### ISSUE TITLE
f9/f12 keys do not work in normal mode

### ISSUE THREAD

**Issue by iuliantatarascu** [NeoVintageous/NeoVintageous#1002]
**Describe the bug**

f9/f12 keys do not work in normal mode

**To Reproduce**

Steps to reproduce the behaviour:

1. create new tab
2. insert multiple lines
```
foo
bar
baz
```
3. enter normal mode
4. press F9 key (which runs the `sort_lines` command)
5. see error in console

**Expected behaviour**

the lines to be sorted:
```
bar
baz
foo
```

**Actual behaviour**

the lines have not been sorted if pressing the key
```
foo
bar
baz
```

(opening the command palette and selecting "Sort Lines" does work as intended)

**Versions**

Sublime Text: `startup, version: 4169 linux x64 channel: stable`

NeoVintageous: `1.34.1 - 2024-12-08`

**Additional Information**

f12 key (`goto_definition`) does not work either
f1-f8,f10-f11 seem to work

command + input log:
<details><summary>expand</summary>

```
command: new_file
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_unknown"}
command: hide_overlay
chr evt: i (0x69)
command: nv_feed_key
command: mark_undo_groups_for_gluing
command: nv_enter_insert_mode {"count": 1, "mode": "mode_internal_normal", "register": "\""}
chr evt: f (0x66)
chr evt: o (0x6f)
chr evt: o (0x6f)
key evt: enter
command: insert {"characters": "\n"}
chr evt: b (0x62)
chr evt: a (0x61)
chr evt: r (0x72)
key evt: enter
command: insert {"characters": "\n"}
chr evt: b (0x62)
chr evt: a (0x61)
chr evt: z (0x7a)
key evt: escape
command: nv_feed_key {"key": "<esc>"}
command: nv_enter_normal_mode {"mode": "mode_insert"}
command: hide_overlay
command: glue_marked_undo_groups
key evt: f9
command: nv_feed_key {"key": "<f9>"}
command: sort_lines {"case_sensitive": false, "count": 1, "mode": "mode_internal_normal", "register": "\""}
Traceback (most recent call last):
  File "/home/<user>/Desktop/sublime_text/Lib/python38/sublime_plugin.py", line 1698, in run_
    return self.run(edit, **args)
TypeError: run() got an unexpected keyword argument 'count'
key evt: f12
command: nv_feed_key {"key": "<f12>"}
command: goto_definition {"count": 1, "mode": "mode_internal_normal", "register": "\""}
Traceback (most recent call last):
  File "/home/<user>/Desktop/sublime_text/Lib/python38/sublime_plugin.py", line 1658, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'count'
```
</details>

**Comment by gerardroche** [comment]
Thanks. I can reproduce it. In the mean time I suggest using
alternatives like `CTRL-]` for goto definition and the `:sort` command
for sorting.

If you're using lsp I can suggest mappings like:

```
noremap <C-w>gd :LspSymbolDefinitionSplit<CR>
noremap gd :LspSymbolDefinition<CR>
```

Or only for some file types:

```
noremap FileType css,go,html,js,php,vue <C-w>gd :LspSymbolDefinitionSplit<CR>
noremap FileType css,go,html,js,php,vue gd :LspSymbolDefinition<CR>
```

**:sort**

To sort an entire file:

```
:%sort
```

Unique sort:

```
:%sort u
```

Sort a pragraph:

```
vip:sort
```

Create a mapping so you can do it via `,ss`:

```
let mapleader=,
nnoremap <leader>ss vip:sort u<CR>
```

See the [readme](https://github.com/NeoVintageous/NeoVintageous?tab=readme-ov-file#neovintageousrc) on usage of mappings and the rc file.

Also my blog for some tips and usage: https://blog.gerardroche.com/2023/09/28/neovintageous-1.33.0/#effortless-reverse-sorting

The roadmap shows what is currenty impemented for `:sort`:

| Status             | Command                                    | Description
| :----------------- | ------------------------------------------ | :----------
| :heavy_check_mark: | <code>:[range]sor[t]!&nbsp;[i][u]</code>   | Sort lines in `[range]`.  When no range is given all lines are sorted. <br><br>With `[!]` the order is reversed. <br><br>With `[i]` case is ignored.<br><br>With `[u]` (u stands for unique) only keep the first of a sequence of identical lines (ignoring case when `[i]` is used).  Without this flag, a sequence of identical lines will be kept in their original order. Note that leading and trailing white space may cause lines to be different.

https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md#7-sorting-text

See also `:help :sort`.
