### ISSUE TITLE
Support for :simalt to activate menus

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#1004]
The alt+X remapping docs mention that there is a substitute for when you've remapped Alt+F, but still want to activate the F menu - you use `|:simalt|` command https://github.com/NeoVintageous/NeoVintageous/issues/579

But as far as I understand, it's still not implemented?

**Comment by gerardroche** [comment]
I don't understand. Are you looking for one of:

```
set winaltkeys=menu
set winaltkeys=yes
set winaltkeys=no
```

**Comment by eugenesvk** [comment]
No, I'm looking for a key combo that can open the File menu even when the original Alt+F shortcut is used by NV to execute something else, so something like `:map <C-M-f> :simalt f<CR>`

> 							*:simalt* *:sim*
:sim[alt] {key}		simulate pressing {key} while holding Alt pressed.
			{only for Win32 versions}
			Note: ":si" means ":s" with the "i" flag.

https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/gui_w32.txt

**Comment by gerardroche** [comment]
The `:simalt` command is not implemented.

**Comment by gerardroche** [comment]
Moved to roadmap doc.
