### ISSUE TITLE
Replace mode doesn't repeat count set before entering

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#1005]
In nvim `5RaEsc` would repeat `a` 5 times overwriting current text, so Replace mode repeats the `5` count

In NeoVintageous there is no repeat, the `5` count is reset on entering Replace mode?

**Comment by gerardroche** [comment]
Moved to [roadmap doc](https://neovintageous.github.io/roadmap)

**Comment by eugenesvk** [comment]
I've excluded count from being reset at one spot as a workaround https://github.com/eugenesvk/NeoVintageous/commit/d3c96092a599a1628ef4359530aea7ab37236566

will see if this has any negative effects
