### ISSUE TITLE
it motion in an empty XML element removes extra character

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#101]
<a href="https://github.com/DaanDD"><img src="https://avatars2.githubusercontent.com/u/1300724?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [DaanDD](https://github.com/DaanDD)**
_Thursday Jan 08, 2015 at 11:13 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/805_

----

When I type cit to enter content in an empty XML element, Vintageous removes the '<' character of the closing element, like this:

``` html
<div>/div>
```

dit also removes the '>' character of the opening element, like this:

``` html
<div</div>
```

**Comment by gerardroche** [comment]
@DaanDD I'm unable to reproduce this in the latest version of NeoVintageous (1.5.1), perhaps it haas been fixed in previous version? NeoVintageous is fork of the discontinued Vintageous plugin.

**Comment by DaanDD** [comment]
@gerardroche This is a long time ago, I don't use Sublime Text anymore, so it could probably be fixed by now.

**Comment by gerardroche** [comment]
Thanks. It *was* a long time ago. I'm reviewing all old issues trying to eitehr resove them or close them. Thanks for the reply.
