### ISSUE TITLE
Support for Ctrl-A/X (Increment/Decrement numbers)

### ISSUE THREAD

**Issue by nk9** [NeoVintageous/NeoVintageous#1011]
**Description**

I'd like to use Vim's Ctrl-A/X to increment/decrement numbers. [This bug](https://github.com/NeoVintageous/NeoVintageous/issues/737) from 2020 says that you can do this if you turn on "Toggle CTRL Keys". But I've done that, and Ctrl-A just jumps the cursor to the beginning of the line. (Which, interestingly, is what Ctrl-A does in Emacs mappings. Coincidence?) Ctrl-X does nothing.

[The docs say](https://neovintageous.github.io/roadmap#_3-simple-changes) that Ctrl-A/X should work now. Am I doing something wrong, or has this perhaps stopped working at some point?

**Steps to reproduce**

Steps to reproduce the behaviour:

1. Turn on "Toggle CTRL Keys" via the Command Palette
1. Put an integer on a line in a file.
1. In Normal mode, put the cursor on or before the number.
1. Press Ctrl-A

**Expected behaviour**

The cursor should jump to the first integer and increment it.

**Actual behaviour**

The cursor jumps to the beginning of the line

**Version**

```
startup, version: 4169 osx arm64 channel: stable
```

NeoVinteagous 1.35.0

**Comment by gerardroche** [comment]
When you turn ctrl on, do other ctrl keys like ctrl-d (scroll downwards) and ctrl-u (scroll upwards) work?

**Comment by gerardroche** [comment]
Maybe you have some other plugin installed because I think ctrl-a should _select all_ when ctrl keys is off. 

Try enabling logging to see if some other command is being run on ctrl-a: https://neovintageous.github.io/contributing#debugging

**Comment by gerardroche** [comment]
Try enabling command and input logging and then press ctrl-a. You should see the following in the console log:

```
key evt: ctrl+a
command: nv_feed_key {"key": "<C-a>"}
command: nv_vi_modify_numbers {"count": 1, "mode": "mode_internal_normal", "register": "\""}
```

That would indicate that NeoVintageous is actually being called. If something else if being called, then it's probably being overridden by a plugin. I use Origami, MarkdownPreview, and SublimeLinter, so it's probably not those. If something is overriding the key, disable the plugins until you find it.

One other thing, check your keymaps to see if you override those keys and forgot about it: Menu → Preferences →  Key Bindings.

**Comment by nk9** [comment]
I turned on logging, and pressing ctrl-a prints:

```
key evt: ctrl+a
key evt: ctrl+a
```

The increment functionality still wasn't working.

However, when I ran "Toggle CTRL Keys" again, the increment/decrement feature started working! However, the logging didn't change. So this seems strange in two different ways, but I guess my problem is solved.

**Comment by gerardroche** [comment]
The ctrl keys were disabled or stuck for some reason.

It looks like you only enabled input logging. Command logging would log the commands being run too.

```
sublime.log_commands(True)
sublime.log_input(True)
```
