### ISSUE TITLE
Multiple cursors ignores case depending on last search case options

### ISSUE THREAD

**Issue by metalbass** [NeoVintageous/NeoVintageous#1012]
**Description**

Depending on your last search options, selecting multiple lines using multiple cursors can be case sensitive or not.

**Steps to reproduce**

Given the following code:

    static void PresentBufferToWindow(HWND window, const BackBuffer& buffer)
    {
        HDC deviceContext = GetDC(window);
        RECT clientRect   = {};
        GetClientRect(window, &clientRect);

        int windowWidth  = clientRect.right - clientRect.left;
        int windowHeight = clientRect.bottom - clientRect.top;

        ...
    }

1. Open Sublime's Find view through Menu > Find > Find... and make sure that the search is configured as case insensitive.
1. Put your caret on top of `clientRect`
2. Press `<C-n>` to select the whole word.
3. Press `<C-n>` again to select the next ocurrence, which is now  `ClientRect`, a subset of the `GetClientRect` name.
4. Change to search sensitive options in the Find menu and repeat steps 1 to 4 and notice how `GetClientRect`is skipped.

**Expected behaviour**

multiple cursors's `<C-n>` shouldn't depend on how you used sublime's built-in search last time.

**Actual behaviour**

multiple cursors's `<C-n>` depends on how you used sublime's built-in search last time, making it inconsistently case insensitive.

**Version**

```
startup, version: 4169 windows x64 channel: stable
```

**Additional Information**

After a quick code examination, I think multiple cursors ends up calling sublime's built-in `find_under_expand` command, which seems to depend on the current user find options.

I've seen some users online attempting to find the values of the current user find options here:
https://forum.sublimetext.com/t/how-to-get-the-status-of-case-sensitive-and-whole-word-in-find-panel/56791/5

**Comment by gerardroche** [comment]
I didn't even realise the finder panel controlled this. There's currently no way to make the `find_under_expand` and related commands case sensitive. But you are right, it should be case sensitive. 

There is maybe a hacky work around, but I'll have to test that is a reasonable workaround.

**Comment by metalbass** [comment]
I just started using NeoVintageous recently, but after configuring Sublime's search once this hasn't been an issue since.

I now feel like this is more of an issue of obscure UX, where it was not easy to understand what was going on, than a bug per se.
Unless Sublime offers an easy API to handle this, it may not be worth the effort to fix it.

Maybe adding a note in [multiple-cursors doc page](https://neovintageous.github.io/plugins/multiple-cursors) would suffice?

**Comment by gerardroche** [comment]
Yeah, I think documenting is the best course of action.  The hacky solution to implement it now is too flaky to implement. When Sublime adds an api for a case sensitivity `find_under_expand`, I'll add it as an optional feature via a setting.
