### ISSUE TITLE
"Wrap Selection with Tag" doesn't work from Visual mode

### ISSUE THREAD

**Issue by nk9** [NeoVintageous/NeoVintageous#1022]
**Description**

In Insert mode, you can use the default <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>W</kbd> shortcut to wrap the selection in an HTML tag. (In the menus: Edit > Tag > Wrap Selection With Tag) However, this shortcut doesn't work from Visual mode. I frequently find myself selecting text in Visual mode, then having to return to Normal mode, then Insert mode, and then select again before I can use <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>W</kbd>.

I'm not sure if I'm doing something wrong, if this really is a bug, or if it's a feature that's missing or has been intentionally skipped. But I wanted to see if there's anything that could be done to remedy this.

**Steps to reproduce**

Steps to reproduce the behaviour:

1. Select some text using <kbd>v</kbd> for visual mode, or by selecting text with the mouse from Normal mode
1. Press <kbd>Ctrl</kbd>-<kbd>Shift</kbd>-<kbd>W</kbd> ("Wrap Selection with Tag" shortcut)

**Expected behaviour**

I'd expect to enter Insert mode, with the selection having been wrapped in the default `<p>` Tag, and the multi-selection being set up correctly (both starting and ending tag selected).

**Actual behaviour**

Nothing happens.

**Version**

```
startup, version: 4169 osx arm64 channel: stable
```

NeoVintageous: v1.35.1

**Comment by itsmewes** [comment]
I usually use `Surround` for this. When something is in visual mode, I'll type something like `S<p>` (capital `S`) and it will wrap it. Or `S<p class="hello">` to add an attribute. Not sure if this would be helpful in the interim.

**Comment by nk9** [comment]
Thanks for the suggestion, but that's not working for me?

https://github.com/NeoVintageous/NeoVintageous/assets/3646730/196b9896-fe4c-4eff-b37c-c07bed76207e

**Comment by itsmewes** [comment]
Hmmm, it's strange that is adds the `<` immediately, for me nothing happens until I press `>` or `enter`. The screen recording doesn't show the exact keys pressed but I pressed `S<p>` and it seemed to work as expected. 


https://github.com/NeoVintageous/NeoVintageous/assets/974222/ffaa5c7d-7978-4712-a58c-b3124c5d312a

**Comment by gerardroche** [comment]
The surround command `S` is probably best `S<p>`.

fyi you can disable keys, this disables Alt+Shift+w in visual mode:

```
    "vintageous_handle_keys": {
        "v_<M-W>": false,
    },
```

See https://neovintageous.github.io/reference/settings#vintageous-handle-keys

This would still require you to press c after alt+shift+w, to enter insert mode. So you would press alt+shift+w, then c.

The surround method using `S` is still better because that's what's it's designed for. 

Surround docs: https://github.com/tpope/vim-surround/blob/master/doc/surround.txt

And status in nv: https://neovintageous.github.io/plugins/surround

**Comment by nk9** [comment]
Oh, that's great! I used this:

```json
	"vintageous_handle_keys": {
		"v_<C-W>": false,
	},
```

Yes, I have to press `c` after… but this way I don't have to remember a new keyboard shortcut for the wrapping, and I get to see the text as I type it. Plus… it actually works, which `S<p>` doesn't, for some reason. Happy to try to debug why `S` is failing to insert the final `>`, if that would help matters. (See my video above.) But I have an answer that works for me, so we can also close this now.
