### ISSUE TITLE
Not able to use some Sublime Text shortcuts in normal mode

### ISSUE THREAD

**Issue by hronro** [NeoVintageous/NeoVintageous#1025]
I'm using macOS, and when this plugin is enabled, I can't use <kbd>⌘</kbd> + <kbd>c</kbd> to copy text to the system clipboard or <kbd>⌘</kbd> + <kbd>n</kbd> to open a new tab in normal mode. However, these shortcuts work in insert mode.

As the <kbd>⌘</kbd> key doesn't conflict with Vim key bindings, is there a way to use these shortcuts in normal mode?

**Comment by pigeon-999** [comment]
i was able to use ⌘ key after disabling the option below.
- [vintageous_use_super_keys](https://neovintageous.github.io/reference/settings#vintageous-use-super-keys)

**Comment by gerardroche** [comment]
Yes. You can disable super keys, they are enabled by default. Similarly control keys are enabled by default and can be disabled. 

There are toggle commands for both in the command palette.

If you only want to disable some keys, even in specific modes, you can use the `vintageous_handle_keys` settings:

```
"vintageous_handle_keys": {
    "<C-f>": false
}
```

See https://neovintageous.github.io/reference/settings#vintageous-handle-keys
