### ISSUE TITLE
Pasting multiple lines inserts them within the current line

### ISSUE THREAD

**Issue by JJMorton** [NeoVintageous/NeoVintageous#1027]
**Description**

In vim, pasting multiple lines inserts them on new lines, regardless of where the cursor is. With NeoVintageous, the lines are often inserted at the current cursor position.

Similar to issue #762

**Steps to reproduce**

Start with multiple lines, e.g.
```
AAA
BBB
CCC
```
with the cursor over the first 'A'.

**Expected behaviour**

After yanking two lines with `yj`, pressing `p` should paste the yanked lines after the 'AAA', giving
```
AAA
AAA
BBB
BBB
CCC
```

**Actual behaviour**

Instead, I get
```
AAAA
BBB
AA
BBB
CCC
```
i.e. the pasted text starts at the cursor position, rather than on the next line.

**Version**

```
startup, version: 4180 osx arm64 channel: stable
```

**Additional Information**

The same happens if I yank the whole paragraph with `yap`.

The result is especially confusing if the text is indented, with the indent being pasted at the cursor position, within the current line.

Interestingly, the issue is not present if I yank more than two lines. e.g. `y2jp` or `2yjp` work as expected. I assume this is a result of fixing issue #762.

**Comment by gerardroche** [comment]
Thanks.
