### ISSUE TITLE
implement lazy loading

### ISSUE THREAD

**Issue by tfriedel** [NeoVintageous/NeoVintageous#1028]
**Is your feature request related to a problem? Please describe.**
I have many (~100) files open in Sublime. Without NeoVintageous enabled start up time is fast.
With NeoVintageous enabled directly after start there is a long time (2-3 minutes?) during which Sublime is unresponsive.
I suspect EVER file is opened and processed by NeoVintageous.

**Describe the solution you'd like**
Only process the currently visible file with NeoVintageous. I.e. implement lazy loading where files are only processed
by NeoVintageous when it is really required. 

**Describe alternatives you've considered**
Toggle NeoVintageous per file. However this is also not yet possible, the NeoVintageous toggle plugin can only
toggle it for all files or none.

**Additional context**
Interestingly when I installed NeoVintageous (with the 100+ files open), I observed no unresponsiveness.
This only became an issue after restarting Sublime.

**Comment by gerardroche** [comment]
This only happens when lots of files are opened?

I can't think why this would be an issue, only the activated file should
be initalised on start and the init is very minimal.

If it also happens when only one file is open, then I'm thinking of
several things:

- The session is loaded on start
- The `.neovintageousrc` is loaded on start

The session or rc file might be large.

**Check the rc file**

Command Palette → Open neovintageousrc file

**Check the size of the session file**

Command Palette → Browse Packages

Navigate back on folder, into the Local folder and look for `neovintageous.session`.
It's a json format file.

Check the size and contents of it and then move it out of the way and
try starting again. Keep the file so that we can maybe debug the
underlying issue, if this is actually the cause.

**Start sulime in neovintegeous debug mode**

```
SUBLIME_NEOVINTAGEOUS_DEBUG=DEBUG subl
```

https://neovintageous.github.io/contributing

**Comment by gerardroche** [comment]
Thanks. It looks like something is seriously wrong.

I think there is an issue parsing modelines.

Does the active file have modelines? The default is to check the top 5
and bottom 5 lines of the file. Modelines will look like this:

```
# vim: number
```

See https://vimdoc.sourceforge.net/htmldoc/options.html#auto-setting

Turn off modeline by adding this to your neovintageousrc:

```
set nomodeline
```

Restart.

I'm digging through the log now to try figure out why the modeline is
parsing the way it is, maybe an infinite loop.

If turning off modeline resolves it and if the file has a modeline, can you post it. Or post the top 5, bottom lines of the file.

How big is the active file? Is everything on one line?

I think modeline is parsing an entire file.

**Comment by gerardroche** [comment]
It looks like modeline is loosely and greedily parsing the file. It will
be parse anything in the top 5 or botton 5 files that match things like
`vim: *` so if everything is on one file it looks like it tries
everything after `vim: `.

**Comment by tfriedel** [comment]
I think we are onto something!
I searched the open files for "ex:" and "vim:"
Even though I don't have any vim configuration files open, I still had a few matches. After a bit of bisecting I narrowed it down to "conversations.json", an export of all my ChatGPT conversations. If that is part of the opened files, we have the problem.
Note that it doesn't have to be the active file!
This file has a size of 27 MB and consists of only one (very long) line of json.

What could be done to improve the situation:
- when parsing for modelines, only consider the first n characters in each line (e.g. max 1024). 
- only consider active files, not all files maybe

**Comment by gerardroche** [comment]
I've been looking into Vim to see what it does and there doesn't appear
to be any constraints, but that's not really an option for us. There is
no effecient way, at least that I can see, that we do that in Sublime.

Sublime has an `find()` api, which is effecient, but search the the
entire file and there's no way to constrain it to one line. A pity.

So, yes, I've reworked it to only check up to n characters per line.

I can't imagine many modelines exceeding much over 100 characters, I
think I'll bring it all the way back to 256 per line. I just can't see
anything exceeding that?

> only consider active file, not all files maybe

It should only be applied to the active file. That is something I'm
curious about. Modelines is only applied when the view is loaded, which
shouldn't be happening on start when the view is already loaded. Perhaps
some other plugin is opening the file on start.

**Comment by tfriedel** [comment]
Thanks for fixing this! 
I'd agree 256 characters should be enough, but then I'm not knowledgeable about modelines.

Regarding another plugin maybe doing something with the file... could be.
