### ISSUE TITLE
Support for jumping between issues reported by LSP

### ISSUE THREAD

**Issue by JonathanHolvey** [NeoVintageous/NeoVintageous#1029]
NeoVintageous's implementation of the vim-unimpaired plugin supports the `]l` and `[l` movements, which jump the cursor position between issues reported by SublimeLinter. It would be nice to have the same ability when using LSP for linting instead.

The Sublime Text LSP package exposes this functionality through it's `lsp_next_diagnostic` and `lsp_prev_diagnostic` commands.

**Comment by itsmewes** [comment]
I'm not sure if this is helpful but I have added the below to my `.neovintageousrc` to get that functionality. I stole this from  [Gerard Roche's .neovintageousrc](https://github.com/gerardroche/sublimefiles/blob/0d5da4d436490f213506a866a59d8dd861173f2f/User/.neovintageousrc). There are some other great options in there as well.

```
nnoremap [d :LspPrevDiagnostic<CR>
nnoremap ]d :LspNextDiagnostic<CR>
```

**Comment by gerardroche** [comment]
My current suggested mappings for LSP are modeled on lazyvim:


```
" http://www.lazyvim.org/keymaps#lsp
nnoremap FileType css,go,html,js,php,vue <Leader>ca :LspCodeActions<CR>
nnoremap FileType css,go,html,js,php,vue <Leader>cc :LspCodeLens<CR>
nnoremap FileType css,go,html,js,php,vue <Leader>cs :LspSymbolRename<CR>
nnoremap FileType css,go,html,js,php,vue K :LspHover<CR>
nnoremap FileType css,go,html,js,php,vue [d :LspPrevDiagnostic<CR>
nnoremap FileType css,go,html,js,php,vue ]d :LspNextDiagnostic<CR>
nnoremap FileType css,go,html,js,php,vue gD :LspSymbolDeclaration<CR>
nnoremap FileType css,go,html,js,php,vue gI :LspSymbolImplementation<CR>
nnoremap FileType css,go,html,js,php,vue gK :LspSignatureHelpShow<CR>
nnoremap FileType css,go,html,js,php,vue gd :LspSymbolDefinition<CR>
nnoremap FileType css,go,html,js,php,vue gr :LspSymbolReferences<CR>
nnoremap FileType css,go,html,js,php,vue gy :LspSymbolTypeDefinition<CR>
```

The default leader key in LazyVim is `<Space>`, but I like `,` (comma):

```
let mapleader=","
let maplocalleader="<Bslash>"
```

If you prefer space:

```
let mapleader="<Space>"
let maplocalleader="<Bslash>"
```

The default is `<Bslash>` so I like to move that to the localleader,
though I never use it.

See my rc file for more:

https://github.com/gerardroche/sublimefiles/blob/master/User/.neovintageousrc#L77C1-L89C73

Some of my mappings require custom commnds. I'm going to try move all my
custom commands to their own package so everyone interested can use
them.

Thanks @itsmewes

**Comment by gerardroche** [comment]
Also see https://neovintageous.github.io/reference/key-mapping
