### ISSUE TITLE
Anyway to leave the program using NeoVintageous while preserving the session?

### ISSUE THREAD

**Issue by alienbogart** [NeoVintageous/NeoVintageous#1030]
Simple put, all the Vim commands I use to quit the program have the result of erasing the session in such a way that when I open Sublime later on there are no files open and I start from scratch. Nothing seems to work: `ZZ`, `:quit`, `:qa!<cr>`, `wqa!<cr>`, etc, all seem to close all the files before leaving the program. If I disable Neovintageous, everything works fine. And I can't really leave the program using `Alt+F4` either, as NeoVintageous seems to block it. Is there a way for me to get past this?

I am running Sublime Text 4 build 4180 on Windows.

Thanks!

**Comment by alienbogart** [comment]
Forget about it, solved after reading this: https://neovintageous.github.io/reference/key-mapping#mapping-sublime-text-commands. `nnoremap ZZ :Exit<cr>` did the trick (`ZZ`can be replaced by whatever you want...). It calls the Sublime command quit, which is why it works, while `nnoremap ZZ :exit<cr>` doesn't. Anyway, I think it would be nice if quitting via NeoVintageous did that by default. Something to think about. In any case, that might be a good addiction to the documentation. Personally, my issue is resolved, so I'm closing it now.

**Comment by gerardroche** [comment]
Interesting. I had to check how I quit. I enter insert mode and press `CTRL-q`.

`CTRL-q` in insert mode is the exit command (Menu → File → Quit).

The reason this works is a side-effect of the fact NeoVintageous doesn't currently implement many insert commands. So nearly all insert mode key bindings default to the default Sublime Text key binding. `CTRL-q` binds to exit.

I wonder if Vim has command for this use-case.
