### ISSUE TITLE
Triple click to select line not working outside insert mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#104]
<a href="https://github.com/mwhoffman"><img src="https://avatars2.githubusercontent.com/u/1824561?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mwhoffman](https://github.com/mwhoffman)**
_Wednesday Jan 07, 2015 at 17:38 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/804_

----

When in insert mode double-clicking will select a word and triple-clicking will select a line. However outside of insert mode double-clicking still appears to work, but the triple-click behavior does not.

Adding an additional check to `xsupport.py` on line 62 for `args.get('by') == 'lines'` appears to fix this behavior, but as I'm not totally sure what's going on in the rest of the code I can't really verify that this doesn't break anything else.

**Comment by Clor** [comment]
Any information here? I'd like to reinstate the normal triple-click behavior; but I don't know in which file to make changes.

**Comment by gerardroche** [comment]
@mwhoffman This was fixed in NeoVintageous 1.5.2 https://github.com/NeoVintageous/NeoVintageous/issues/306. Note: NeoVintageous is a fork of the discontinued Vintageous plugin.

@Clor Can you confirm that this was fixed 1.5.2? 

Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/306
