### ISSUE TITLE
A couple minor issues: ^d (^f/^u/...) not going to top/bottom of buffer fully, x can delete lines

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#105]
<a href="https://github.com/ebrady"><img src="https://avatars3.githubusercontent.com/u/1985373?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ebrady](https://github.com/ebrady)**
_Monday Nov 03, 2014 at 05:31 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/782_

----

The basic minor issues are (if you want me to file two issues that's fine):

# 1

If I go to an empty line at type 'x' (or '9x') in escape mode it should be a no-op but instead it deletes the line (this behaves correctly if the line has any content, it removes the number of characters desired and does not delete the line, only on an empty line is it misbehaving and deleting the line itself)

# 2

In 'vim' if i use ^d (or ^f, or ^u and other equivalents to scroll down/up) they will always go up or down if there is any "room" left to go... with Vintageous it will only scroll up or down if there are enough lines above or below for the given scroll action to go (eg: if ^d has 30 lines above, no problem, it scrolls... but if it has 3 lines above it doesn't scroll to the top of the buffer).  It should always scroll all the way to the beginning or end of the buffer (depending on the control sequence) even if there are only a few lines that can be scrolled in that direction.  To test, open a file, scroll down 3 or 4 lines, hit ^u, should go to the 1st line, or go to the bottom of the file, scroll up a few lines and hit ^d, it should go to the last line in the file

Appreciate your time and consideration as always.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Dec 22, 2014 at 13:07 GMT_

----

Better to split this into two issues.

**Comment by gerardroche** [comment]
@ebrady These issue have been fixed in NeoVintageous 1.6.0 (NeoVintageous is a fork of the discontinued Vintageous plugin).

**Comment by ebrady** [comment]
Thanks for the update... I will check that out!
