### ISSUE TITLE
'g;', 'g,' and 'gi' commands not implemented

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#106]
<a href="https://github.com/mikedmcfarland"><img src="https://avatars1.githubusercontent.com/u/3240061?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mikedmcfarland](https://github.com/mikedmcfarland)**
_Sunday Nov 16, 2014 at 20:20 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/785_

----

These commands are missing in vintagious, and are very helpful for navigating though recent changes made in the file.

In Vim:
'g;' Jumps backward in the changelist
'g,' Jumps foward in the change list
'gi' Jumps backward in the changelist and puts your cursor there in insert mode.

In vintageous the commands do nothing.
(I grouped them since they seem very much related, as they act on the changelist)

**Comment by gerardroche** [comment]
<a href="https://github.com/mikedmcfarland"><img src="https://avatars1.githubusercontent.com/u/3240061?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mikedmcfarland](https://github.com/mikedmcfarland)**
_Tuesday Nov 18, 2014 at 19:53 GMT_

----

By the way, thank you for this plugin. I'm able to use both sublime and vim (where it's convenient to do so) with hardly any issues. These commands are the only real important one's i miss.

**Comment by gerardroche** [comment]
<a href="https://github.com/PrestanceDesign"><img src="https://avatars0.githubusercontent.com/u/1840522?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [PrestanceDesign](https://github.com/PrestanceDesign)**
_Friday Jun 19, 2015 at 12:37 GMT_

----

+1 Very useful commands

**Comment by sdemura** [comment]
+1 for this. Please add!

**Comment by bfulop** [comment]
(Sorry for the spam,) the ability to jump back to previous edit locations is something I miss daily. There's the "native" jump back functionality but it's not as precise/reliable as I would like it to be.

**Comment by gerardroche** [comment]
A rough implementation of `g;` and `g,` will be available in the next release. I might do `gi` too because that's just adding enter insert after `g;`.

I don't think it will work exactly right, but I'm pretty I can improve them going forward.
