### ISSUE TITLE
Paste and indent behavior

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#11]
<a href="https://github.com/trkoch"><img src="https://avatars0.githubusercontent.com/u/73974?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [trkoch](https://github.com/trkoch)**
_Tuesday Apr 30, 2013 at 11:26 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/207_

----

Vintageous currently lacks a convenient way to paste and indent. For instance, when working with html markup, wrapping a chunk of markup in a new element involves selecting, yanking, pasting, re-selecting, indenting.

As discussed in https://github.com/guillermooo/Vintageous/issues/168, one approach is to paste (`p`), select previous paste (e.g. `gp`) and indent (`==`).

I have this in my `.vimrc`

```
nnoremap <expr> gp '`[' . strpart(getregtype(), 0, 1) . '`]'
```

Could something like this be implemented in Vintage?

Another option may be to map `p` and `P` to the paste with indent command of Sublime but this would be a rather big difference to standard Vim behavior.

**Comment by gerardroche** [comment]
<a href="https://github.com/trkoch"><img src="https://avatars0.githubusercontent.com/u/73974?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trkoch](https://github.com/trkoch)**
_Monday Jul 01, 2013 at 18:35 GMT_

----

Any news on this? `gp` would be immensely useful. In case you've been thinking about this already, what approach would you take?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Jul 01, 2013 at 19:24 GMT_

----

Haven't given any thought to this yet, no... I somewhat agree that paste and indent is generally useful.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Jul 01, 2013 at 19:27 GMT_

----

What does your custom mapping do?

Remapping is something that I want to have, but it looks like a rather big task.

**Comment by gerardroche** [comment]
<a href="https://github.com/trkoch"><img src="https://avatars0.githubusercontent.com/u/73974?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trkoch](https://github.com/trkoch)**
_Monday Jul 01, 2013 at 19:29 GMT_

----

It selects previously pasted text. See http://vim.wikia.com/wiki/Selecting_your_pasted_text.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Sunday May 25, 2014 at 16:32 GMT_

----

Indenting after `p` is now the default behavior.

**Comment by gerardroche** [comment]
<a href="https://github.com/trkoch"><img src="https://avatars0.githubusercontent.com/u/73974?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [trkoch](https://github.com/trkoch)**
_Sunday May 25, 2014 at 18:14 GMT_

----

Nice. Is there a way to paste without indenting? `gp`?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday May 26, 2014 at 05:25 GMT_

----

I immediately missed the ability to do that after the change, but no, there isn't at the moment. I'll add this to the todo list, though.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Thursday May 29, 2014 at 10:13 GMT_

----

I'll revert this change. Pasting and indenting is less useful than pasting without indenting. As far as I can tell, ST 's built-in command gets it wrong quite often. The mapping you indicate above should work in Vintageous at some point, but that won't likely happen until after Vintageous hits 4.0.

**Comment by gerardroche** [comment]
<a href="https://github.com/P233"><img src="https://avatars1.githubusercontent.com/u/1818679?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [P233](https://github.com/P233)**
_Friday Jul 25, 2014 at 20:53 GMT_

----

Could you add support of `]p` and `[p` ? thanks

**Comment by gerardroche** [comment]
<a href="https://github.com/xiaogwu"><img src="https://avatars1.githubusercontent.com/u/7885?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [xiaogwu](https://github.com/xiaogwu)**
_Saturday Nov 21, 2015 at 05:17 GMT_

----

I like P233's idea

**Comment by gerardroche** [comment]
Duplicate of #339

**Comment by sourcevault** [comment]
It seems `neovintageous` doesn't support `<expr>` for now ?

``
nnoremap <expr> ' "'" . nr2char(getchar()) . "zz"
``

I get this error :

```
command: neovintageous {"action": "reload_rc_file"}
Traceback (most recent call last):
  File "C:\Users\......\AppData\Roaming\Sublime Text\Packages\NeoVintageous\nv\mappings.py", line 98, in _normalise_lhs
    return ''.join(tokenize_keys(expand_keys(lhs)))
  File "C:\Users\i_fac\AppData\Roaming\Sublime Text\Packages\NeoVintageous\nv\vi\keys.py", line 203, in _iter_tokenize
    token = self._tokenize_one()
  File "C:\Users\......\AppData\Roaming\Sublime Text\Packages\NeoVintageous\nv\vi\keys.py", line 197, in _tokenize_one
    return self._expand_vars(self._long_key_name())
  File "C:\Users\......\AppData\Roaming\Sublime Text\Packages\NeoVintageous\nv\vi\keys.py", line 188, in _long_key_name
    raise ValueError("'<{0}>' is not a known key".format(key_name))
ValueError: '<expr>' is not a known key
```

**Comment by gerardroche** [comment]
Yes, `<expr>` is not supported. The mappings is limited. Things like `nr2char` won't work.
