### ISSUE TITLE
Support "special marks"

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#117]
<a href="https://github.com/alecthomas"><img src="https://avatars0.githubusercontent.com/u/41767?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [alecthomas](https://github.com/alecthomas)**
_Thursday Apr 16, 2015 at 00:24 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/924_

----

Vim has a bunch of ["special marks"](http://vim.wikia.com/wiki/Using_marks#Special_marks) that would it would be nice to have support for. In particular "``" is very useful for jumping back to the previous position jumped from.

**Comment by gerardroche** [comment]
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/198

**Comment by sourcevault** [comment]
To go to the next line with a (lowercase) mark, I can do:

    ]'

And to go to the previous mark I can do:

    ['


https://stackoverflow.com/questions/61946832/how-to-cycle-through-vim-marks

----

Unable to reproduce it on my system,  don't think it is implemented.
