### ISSUE TITLE
Relative Line Numbers

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#13]
<a href="https://github.com/joshbetz"><img src="https://avatars2.githubusercontent.com/u/300429?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [joshbetz](https://github.com/joshbetz)**
_Friday May 10, 2013 at 20:32 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/214_

----

Maybe I'm dreaming, but the option to have relative line numbers while in normal mode would be super duper amazingly awesome.

**Comment by gerardroche** [comment]
<a href="https://github.com/gmosteoru"><img src="https://avatars3.githubusercontent.com/u/4339287?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [gmosteoru](https://github.com/gmosteoru)**
_Saturday May 11, 2013 at 16:05 GMT_

----

Try vintageLines https://github.com/tmanderson/VintageLines

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday May 11, 2013 at 21:42 GMT_

----

I don't know whether this is possible in a reliable way, but I'll take a look at the referenced package and see if I can borrow that.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Jul 08, 2013 at 21:31 GMT_

----

#259

**Comment by gerardroche** [comment]
<a href="https://github.com/hoang-tran"><img src="https://avatars0.githubusercontent.com/u/6714157?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [hoang-tran](https://github.com/hoang-tran)**
_Tuesday Aug 23, 2016 at 15:58 GMT_

----

any updates on this @guillermooo ?

**Comment by gerardroche** [comment]
<a href="https://github.com/qazip"><img src="https://avatars3.githubusercontent.com/u/16175716?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [qazip](https://github.com/qazip)**
_Friday Mar 10, 2017 at 10:34 GMT_

----

I would also like this feature.

**Comment by gerardroche** [comment]
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/13

**Comment by trishume** [comment]
@gerardroche This issue was closed as a duplicate of itself. Did you mean to do that?

Also it's possible, but in a hacky way. Two examples:
https://github.com/francescarpi/RelativeLineNumbers
https://github.com/co-dh/VintageLines

**Comment by gerardroche** [comment]
:) No I didn't mean to do that. Relative lines needs to be implemented by ST in core.

**Comment by trishume** [comment]
See the two links I posted, a limited form of them is possible without core changes. I think maybe the best solution is to only add a limited range of maybe 0-9 as gutter icons.

I'm thinking of trying to switch to a Vim style where I use relative line numbers more so I might even implement this myself.

**Comment by trishume** [comment]
Yah I agree it's pretty hacky. I think it should be possible to do something nice that works well as long as it's limited to 0-9 lines away using gutter icons. If I do implement this for my own use and PR it I'll have it disabled by default. But if I do that and you still think it's too crappy I'll be okay with it not being included.

**Comment by gerardroche** [comment]
Closing and moving the issue to the [known issues](https://github.com/NeoVintageous/NeoVintageous/issues/404) section of the roadmap.

There's a feature request on the ST issue tracker: https://github.com/sublimehq/sublime_text/issues/3240
