### ISSUE TITLE
"(" and ")" not jumping correctly

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#134]
<a href="https://github.com/escherpf"><img src="https://avatars3.githubusercontent.com/u/3789736?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [escherpf](https://github.com/escherpf)**
_Friday Mar 06, 2015 at 15:26 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/842_

----

In Vintageous, ")" does not recognize sentence ending with "}." or ")" or "]."

Example:  
In Vim, starting at the beginning of the line, selecting ")" three times advances the cursor to the "f" at the beginning of each sentence as shown below, with brackets indicating cursor position:

[f]oo foo. [f]oo (foo). [f]oo foo. 

In Vintageous, the following occurs when selecting ")" three times, starting at the beginning of the line:

[f]oo foo.[]foo (foo). foo foo.
[]

Two things to note:
1. ")" should advance to the first non-whitespace character of the next sentence. In Vintageous it jumps to the first character of the next sentence, white space or not (not a huge deal).
2. In Vintageous, ")" does not recognize the second sentence, ending in ")." as a sentence and jumps it and the following sentence, ending up at the beginning of the second line.

**Comment by AltitudeApps** [comment]
Hi, I found a bug which might be related to this.

I can perform a "5)" command, which advances the cursor five sentences as expected.

But doing a "5(" command only puts my cursor back a single sentence.
