### ISSUE TITLE
Emacs like movement in Insert Mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#137]
<a href="https://github.com/amosbird"><img src="https://avatars0.githubusercontent.com/u/5085485?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [amosbird](https://github.com/amosbird)**
_Monday Jun 15, 2015 at 14:14 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/971_

----

How can I add customize bindings for Insert mode?  I've been using vim plugin : vim-rsi for quite a long time, it is quite ergonomic for some tasks.

**Comment by gerardroche** [comment]
@amosbird use the keymap context `vi_insert_mode_aware`:

Here's some examples from the docs:

> 4. Mapping jj, jk, CTRL-[, etc. to Esc
>
> Preferences > Key Bindings: >
>
>     # jj -> Esc
>     {
>         "keys": ["j", "j"],
>         "command": "_enter_normal_mode",
>         "args": {"mode": "mode_insert"},
>         "context": [{"key": "vi_insert_mode_aware"}]
>     }
>
>     # jk -> Esc
>     {
>         "keys": ["j", "k"],
>         "command": "_enter_normal_mode",
>         "args": {"mode": "mode_insert"},
>         "context": [{"key": "vi_insert_mode_aware"}]
>     }
>
>     # CTRL-[ -> Esc
>     {
>         "keys": ["ctrl+["],
>         "command": "_enter_normal_mode",
>         "args": {"mode": "mode_insert"},
>         "context": [{"key": "vi_insert_mode_aware"}]
>     }

See the [`:help neovintageous`](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt) command for information.




*NeoVintageous is a fork of the discontinued Vintageous plugin.*

**Comment by amosbird** [comment]
thanks!
