### ISSUE TITLE
f<key> doesn't jump to <key> if there is a mapping for <key>

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#152]
<a href="https://github.com/tom-kuca"><img src="https://avatars0.githubusercontent.com/u/171436?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tom-kuca](https://github.com/tom-kuca)**
_Saturday May 02, 2015 at 12:19 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/948_

----

Mapping a `<key>` to a command in normal mode breaks the functionality of `f<key>` (and also `t<key>`, `F<key>,`, `T<key>,`). I expect that `f<key>` jumps to the next `<key>` character on the line, without invoking the command.
## Example

I want to open a command palette when I press a `,` in the normal mode, but `f,`  should jump to the next comma on the line without opening the pallete. I have just switched for sublime text 2 (Vintage), when the following mapping works as expected:

``` json
{ "keys": [","], "command": "show_overlay", "args": {"overlay": "command_palette"} }
```

I have tried to fix it by adding a proper context. I have searched for them in the `vi/contexts.py` without success. The relevant contexts, like `vi_state_expecting_user_input`, were removed. But in my opinion, it should work even without any context, I can't imagine the situation when I want to invoking anything in the middle of a motion command. But I admit my imagination can be limited.
- Sublime Text 3, Build 3083
- Vintageous - both current build and the version installed by Package manager

I guess that the bug (if it's really a bug) was introduced in a8809e16bb2664b297d3d9d964d45176fc3d5b66.

**Comment by gerardroche** [comment]
<a href="https://github.com/jwkicklighter"><img src="https://avatars2.githubusercontent.com/u/1447947?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jwkicklighter](https://github.com/jwkicklighter)**
_Thursday Aug 11, 2016 at 19:03 GMT_

----

Over a year later and I'm still having this issue as well.

**Comment by gerardroche** [comment]
@tom-kuca @jwkicklighter this will be fixed in the next version of NeoVintageous (1.4.0). In the meantime available from the develop branch: https://github.com/NeoVintageous/NeoVintageous/tree/develop. In case you don't know what NeoVintageous is: it is a fork of the discontinued Vintageous plugin. I show some examples of how to get it working:


Instead of defining the keymap as regular ST keybinding, you use the `.vintageousrc` file to map keys to commands.

Here's the working documentation for the `develop` branch: 

### The .vintageousrc file

A feature comparative to the `.vimrc` file.

The file is located at `Packages/User/.vintageousrc` and is read during startup. It can be opened for editing via the Command Palette: `NeoVintageous: Open My .vintageousrc File`. It can be reloaded too: `NeoVintageous: Reload My .vintageousrc File`.

`let mapleader=`, `noremap`, `nnoremap`, `onoremap`, `vnoremap`, `map`, `nmap`, `omap`, and `vmap` are all supported in basic use-cases. *Note that `map`, `nmap`, `omap`, `vmap` work the same as their `*remap` variants, this is a known issue.*

Mapping to basic ex commands is supported in the form `:excommand<CR>`.

To map to a Sublime Text command, the command must start an uppercase letter, to avoid confusion with builtin ex commands e.g. `:YourCommand<CR>`. The command is converted to snake case.

This is easiest to understand with some examples:

```
" The character " (the double quote mark) starts a comment

let mapleader=,

" Enter command line mode.
nnoremap <space> :

" Toggle the side bar.
nnoremap <leader>d :ToggleSideBar<CR>

" " Make j and k work file linewise instead of screen linewise.
" nnoremap j gj
" nnoremap k gk

" Scroll viewport faster.
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Easy buffer navigation.
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Select entire buffer
nnoremap <leader>vaa ggvGg_
nnoremap <leader>Vaa ggVG

" Test
" https://github.com/gerardroche/sublime-test
" https://github.com/gerardroche/sublime-phpunit
nnoremap <leader>t :TestNearest<CR>
nnoremap <leader>T :TestFile<CR>
nnoremap <leader>a :TestSuite<CR>
nnoremap <leader>l :TestLast<CR>
nnoremap <leader>g :TestVisit<CR>
```

<hr>

There is current;y a limitation in that the commands you map to can't accept arguments so to map to the command to open the Command Palette you need to create a custom command. As I hope you can see, the command is just a proxy to the show_overlay command:

```
class ShowCommandPaletteCommand(WindowCommand):
    def run(self):
        self.window.run_command('show_overlay', {'overlay': 'command_palette'})
```

Now you can map that command to any key in your `.vintageousrc` file, for example to map it to your `<leader>` followed by `cp`:

```
nnoremap <leader>cp :CommandPallette<CR>
``` 

The default leader is `\`. Most people set the leader to `,`, but if you leave the leader as the default then you can map `,` to open the command pallete:

```
nnoremap , :CommandPallette<CR>
``` 

Make sure to remove any existing ST keymaps using the comma, otherwise they will cause issues.

1.4.0 should be released soon enough. Hope you enjoy,

**Comment by tom-kuca** [comment]
It works, awesome! About a month ago, I tried a few different plugins just to found out that all of them suffers from this bug, I'm glad things has changed. 

Just a note, the command name in mapping should match the definition. The mapping should be
```
nnoremap <leader>cp :ShowCommandPallette<CR>
```

**Comment by gerardroche** [comment]
1.4.0 has been released. It took a little longer to get the release out the door. See the forum post on latest release: [NeoVintageous 1.4.0 released zap KAPOW](https://forum.sublimetext.com/t/neovintageous-1-4-0-released-zap-kapow/33172).

**Comment by dvcrn** [comment]
Is it possible to get this working without using .vintageourc? Such as having a custom ST3 context when NeoVintageous is in a ongoing motion?

**Comment by gerardroche** [comment]
@dvcm No that won't be possible because if you use a st context then Sublime captures the key and NeoVintageous doesn't know that the key was pressed. Out of interest what's the reason you can't use the rc file?

**Comment by dvcrn** [comment]
Thanks for the explanation!

Just fragmentation. It's nicer and easier to maintain to have everything in one file, not in multiple split up

**Comment by timfjord** [comment]
I think this problem is still there, at least partly.

For example, when you do
```vim
nnoremap t<C-n> :SomeSublimeCommand<CR>
```
the default vim `t<key>` thing doesn't work anymore but `t<C-n>` works
