### ISSUE TITLE
Allow .vintageousrc to map any keybinds

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#167]
<a href="https://github.com/mreq"><img src="https://avatars3.githubusercontent.com/u/1286942?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mreq](https://github.com/mreq)**
_Tuesday Apr 12, 2016 at 13:22 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1068_

----

It'd be nice if we were able to perform a custom-bound shortcut

Say I'd like to trigger a command, which is bound to `["ctrl+g", "s"]` in sublime keymaps. To remap that via .vintageousrc one'd write:

```
map <Leader>gs <C-g>s
```

I can do something similar using the leader key (space in my case) in the actual sublime keymaps, but that breaks vintageous a bit (for instance movement towards space (`f" "`) doesn't work, etc.).

**Comment by gerardroche** [comment]
@mreq This has been resolved in the latest 1.4.0 release (NeoVintageous is a fork of the discontinued Vintageous plugin):

You can now map to Sublime Text commands from your `vintageousrc` file.

> Mapping to Command-line mode commands is supported for basic use-cases: >
>     :command<CR>
>
> Mapping to Sublime Text commands is supported for basic use-cases. The command
> must start an Uppercase letter to avoid confusion with built-in Command-line
> mode commands. The command is converted to snake_case. For example to map to
> the Sublime Text command "toggle_side_bar": >
>     :ToggleSideBar<CR>
>
> Here is an example |vintageousrc| file: >
>
>     " The character " (the double quote mark) starts a comment
>
>     let mapleader=,
>
>     " Toggle the side bar.
>     nnoremap <leader>d :ToggleSideBar<CR>

See the [`:help neovintageous`](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt) command for information.

Also see the forum post on latest release: [NeoVintageous 1.4.0 released zap KAPOW](https://forum.sublimetext.com/t/neovintageous-1-4-0-released-zap-kapow/33172).

**Comment by mreq** [comment]
Cheers! Looking great.

**Comment by varmanishant** [comment]
Here we are calling the command directly which is very nice. Is it also possible to just map to an existing Sublime Key Binding like say:

`map \u ctrl+enter`

where `ctrl+enter` is just the stock definition from Sublime Keymaps:

`{ "keys": ["ctrl+enter"], "command": "run_macro_file", "args": {"file": xs"} }`

I did create a custom command in `plugin.py` and it works fine. But I am repeating the whole thing there. It would be really nice if I can execute a <kbd>Ctrl+Enter</kbd> through code like say using a dummy function which can invoke the necessary Sublime Key. Any thoughts?

**Comment by varmanishant** [comment]
Thanks @gerardroche. I just did it using the normal plugin way for now.
