### ISSUE TITLE
How to unmap action `s` 

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#179]
<a href="https://github.com/BjornMelgaard"><img src="https://avatars1.githubusercontent.com/u/7573215?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [BjornMelgaard](https://github.com/BjornMelgaard)**
_Saturday Dec 24, 2016 at 23:09 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1089_

----

Here I want to make `ss` and others keystrokes to call external plugin AceJump

```py
from Vintageous import plugins
from Vintageous.vi.cmd_defs import ViOperatorDef
from Vintageous.vi.utils import modes

class VintageousAceJump(ViOperatorDef):
    def __init__(self, *args, **kwargs):
        ViOperatorDef.__init__(self, *args, **kwargs)

        self.repeatable = False
        self.motion_required = False

@plugins.register('ss', (modes.NORMAL,))
class VistageousAceJumpChar(VintageousAceJump):

    def translate(self, state):
        return {
          'action': 'ace_jump_char',
          'action_args': {},
        }


@plugins.register('sw', (modes.NORMAL,))
class VintageousAceJumpWord(VintageousAceJump):

    def translate(self, state):
        return {
          'action': 'ace_jump_word',
          'action_args': {},
        }


@plugins.register('sl', (modes.NORMAL,))
class VintageousAceJumpLine(VintageousAceJump):

    def translate(self, state):
        return {
          'action': 'ace_jump_line',
          'action_args': {},
        }

```

But this code dont work, `s` call substitute and keystroke stumble. I tried to add `No Operation` but this dont help.

```py
@plugins.register('s', (modes.NORMAL, ))
class VistageousAceJumpChar(VintageousAceJump):

    def translate(self, state):
        return { }

```

The only way that I see is to unmap `s` entirely on `plugin_loaded`, how to do this without hacking `Vintageous.vi.keys.mappings`?

**Comment by gerardroche** [comment]
@BjornMelgaard You can try setting up mappings using your `vintageousrc` file in NeoVintageous. NeoVintageous is a fork of the discontinued Vintageous plugin. Here's how you might setup mappings for AceJump:

Edit your `vintageousrc` file (from the Command Palette: `NeoVintageous: Open My vintageousrc File`), and add:

```
let mapleader=,

" AceJump plugin
" https://packagecontrol.io/packages/AceJump
nnoremap <leader><leader>a :AceJumpAfter<CR>
nnoremap <leader><leader>c :AceJumpChar<CR>
nnoremap <leader><leader>d :AceJumpAddCursor<CR>
nnoremap <leader><leader>i :AceJumpWithinLine<CR>
nnoremap <leader><leader>l :AceJumpLine<CR>
nnoremap <leader><leader>s :AceJumpSelect<CR>
nnoremap <leader><leader>w :AceJumpWord<CR>
```

With those mappings you have mappings like `,,w` mapped to the `AceJumpWord` command (that's two commas followed by w).

Alternatively you can configure whatever mappings work for you.

You can read more about mappings in the help file see `:h neovintageous`.

**Comment by BjornMelgaard** [comment]
Tnx, @gerardroche, but I'm using neovim now
