### ISSUE TITLE
Semicolon after t/f/T/F doesn’t work

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#191]
<a href="https://github.com/kibin"><img src="https://avatars3.githubusercontent.com/u/1782569?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [kibin](https://github.com/kibin)**
_Monday Nov 16, 2015 at 12:53 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1035_

----

Comma, on the other hand, works fine.

**Comment by gerardroche** [comment]
<a href="https://github.com/kibin"><img src="https://avatars3.githubusercontent.com/u/1782569?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kibin](https://github.com/kibin)**
_Tuesday Nov 17, 2015 at 15:16 GMT_

----

Also search for semicolon doesn’t work (e.g. `t ;`/`f ;`)

**Comment by gerardroche** [comment]
<a href="https://github.com/Saevon"><img src="https://avatars3.githubusercontent.com/u/570036?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Saevon](https://github.com/Saevon)**
_Wednesday Aug 24, 2016 at 23:37 GMT_

----

Both of these cases seem to work for me. Can you check again, and see if its still reproducible? Perhaps theres a clash with one of your plugins?

**Comment by gerardroche** [comment]
@kibin @Saevon I'm unable to reproduce this in the latest version NeoVintageous. Looks like it has been fixed. Can you confirm? (NeoVintageous is a fork of the discontinued Vintageous plugin)

**Comment by Saevon** [comment]
Not sure about Neo Vintageous, I haven't updated yet, but I have no problems with this command in the original code.

**Comment by gerardroche** [comment]
@Saevon Thanks.
