### ISSUE TITLE
Option or documentation for not binding escape to _enter_normal_mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#202]
<a href="https://github.com/pbeshai"><img src="https://avatars0.githubusercontent.com/u/793847?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [pbeshai](https://github.com/pbeshai)**
_Wednesday Dec 02, 2015 at 18:39 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1049_

----

When using multiple cursors, it can be annoying that escape does not get rid of them, but instead changes to command mode with multiple cursors. 

The simplest way around this that I found was to put the following in my User keybindings:

``` json
{ "keys": ["escape"], "command": "single_selection", "context": [{"key": "vi_insert_mode_aware"}]},
```

This basically copies the command from default keybindings but uses the context as specified in the Default.sublime-keymap in Vintageous. 

Prior to figuring this out, one of my main annoyances with using vim emulation in Sublime was when it would switch to command mode when I didn't want to (typically by pressing escape). I figured I would share how I fixed this problem here as some form of documentation. It might be worth adding a configuration option to Vintageous that just does not bind escape in the first place.

**Comment by gerardroche** [comment]
@pbeshai If I'm understanding you correctly, you want a multiple selection to reduce to one selection on escape?

If this is indeed what you want then one issue with the mapping is that you cannot escape from a single selection, try this:

    {
        "keys": ["escape"],
        "command": "single_selection",
        "context": [
            {"key": "selection_empty", "operator": "equal", "operand": false, "match_all": true},
            {"key": "num_selections", "operator": "not_equal", "operand": 1},
            {"key": "vi_insert_mode_aware"}
        ]
    },

This mapping will only execute if you have 2 or more selections.


I'm used to the Esc key switching to normal mode in multiple selections, because sometimes that I want. Pressing Esc again will remove the multiple selections. 

Vim's multiple cursor plugin does it a little differently: Esc removes all the selections and you press `v` to enter normal mode in multiple selection mode. I'd like to rework multiple selections in NeoVintageous to be a bit more like Vim's plugins, there's an open issue for it: https://github.com/NeoVintageous/NeoVintageous/issues/251.










*Just in case you don't know what NeoVintageous is, it is a fork of the discontinued Vintageous plugin.*

**Comment by pbeshai** [comment]
Thanks for the follow-up. I ended up switching to using ctrl+c instead of escape for switching between vim modes in the end. 😅
