### ISSUE TITLE
Implement 'scrolloff' option

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#205]
<a href="https://github.com/jasjuang"><img src="https://avatars0.githubusercontent.com/u/11759200?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jasjuang](https://github.com/jasjuang)**
_Wednesday Jan 13, 2016 at 22:47 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1054_

----

In order to achieve scrolling down while keeping cursor in middle of screen without having to type zz everytime, in vim we can type

```
:set scrolloff=999
```

once, is it possible for vintageous to support this feature as well?

Thanks.

**Comment by gerardroche** [comment]
<a href="https://github.com/rozling"><img src="https://avatars1.githubusercontent.com/u/1826422?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rozling](https://github.com/rozling)**
_Friday Apr 08, 2016 at 21:57 GMT_

----

+1, this would be so useful!

**Comment by gerardroche** [comment]
Docs https://neovim.io/doc/user/scroll.html

**Comment by eproxus** [comment]
Sublime Text has the `scroll_past_end` setting, but it only takes a boolean and adds a length equal to the current height of the buffer.

**Comment by gerardroche** [comment]
Re also [Cursor surrounding lines feature Sublime request](https://github.com/SublimeTextIssues/Core/issues/2983).

**Comment by gerardroche** [comment]
Closing and moving the issue to the [known issues](https://github.com/NeoVintageous/NeoVintageous/issues/404) section of the roadmap.

**Comment by gerardroche** [comment]
Fixed in 4075: The "scroll_context_lines" controls this behaviour.
