### ISSUE TITLE
Jumping to mark in visual mode does not work

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#209]
<a href="https://github.com/asfaltboy"><img src="https://avatars3.githubusercontent.com/u/321520?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [asfaltboy](https://github.com/asfaltboy)**
_Friday Feb 19, 2016 at 08:40 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1060_

----

I see that using marks (in both normal/visual modes) was [implemented around 2013](https://github.com/guillermooo/Vintageous/issues/157#issuecomment-15344643); however I just now getting used to marks, and using marks in Visual Mode does not seem to work for me.

I'm on latest Sublime Text 3 build 3103, and Vintageous is installed from Package Control.

**Comment by gerardroche** [comment]
@asfaltboy This has been fixed in NeoVintageous 1.6.0 (NeoVintageous is a fork of the discontinued Vintageous plugin).

**Comment by asfaltboy** [comment]
Thanks @gerardroche , can't wait to try it again.
