### ISSUE TITLE
Feature request - Ctrl + [ as escape.

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#231]
<a href="https://github.com/zkanda"><img src="https://avatars1.githubusercontent.com/u/5354184?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [zkanda](https://github.com/zkanda)**
_Sunday Oct 11, 2015 at 11:30 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/1005_

----

As what the title says. This is also default in Vim.

**Comment by gerardroche** [comment]
<a href="https://github.com/AlexArendsen"><img src="https://avatars2.githubusercontent.com/u/9682835?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AlexArendsen](https://github.com/AlexArendsen)**
_Sunday Oct 18, 2015 at 15:27 GMT_

----

Seconded-- this will be essential for many vim users.

**Comment by GameKyuubi** [comment]
Yes.  In Vintageous there was a bug where even if you set Ctrl + [ to exit_insert_mode it wouldn't do it properly.

**Comment by gerardroche** [comment]
Duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/249

**Comment by gerardroche** [comment]
@zkanda @AlexArendsen This was fixed in NeoVintageous 1.1.0. get the latest version 1.4.4 with more bug fixes and features. NeoVintageous is a fork of the discontinued Vintageous plugin.
