### ISSUE TITLE
Simply search & replace not working for me (probably something simple) ...

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#238]
<a href="https://github.com/nmvega"><img src="https://avatars0.githubusercontent.com/u/4001382?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [nmvega](https://github.com/nmvega)**
_Tuesday Aug 11, 2015 at 21:14 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/991_

----

Hello Guillermo:

First, thank you for the plugin. =:). It's appreciated.

I can't this simple substitution to work on Sublime Text 3.
It basically does nothing when I press enter:

:1,$s/cmd/shell_cmd/g

I think it's probably something that I don't have enabled.

Any ideas?

Thank you!

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Oct 10, 2015 at 08:11 GMT_

----

I don't think `$`is implemented here. Try `%` instead. Maybe that's not correct Vim, but it seems to work now.

**Comment by nmvega** [comment]
@gerardroche thank you!
