### ISSUE TITLE
"Dot command" doesn't grab full text input from insert mode for repeating later

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#239]
<a href="https://github.com/prurph"><img src="https://avatars3.githubusercontent.com/u/6109531?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [prurph](https://github.com/prurph)**
_Saturday Aug 22, 2015 at 14:17 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/993_

----

In Vim after doing something like `cw` > "foo" the `.` command will afterwards execute both the `cw` and the text, so you can replace multiple words with "foo" just by repeating the command with `.`

In Vintageous however only the `cw` is captured, so the dot command will execute it, deleting the word, but will immediately put you back into normal mode; it does not execute the actual character insertion.

The default behavior in Vim is more or less that `.` repeats whatever was done inside the last insert mode operations. Not being able to do this in Vintageous reduces efficiency in a lot of common spots.

The Vintageous behavior is "correct" for single character operations like `r` but not for things like `cw`, `s`, `cb`, 'caw', etc.

**Comment by gerardroche** [comment]
@prurph From what I can tell, this has since been fixed (fyi NeoVintageous is a fork of Vintageous).

**Comment by burgreen** [comment]
The dot command repeats only once. Can it be made to repeat multiple times?
