### ISSUE TITLE
Leaving Insert mode still shows as being in Insert mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#241]
<a href="https://github.com/skube"><img src="https://avatars0.githubusercontent.com/u/146396?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [skube](https://github.com/skube)**
_Thursday Jul 23, 2015 at 15:22 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/988_

----

I'm not sure if this is by design but when I exit Insert mode, the status bar still shows `--INSERT--`. However once I start moving around the `--INSERT--` indicator disappears. This is not the behaviour when simply using the Vintage package.

Using Sublime 3083 on Win7

**Comment by jerryturcios08** [comment]
I am also having this issue. I am not sure if it is part of the package.

**Comment by gerardroche** [comment]
@skube Thanks. This has been fixed in NeoVintageous 1.4.4 (NeoVintageous is a fork of the discontinued Vintageous plugin).
