### ISSUE TITLE
Make multiple cursors work as close as possible to terryma/vim-multiple-cursors

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#251]
https://github.com/terryma/vim-multiple-cursors is pretty much what vim users for multiple cursors, so I think it makes sense for NeoVintageous multiple cursors feature to work the same way.

Re: https://github.com/NeoVintageous/NeoVintageous/pull/250

**Comment by haolly** [comment]
I found <c-n> do not work on my mac with v1.14.2

**Comment by gerardroche** [comment]
hmm. You'll need ctrl keys enabled, they're disabled by default. Do you have ctrl keys enabled? Does `gh` work? 


Configure settings via **Menu > Preferences > Settings** or by the Command
Palette. To use the command palette:

1. Press `Ctrl+Shift+P`
2. Select the "Preferences: Settings" command
3. Press `Enter`

For example to enable the ctrl keys:

```
    {
        "vintageous_use_ctrl_keys": true
    }
```

fyi we're working a way to allow more granular control of keys like the ctrl keys https://github.com/NeoVintageous/NeoVintageous/issues/470

**Comment by haolly** [comment]
Thanks, after enable ctrl key, it works
