### ISSUE TITLE
the 'black hole register' doesn't work.

### ISSUE THREAD

**Issue by xiaoq1024** [NeoVintageous/NeoVintageous#260]
I want to replace second line by first line. yy in first line, moving to second line then type "\_dd and p, but the paste text is coming from dd(second line) instead of yy(first line). Does it mean "_(black hold register) not work? the same as "_dw. I am working in Windows7

**Comment by gerardroche** [comment]
It works a few cases like `"_yy`, but currently not others, for example, `"_diw".

One workaround is to use the yank register `"0`. I don't know if that would suit your needs? e.g. `yy` which puts the copied text into the `"0` register, then you can delete whaetever, and then paste from the yank register e.g. `"0P`. 

The vimcast [Meet the yank register](http://vimcasts.org/episodes/meet-the-yank-register/) shows a good example. The example he shows doesn't yet work in NeoVintageous.
