### ISSUE TITLE
Optional :quit (^W q) and :close (^W c) setting to disable exit sublime?

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#270]
Should we add an optional setting for `:quit` (`ctrl+w q`), `:close` (`ctrl+w c`), and related commands, to *not* exit sublime even if the it's the last view?

The behaviour or vim is:

* `:quit` exits vim if only one window left
* `:close` (~~not implemented yet~~ https://github.com/NeoVintageous/NeoVintageous/issues/269, but the `ctrl+w c` ctrl key mapping is implement) closes the window unless it's the last one 

Re: https://github.com/NeoVintageous/NeoVintageous/issues/192

**Comment by gerardroche** [comment]
The default behaviour of Vim is:

> When quitting the last window (not counting a help window), exit Vim.

So unless others want this feature I'm going to close it. `:close` and `ctrl+w c` have been implemented and can be used to close the view without existing ST. `:close!` will close the last one without existing too.

If others still want an option to disable the close feature in `CTRL+w q`, then this can be reopened.

**Comment by sepisoad** [comment]
for me it is extremely annoying to close the subl window when the last buffer is closed, specially when i toggle off the tabs and do not see the number of opened files. I guess it would be nice if we could control the behaviour of :q or :x for this specific case

**Comment by gerardroche** [comment]
I've added the setting `vintageous_exit_when_quiting_last_window` in the lastest version 1.24.1. Set it to false to disable the exit on closing last view.

See https://github.com/NeoVintageous/NeoVintageous/issues/782

You may also like :only (ctrl+w o): close all except the current one.
