### ISSUE TITLE
Vintagoues not working with non-latin keyboard layout

### ISSUE THREAD

**Issue by karamfil** [NeoVintageous/NeoVintageous#274]
Hi Guys,

Awesome work!

Apologies if this is a duplicate I have search but could not find an issue about this.

I am pretty annoyed that keys are not working when I am using the Cyrillic keyboard layout - which I regularly do.

Do you know if there is a way to use key codes instead of characters to do the matching.
Could you point me in the correct directions and may be I can try to help with a pull request?

**Comment by gerardroche** [comment]
Currently I think the only way to solve this would be configure specific mappings for every locale. I'm not sure it's a practical solution.

For example, if `и` should enter insert mode then adding a keymap in [`Default.sublime-keymap`](https://github.com/NeoVintageous/NeoVintageous/blob/master/Default.sublime-keymap) for  `и` to "translate" to the "i" keymap".

```
    {"keys": ["i"], "command": "press_key", "args": {"key": "i"}, "context": [{"key": "vi_command_mode_aware"}]},
    {"keys": ["и"], "command": "press_key", "args": {"key": "i"}, "context": [{"key": "vi_command_mode_aware"}]},
```

This is common issue Sublime Text.

Atom blog article about similar issues: http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html

**Comment by karamfil** [comment]
I see, well this should be ok I guess :)

Also "i" should actually map to "с" as I am using Dvorak Bulgarian keyboard layout and I want the commands to be the Latin ones even though I am currently on Cyrillic  ;)

Thanks. I will post may config after I make it so that other poeple may use it if interested :)

**Comment by webtotma** [comment]
Can be implement this -https://github.com/lyokha/vim-xkbswitch

**Comment by karamfil** [comment]
Well I actually mapped only a few commands I am frequently using and I map new when I feel like it is missing. One advice you have to map only letters, because special chars will be remapped for US locale too.

**Comment by eugenesvk** [comment]
You could check this PR that adds a generator for non-qwerty (including non-latin) keymaps to NV (by copy&pasting all of the default keybinds) and also unlike [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) doesn't mess with OS layouts

https://github.com/NeoVintageous/NeoVintageous/pull/869
