### ISSUE TITLE
Insert Mode by default when changing open files

### ISSUE THREAD

**Issue by GhostValk** [NeoVintageous/NeoVintageous#277]
It's possible to start by default in Insert Mode, or to remember the last mode used in a file when you switch to another one and back?

I know all the philosophy behind vim-like editors and bla bla, but in my case, for the specific coding work i do, my default work is 99% in insert mode, even more when just opening a file.

**Comment by GhostValk** [comment]
Also, i would like to ask if it's possible to define custom ex commands in this plugin?

**Comment by gerardroche** [comment]
There is an option `vintageous_reset_mode_when_switching_tabs` that might fullfil you needs.

`Preferences > Settings`

```json
{
    "vintageous_reset_mode_when_switching_tabs": false
}
```

I would like tackle this issue and make the behaviour closer to how vim works and also add options like staying one mode or another. The way vim currently works:

* if in any mode other than insert when switching to another view with the mouse it resets to normal mode
* if in insert mode and switching to another view vim stays in insert mode

Implementing the above would solve a few grievances with changing modes on switching view, but I'd also like to implement the option of specifying a default mode.

**Comment by duranivan** [comment]
The option `"vintageous_reset_mode_when_switching_tabs": false` works for me. Just what I was looking for. Thanks!

**Comment by varmanishant** [comment]
I would like to **_start_** NeoVintageous in Insert Mode. Is there a  setting for that?

**Comment by gerardroche** [comment]
It's a big change. It relates to other recent issues too: #357.

There's an explanation here about how I'd like to change the way the mode state works (the last paragraph): 

https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346

In terms of eta: I don't know. I need to do more internal refactoring, redesign, and testing, to make sure things don't break. I'm getting closer to it though.

**Comment by gerardroche** [comment]
I've added a **beta** feature option to enable insert mode by default. It's currently available in the master branch:


## `'vintageous_default_mode'` string (default "")

Default mode to use when activating or switching views.
Valid values are: "insert"

mode   | description
------ | -----------
insert | Enter insert mode when opening or switching views or when the window receives focus and is not in visual mode i.e. visual mode selections are retained when the window loses focus.

Configure settings via **Menu > Preferences > Settings** or by the Command
Palette. To use the command palette:

1. Press `Ctrl+Shift+P`
2. Select the "Preferences: Settings" command
3. Press `Enter`

For example to enable the ctrl keys: >

```
    {
        "vintageous_default_mode": "insert"
    }
```

I need your feedback and suggestions for tweaking, enhancements, and bugs.

Essentially, it works like this:

* Enter insert mode when opening a view
* Enter insert mode when switching views
* Enter insert mode when focus is given to Sublime and current mode is normal or unknown

The reasoning for the above is avoid visual selections from being cleared when Sublime loses focus e.g. switching to another application. Normally when switching views or opening new views any visual selections in other views are cleared. 

This is very close to how Vim behaves. But let me know what you think and your suggestions. You can probably tell from the setting name that we could have different default modes with alternate behaviours to accommodate as many default modes as possible.

**Comment by eugenesvk** [comment]
Maybe I'm misunderstanding how these settings are supposed to work together, but I'd like to have the following behavior:
  - whenever a new tab is opened for the first time, its mode should be `normal` (or whatever else is in the settings)
  - however, after I change to to whatever other mode, this mode should remain until I switch it to something else
  - ↑ this is especially great when I'm switching apps: if I want to switch to a browser from an insert mode to copy&paste some text, I should not switch back to an editor that switched modes on me

I've tried setting like below, but the first setting behaves like the second, so turning it `off` doesn't help, if I enter `insert` mode and switch apps, the mode is reset to normal (having `vintageous_default_mode` to `""`, which I hoped would be ~`none` didn't help)
```json
  "vintageous_default_mode"                  	: "normal"	,//|""| default mode when activating or switching views (visual mode selections are retained when the window loses focus)
  "vintageous_reset_mode_when_switching_tabs"	: "off"   	,//|on|	Reset to normal mode when a view is activated
```
