### ISSUE TITLE
"%" does not work in shell commands

### ISSUE THREAD

**Issue by girtsf** [NeoVintageous/NeoVintageous#284]
In vim `%` is replaced with name of current file. E.g., `:!echo %` runs `echo` with current file as argument. NeoVintageous seems to pass `%` through as is.

**Comment by gerardroche** [comment]
Will be nice to be able to things like `:!git add %` and I'm adding a setting `vintageous_shell_silent` to prevent the output panel from appearing which will then allows silent mappings:

```
nnoremap <leader>ga :!git add %<CR>
```
