### ISSUE TITLE
Visual mode block insert and append partially working

### ISSUE THREAD

**Issue by princemaple** [NeoVintageous/NeoVintageous#292]
In visual mode, `I` and `A` should enter insert mode while moving the cursor to the beginning / end of the selection respectively. Currently it works with a subtle caveat.

~~When the cursor is at the end of the selection, `A` works as spected.
When the cursor is at the beginning of the selection, `I` works as expected.
In other cases (cursor at the end and press 'I' or cursor at the beginning and press 'A'), we enter insert mode but the cursor would end up at the beginning of the line.~~

~https://user-images.githubusercontent.com/1329716/32533197-6bad0324-c4a3-11e7-83e0-8793d4e505ae.gif~

**Comment by princemaple** [comment]
Currently, can be worked around by using `o` to move the cursor first before entering insert mode.

**Comment by gerardroche** [comment]
Sorry I'm finding hard to understand the behaviour you expect. The gif is too fast.

*Where cursor starts at column |.*

# First test (end position)

Both these work as expected.

```
|aaaa bbbb cccc
```

Press `wvt<Space>` (this selects the `bbbb` with the cursor on the last b):

Pressing `I`:

```
|aaaa bbbb cccc
```

Pressing `A`:

```
aaaa bbbb| cccc
```

# Second test (begin position)

```
|aaaa bbbb cccc
```

Press `wvt<Space>o` (this selects the `bbbb` with the cursor on the *first* b):

Pressing `I`:

## Expected

```
|aaaa bbbb cccc
```

## Actual

```
aaaa |bbbb cccc
```

Pressing `A`:

## Expected

```
aaaa b|bbb cccc
```

# Actual

```
|aaaa bbbb cccc
```

**Comment by princemaple** [comment]
Yeah my reporting was problematic. I thought when you highlighted a word and press `I` it would move the cursor to the beginning of the selection and enter insert mode. The truth is it would move the cursor to the beginning of the line and enter insert mode. The is a small difference between real vim implementations and Sublime Vintage mode I'm used to.

**Comment by gerardroche** [comment]
I half expected the same as you. It's seems a little inconsistent.
