### ISSUE TITLE
Sublime doesn't load

### ISSUE THREAD

**Issue by slifin** [NeoVintageous/NeoVintageous#297]
I get this issue first thing this morning, I don't think I made any changes to neovintageous yesterday

<img width="224" alt="screen shot 2017-12-21 at 09 22 48" src="https://user-images.githubusercontent.com/198857/34249146-8c592a72-e630-11e7-8178-bbee3a2126de.png">

**Comment by slifin** [comment]
Looks like closing the dialog and swapping the tabs works, the console said something about active view not found, seems "fixed" now that sublime is focusing an active file

**Comment by gerardroche** [comment]
I'm going to reopen this because testing it just now I've found that if the active view is for example an image then it triggers the error. It night also be triggered after an update. I'll debug it some and fix whatever I find. Thanks.
