### ISSUE TITLE
Relative Numbers

### ISSUE THREAD

**Issue by qazip** [NeoVintageous/NeoVintageous#3]
Hey,

I'm not sure if this is even possible yet, but it would be really nice to have support for true relative numbers.

**Comment by trishume** [comment]
I don't think this is possible with the limitations of the Sublime Plugin API. There's no API for manipulating line numbers.

It may be possible however to add icons to the gutter which are numbers, which would work for a limited range (1-9 maybe?) but they would show up alongside the normal line numbers. I also forget how well Sublime deals with multiple gutter icons, they might screw with GitGutter.

**Comment by gerardroche** [comment]
Relative line numbers is core limitation. It's an [often requested](https://forum.sublimetext.com/search?q=relative%20line%20numbers) feature. 

Sublime doesn't support multiple gutters so that's not an option, besides it would still only be a work around.

**Comment by gerardroche** [comment]
https://github.com/NeoVintageous/NeoVintageous/issues/13
