### ISSUE TITLE
vmap < <gv does not work

### ISSUE THREAD

**Issue by haolly** [NeoVintageous/NeoVintageous#302]
### Description
I use the setting in .vintageousrc file:
```
"" Vmap for maintain Visual Mode after shifting > and <
vmap < <gv
vmap > >gv
```

### Steps to Reproduce
Issue command:
V>><<

### Expected behaviour
the line is still selected, and shift to  left
### Actual behaviour
lost selection and could not shift to left
### Versions
1.4.4
You can get Sublime Text version information from copy and pasting the output of the console `Menu > View > Show Console`.

Also, please include the OS and what version of the OS you're running.

> DPI scale: 1
startup, version: 3143 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/liuhao1/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/liuhao1/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/liuhao1/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Six", "Vintage", "Vintageous"]
pre session restore time: 0.135242
startup time: 0.243242
first paint time: 0.246242
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin Alignment.Alignment
reloading plugin BracketGuard.BracketGuard
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin Find++.DirectoryPanel
reloading plugin Find++.FindPlusPlus
reloading plugin LSP.boot
reloading plugin NeoVintageous.plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SyncedSideBar.SyncedSideBar
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin Search in Project.search_in_project
reloading plugin TodoReview.TodoReview
plugins loaded
LSP: global clients: 
Detected UTF-8-SIG vs UTF-8 with BOM with 100% confidence
Detected UTF-8-SIG vs UTF-8 with BOM with 100% confidence
Quick panel unavailable
Package Control: Skipping automatic upgrade, last run at 2018-01-24 14:17:03, next run at 2018-01-24 15:17:03 or after
Unable to fetch update url contents
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "lib.commands in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 241, in run
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 529, in to_bare_command_name
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 512, in iter_tokenize
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 506, in tokenize_one
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 482, in long_key_name
ValueError: wrong key lt
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 795, in run_
    return self.run(**args)
  File "lib.commands in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 241, in run
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 529, in to_bare_command_name
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 512, in iter_tokenize
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 506, in tokenize_one
  File "lib.vi.keys in C:\Users\liuhao1\AppData\Roaming\Sublime Text 3\Installed Packages\NeoVintageous.sublime-package", line 482, in long_key_name
ValueError: wrong key lt
Unable to open /C/Users/liuhao1/AppData/Roaming/Sublime Text 3/Packages/NeoVintageous/CHANGELOG.md

**Comment by gerardroche** [comment]
It will work using `<lt>` for `<`: 

```
"" Vmap for maintain Visual Mode after shifting > and <
vmap <lt> <lt>gv
vmap > >gv
```

It's still a bug though, because `<` in keymaps should be converted to `<lt>`.

**Comment by gerardroche** [comment]
From the vimdocs:

>  3.  A real '<' is represented with "\<" or "<lt>".  When there is no  confusion possible, a '<' can be used directly. https://vimhelp.appspot.com/intro.txt.html#%3C%3E

Currently only `<lt>` for `<` will work.

**Comment by haolly** [comment]
Thanks,It works

**Comment by haolly** [comment]
It's broken in the latest version

**Comment by gerardroche** [comment]
What version is it broken in, I can't reproduce it?

**Comment by haolly** [comment]
v 1.5.2

**Comment by gerardroche** [comment]
Try:

```
vnoremap <lt> <lt>gv
vnoremap > >gv
```

The recursive mappings we're removed: See http://blog.gerardroche.com/2018/02/21/neovintageous-1.5.0-released/

**Comment by haolly** [comment]
Works again !

**Comment by haolly** [comment]
v 1.6.3 
use Vj>>
the line under visual line will also be indented
