### ISSUE TITLE
How can I unmap keys?

### ISSUE THREAD

**Issue by michaelHL** [NeoVintageous/NeoVintageous#303]
Great plugin for us vimers !

### Description

I used to `unmap` keys by extracting the plugin via [PackageResourceViewer](https://packagecontrol.io/packages/PackageResourceViewer), commenting the lines  in `Default.sublime-keymap` including the shortcut key combinations which I prefer the default behavior in sublime. But it's inconvenient on every update because the plulgin folder would be updated and all my settings would be overwritten.

For example I want <kbd>ctrl</kbd><kbd>shift</kbd><kbd>t</kbd> to perform "recover last closed tab". I try to `unmap` keys in `.vintageousrc` file:
```
unmap <C-S-t>
```
Of course it doesn't work 😿 

So is there an elegant way to unmap keys?

### Versions

NeoVintageous: 1.5.0
Sublime Text: 3126

**Comment by gerardroche** [comment]
`unmap` only works for mappings that you created in your `.vintageousrc` file (i.e. NeoVintageous's version of the `.vimrc` file). 

There are two ways to "remap" `<C-T>` to recover last closed tab.

When we look at Sublime Text original keymap it is something likes: 

```
    { "keys": ["ctrl+shift+t"], "command": "reopen_last_file" },
```

We can go ahead add that keymap to our user keymaps: `Menu > Preferences > Key Bindings`.

The other alternaitve to create a mapping in out `.vintageousrc` file.

Open your `vintageousrc` file via the Command Palette command: `NeoVintageous: Open My vintageousrc File`, and add:

```
nnoremap <C-T> :ReopenLastFile<CR>
```

Then reload it via the Command Palette command: `NeoVintageous: Reload My vintageousrc File`.

You can read more about the `vintageousrc` file via the ex mode command `:h vintageousrc`.

**Comment by michaelHL** [comment]
@gerardroche Thx for the solution!
