### ISSUE TITLE
surround command with multiple selection leaves cursors in the wrong place

### ISSUE THREAD

**Issue by iuliantatarascu** [NeoVintageous/NeoVintageous#305]
### Description

when using the surround command with multiple selection the cursors are left behind with each replacement made

### `ysiw'`

```
cat eats fi|sh
cat eats fi|sh
cat eats fi|sh
cat eats fi|sh
```

### Expected behaviour

```
cat eats '|fish'
cat eats '|fish'
cat eats '|fish'
cat eats '|fish'
```

### Actual behaviour

```
cat eats '|fish'
cat eats| 'fish'
cat ea|ts 'fish'
cat |eats 'fish'
```

### `cs'(`

```
cat eats 'fi|sh'
cat eats 'fi|sh'
cat eats 'fi|sh'
cat eats 'fi|sh'
```

### Expected behaviour

```
cat eats ( fish )
cat eats ( fish )
cat eats ( fish )
cat eats ( fish )
```

### Actual behaviour

```
cat eats (| fish )
cat eats '|fish(|
cat eats  )fish(|
cat eats  )fish'
```

### `ds'`

```
cat eats 'fi|sh'
cat eats 'fi|sh'
cat eats 'fi|sh'
cat eats 'fi|sh'
```

### Expected behaviour

```
cat eats f|ish
cat eats f|ish
cat eats f|ish
cat eats f|ish
```

### Actual behaviour

```
cat eats f|ish
cat eats f|ish
cat eats 'fish'|
cat eats 'fish'|
```

### Versions

sublime/OS

```
startup, version: 3143 linux x64 channel: stable
```

NeoVintageous

```
1.5.0 - 2018-02-06
```

### Additional Information

potential fix for `ys`:

https://github.com/iuliantatarascu/NeoVintageous/commit/54e364c74674b7a731eef2529818a437f2187d2b

**Comment by gerardroche** [comment]
Thanks. Good catch. I'm suprised I never hit these bugs. I reworked the regions tranformer to make it process in sync with the mutations.
