### ISSUE TITLE
triple-clicking doesnt select a line

### ISSUE THREAD

**Issue by drewcassidy** [NeoVintageous/NeoVintageous#306]
### Description
Triple clicking in neovintageous no longer selects the whole line

### Steps to Reproduce
triple-click on a line of text

### Expected behaviour
the line is selected

### Actual behaviour
the cursor moves to the end of the line

### Versions
 build 3143, macOS 10.13.3

**Comment by gerardroche** [comment]
Note: reproduce bug, and test against ealier versions of Vintageous. This is not a regression.
