### ISSUE TITLE
gj and gk do not work in visual line mode

### ISSUE THREAD

**Issue by DrBones** [NeoVintageous/NeoVintageous#314]
### Description
The commands gj and gk are not working as expected in - VISUAL LINE -
### Steps to Reproduce
Select line of text with shift-v and press gj or gk
### Expected behaviour
One of two:

Vim-like: A cursor moves by screen line and selects the next file line as soon as it enters it.
NeoVintageous file line-like: The whole line is selected and the next line is selected identically to using g and k by itself.
### Actual behaviour
Nothing happens and only one line stays selected
### Versions

Sublime Text 3 Bild 3143
NeoVintageous 1.5.2
Windows 10 1709

Clean portable "install" and only Neovintageous.
### Additional Information

Weirdly, I am under the impression that this used to work a while ago.

Alternatively, is there a way to map  j -> gj and k ->gk only in normal and visual mode not in visual line mode?

Thanks!

**Comment by DrBones** [comment]
For what it's worth, adding a special block in the file cmds_vi_motions.py to `_vi_gj` and `_vi_gk` to execute the `_vi_j` and `_vi_k` behaviour in the case of `VISUAL_LINE` fixed it for me.

I.e like this, seems a little hacky tough...
 ```python
....
elif mode == VISUAL:
    for i in range(count):
        self.view.run_command('move', {'by': 'lines', 'forward': True, 'extend': True})
elif mode == VISUAL_LINE:
    self.view.run_command('_vi_j', {'mode': mode, 'count': count})
elif mode == INTERNAL_NORMAL:
...
```

**Comment by gerardroche** [comment]
> Vim-like: A cursor moves by screen line and selects the next file line as soon as it enters it.
NeoVintageous file line-like: The whole line is selected and the next line is selected identically to using g and k by itself.

On linux in Vim it works line-like i.e. "The whole line is selected and the next line is selected identically to using g and k by itself." There is probably a Vim option that changes this behaviour.  

> Alternatively, is there a way to map j -> gj and k ->gk only in normal and visual mode not in visual line mode?

Not that I know of. I don't think this can done in Vim either.

**Comment by DrBones** [comment]
Thank you for your quick response!

Interesting, my default Vim on a Debian (started with -u NONE) behaves differently then. A bunch of extra patches are included though.
![vimvisualline](https://user-images.githubusercontent.com/212259/37368927-ed1db8ec-2707-11e8-9c4d-7cc4e8b6d73f.gif)

I thought as much that I could not map VISUAL-LINE individually, I will live with the hack then :).
Just out of curiosity, is the behaviour that gj does nothing in visual-line mode working as intended or do I have a strange bug somehow?

**Comment by gerardroche** [comment]
No, that's a bug, it doesn't work for me either.
