### ISSUE TITLE
Support for non-QWERTY based keyboard layouts such as Dvorak

### ISSUE THREAD

**Issue by ArniDagur** [NeoVintageous/NeoVintageous#316]
I am a user of an alternative keyboard layout called QGMLWY that is interested in this project for personal use, and a means to learn the basics of vim. I've got to say, in looks *great*. After installing the project to Sublime, however, I realised that the vim keybindings, based on the traditional QWERTY keyboard layout, do not translate well onto another keyboard layout.

My issue is:
1. Is there a way already to remap the traditional vim bindings to other keys? If not, I suggest implementing such a feature. It would not only benefit users using alternative keyboard layouts, but also QWERTY users with nontraditional binding preferences.
2. A suggestion to implement an optional feature to base keybindings off of the OS-level keyboard APIs, similar to what is talked about in this post from the Atom blog: http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html

**Comment by gerardroche** [comment]
Can give me some reproducible examples of the issues, I'm having a hard time trying to understand the issues?

**Comment by gerardroche** [comment]
To enable some debug info run this in the console `Menu > View > Show Console`: `sublime.log_input(True); sublime.log_commands(True)`.

**Comment by ArniDagur** [comment]
First, a question:

1. Is there a way already to remap the traditional vim bindings to other keys? If not, I suggest implementing such a feature. It would not only benefit users using alternative keyboard layouts, but also QWERTY users with nontraditional binding preferences.

Then:

2. A suggestion to implement an optional feature to base keybindings off of the OS-level keyboard APIs, similar to what is talked about in this post from the Atom blog: http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html

That's all; I'm not having any bugs. Sorry if I didn't make my issue clear.

**Comment by gerardroche** [comment]
> Is there a way already to remap the traditional vim bindings to other keys? If not, I suggest implementing such a feature. It would not only benefit users using alternative keyboard layouts, but also QWERTY users with nontraditional binding preferences.

You can create mappings using the `vintageousrc` file (similar to the `vimrc` file). Lookup the help file via  `:h vintageousrc`. Also, additional info here: [1.5.0 release](http://blog.gerardroche.com/2018/02/21/neovintageous-1.5.0-released/). Is this what you're looking for?

> A suggestion to implement an optional feature to base keybindings off of the OS-level keyboard APIs, similar to what is talked about in this post from the Atom blog: http://blog.atom.io/2016/10/17/the-wonderful-world-of-keyboards.html

I don't really understand what this feature would be or do. Maybe you can show me some examples of what the feature would do and what it solves?

**Comment by gerardroche** [comment]
@ArniDagur Did creating custom mappings solve your issue? Mappings were expanded on in 1.6.0, see https://blog.gerardroche.com/2018/05/21/neovintageous-1.6.0/.

**Comment by sourcevault** [comment]
Hi, 

I use a  custom keyboard :


<img width="512" alt="key10" src="https://user-images.githubusercontent.com/20347647/228232155-f8033f67-cc85-473d-bb9e-56bd8ce8b209.png">

as you can see I would like to remap the functionality of the `HJKL` keys to the arrow keys.


specifically, taken for sublime-text vintage docs :

```json
  { "keys": ["right"], "command": "set_motion", "args": {
    "motion": "vi_move_by_characters_in_line",
    "motion_args": {"forward": true, "extend": true, "visual": false }},
    "context": [{"key": "setting.command_mode"}]
  },

  { "keys": ["left"], "command": "set_motion", "args": {
    "motion": "vi_move_by_characters_in_line",
    "motion_args": {"forward": false, "extend": true }},
    "context": [{"key": "setting.command_mode"}]
  },

  { "keys": ["down"], "command": "set_motion", "args": {
    "motion": "move",
    "motion_args": {"by": "lines", "forward": true, "extend": true },
    "linewise": true },
    "context": [{"key": "setting.command_mode"}]
  },

  { "keys": ["up"], "command": "set_motion", "args": {
    "motion": "move",
    "motion_args": {"by": "lines", "forward": false, "extend": true },
    "linewise": true },
    "context": [{"key": "setting.command_mode"}]
  },
```

where do I put these updated code in the `.neovintageousrc` file ?
 
 Thank you making `NeoVintageous` 😃.

**Comment by sourcevault** [comment]
There is another potential issue, it has to do with the programmer's Dvorak:

![KB_Programmer_Dvorak](https://user-images.githubusercontent.com/20347647/228290938-3916e0bc-8baa-4821-82ca-e1e098d90249.jpg)

It switches numbers with it's symbols, so to type `1` you have to use `SHIFT+!`.

The issue here is that `vim` found a really cool use of the numbers - for selection of lines, ie - ,`v1j`,`v2j`,.....

is there a way to flip the numbers back to qwerty when using command mode ?

Thanks !

**Comment by gerardroche** [comment]
@ArniDagur I've created an experimental NeoVintageous plugin that provides dvorak support. See https://github.com/gerardroche/NeoVintageousDvorak. It's not available in Package Control yet and you will need to copy the mappings to your neovintagousrc file for the moment. Later I hope to add it to Package Control and have it loading before the user neovintageousrc file via an option in NeoVintageous. Your feedback on it would be welcomed.
