### ISSUE TITLE
how to let [[ and ]] behave just like vim

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#32]
<a href="https://github.com/ShengYun"><img src="https://avatars0.githubusercontent.com/u/1317203?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ShengYun](https://github.com/ShengYun)**
_Thursday Feb 13, 2014 at 08:57 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/476_

----

In vim I can use `[[` and `]]` to jump through paragraphs, and also jump through functions in C or C++, is it possible to do that in vintageous?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Friday Feb 14, 2014 at 07:09 GMT_

----

Not implemented. I just had a quick look and `]` seems to be a huge namespace of keys. They seem to mainly be useful for C and C++ and I don't use C or C++ myself, so I'm afraid my motivation to implement this is rather low.

**Comment by gerardroche** [comment]
<a href="https://github.com/ShengYun"><img src="https://avatars0.githubusercontent.com/u/1317203?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ShengYun](https://github.com/ShengYun)**
_Friday Feb 14, 2014 at 07:20 GMT_

----

Got it, thank you for the quick response:)

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Friday Feb 14, 2014 at 07:44 GMT_

----

If you can point to specific commands that might be general-purpose, I'll take a look at it, but please open a different issue for each separate command.

**Comment by gerardroche** [comment]
As far as I can see this has been implemented. @ShengYun can you confirm this has been implemented?

**Comment by ShengYun** [comment]
Hi Gerard,

I just checked it on v4.0.6, when I hit `[[` the cursor blinked but it
remains at the same place.

- Yun

**Comment by ShengYun** [comment]
This issue was opened years ago, why is github saying `Opened 8 days ago`? Also I got an email notification from a comment from @gerardroche saying `[[` is already implemented, can I try it out. But I can't find it on this issue...

**Comment by gerardroche** [comment]
I'm sorry, I should not have pinged you. Vintageous has been discontinued. NeoVintageous (this project) is a fork and all the issues have been ported here. neoVintageous will be available on the PC channel shortly.

My apologies for  unnecessarily pinging you.

**Comment by ShengYun** [comment]
No worries:)

- Yun

**Comment by gerardroche** [comment]
Moved to the roadmap:

https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md
