### ISSUE TITLE
Implement yankstack / yankring plugin

### ISSUE THREAD

**Issue by tsiper** [NeoVintageous/NeoVintageous#337]
With yankring/stack you can quickly cycle your register history when pasting with ctrl+n / ctrl+p.

For me this is a great VIM feature, and I would really appreciate if you can implement this plugin behavior in NeoVintageous.

Thanks!

**Comment by gerardroche** [comment]
I assume you're talking about https://github.com/vim-scripts/YankRing.vim.

**Comment by gerardroche** [comment]
You could probably setup custom mappings and use that plugin if it works. See `:h vintageousrc` on creating mappings.

**Comment by nimafazeli** [comment]
I would also appreciate such functionality. 

Sublime has a function called `paste_from_history` that does a similar thing.
Also there is a plugin called [Clipboard Manager](https://packagecontrol.io/packages/Clipboard%20Manager) that does the same.

Anyways I tried to add them through keybindings and macros but did no succeed. 
I am still not very clear on how to map normal sublime functionalities to Neovintageous and create keybindings. Very often keybindings need several arguments and a proper context and I do not know how to make neovintageous understand those. 
Any hint on that will also be great.

Thanks

**Comment by eduardoarandah** [comment]
To map sublime functionality, just **PascalCaseTheCommand** 

Use this to use native sublime `paste_from_history` with your leader key and p

```
" Clipboard History
nnoremap <leader>p :PasteFromHistory<CR>
```

**Comment by gerardroche** [comment]
Note that by default neo doesn't yank or paste from the system clipboard. You can enable that by setting `vintageous_use_sys_clipboard` to true.

Alternatively you can use mappings for yanking and pasting from the clipboard: 

```
" Yank and paste using system clipboard
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P
```

**Comment by gerardroche** [comment]
Closing this but I've added this to the list of suggestions for future plugin implementations here: https://github.com/NeoVintageous/NeoVintageous/issues/855
