### ISSUE TITLE
Support 'put and align' motion ]p

### ISSUE THREAD

**Issue by LPGhatguy** [NeoVintageous/NeoVintageous#339]
Sublime Text exposes paste and align as `ctrl+shift+v` when coming from the system clipboard. The equivalent motion in [Vim coming from a buffer is `]p`.](https://stackoverflow.com/a/235841/802794).

It doesn't appear that NeoVintageous supports this motion yet.

**Comment by gerardroche** [comment]
Until this is supported you can create a custom mapping.

1. Find out what command ST is using.

     Enable command & input logging: `Menu > View > Show Console`:

     Run `sublime.log_commands(True); sublime.log_input(True)`.

     When you run `ctrl+shift+v` it will now print something like:

     ```
     key evt: shift+control+v
     command: paste_and_indent
     ```

     The command used by ST is `paste_and_indent` (this is perfect for a custom mapping).

2. Open your vintageousrc file.

     From the command palette run: **NeoVintageous: Open My vintageousrc File** and add this mapping:

     ```
     nnoremap ]p :PasteAndIndent<CR>
     ```

3. Reload the **vintageourc** file.

    From the command palette run: **NeoVintageous: Reload My vintageousrc File**.

Done! Now `]p` is mapped to the built in paste and indent command. 

See `:h vintageourc` for more details.

**Comment by LPGhatguy** [comment]
The problem with remapping a motion like that is that Sublime's paste and indent comes from the system clipboard instead of the buffers like NeoVintageous's put (`p`) motion.

In the meantime, I can just use regular copy and `ctrl+shift+v`, or configure NeoVintageous to use the system clipboard for `y` and use `ctrl+shift+v`. This is already in my muscle memory at least!

**Comment by gerardroche** [comment]
@LPGhatguy I've implemented the paste and indent commands:

* Added [#339](https://github.com/NeoVintageous/NeoVintageous/issues/339): `[p` and `[P` like `P`, but adjust the indent to current line
* Added [#339](https://github.com/NeoVintageous/NeoVintageous/issues/339): `]p` and `]P` like `p`, but adjust the indent to current line

There might be a few tweaks and kinks needing fixing. Let me know how they work for you.
