### ISSUE TITLE
Support jumping to bottom/top of codeblocks/functions with ]] or ]}

### ISSUE THREAD

**Issue by slifin** [NeoVintageous/NeoVintageous#340]
In vim I think this can be achieved with ```[{``` or ```]}```

see: http://vim.wikia.com/wiki/Jumping_to_the_start_and_end_of_a_code_block

**Comment by gerardroche** [comment]
Part duplicate of https://github.com/NeoVintageous/NeoVintageous/issues/32 (`[[` and `]]`)
