### ISSUE TITLE
/ and ? search, add ':set ic' and ':set noic' command options?

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#35]
<a href="https://github.com/JesseLeite"><img src="https://avatars0.githubusercontent.com/u/5187394?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JesseLeite](https://github.com/JesseLeite)**
_Wednesday Feb 26, 2014 at 16:12 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/522_

----

I can't find anyway to do case insensitive search using `/` and `?`  If there currently is no ability, maybe we could get `:set ic` and `:set noic` options?

## Details

`:set ic` (shorthand for `:set ignorecase`) should change the `/` and `?` search functionality to be case insensitive.
`:set noic` (shorthand for `:set noignorecase`) should reset `/` and `?` search functionality back to default, which is case sensitive.

Here is link to [Vim Docs](http://vimdoc.sourceforge.net/htmldoc/options.html#'ignorecase') (Edit: That's weird, sometimes when I click on this link, it doesn't scroll page to proper section. If that happens, just search that page for 'ic', 'ignorecase', 'noic', or 'noignorecase', and you will find what you need there.)

PS. I am not Vim expert (just learning), but I think you can make real vim remember ':set ic' as default so that / and ? searches always use case insensitive matching.  If you implement the above commands, is there a way to run commands automatically when Vintageous starts/resets?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Wednesday Feb 26, 2014 at 16:46 GMT_

----

Could you please link to any relevant Vim docs? That would save me some research time.

**Comment by gerardroche** [comment]
<a href="https://github.com/JesseLeite"><img src="https://avatars0.githubusercontent.com/u/5187394?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JesseLeite](https://github.com/JesseLeite)**
_Wednesday Feb 26, 2014 at 16:54 GMT_

----

Sure :)

`:set ic` (shorthand for `:set ignorecase`) should change the `/` and `?` search functionality to be case insensitive.
`:set noic` (shorthand for `:set noignorecase`) should reset `/` and `?` search functionality back to default, which is case sensitive.

Here is link to Vim Docs: Vim Doc: http://vimdoc.sourceforge.net/htmldoc/options.html#'ic' (Edit: That's weird, sometimes when I click on this link, it doesn't scroll page to proper section. If that happens, just search that page for 'ic', 'ignorecase', 'noic', or 'noignorecase', and you will find what you need there.)

PS. I am not Vim expert (just learning), but I think you can make real vim remember ':set ic' as default so that / and ? searches always use case insensitive matching.  If you implement the above commands, is there a way to run commands automatically when Vintageous starts/resets?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Mar 01, 2014 at 11:41 GMT_

----

MD doesn't like this url:

[docs](http://vimdoc.sourceforge.net/htmldoc/options.html#'ignorecase')

**Comment by gerardroche** [comment]
<a href="https://github.com/JesseLeite"><img src="https://avatars0.githubusercontent.com/u/5187394?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JesseLeite](https://github.com/JesseLeite)**
_Saturday Mar 01, 2014 at 15:12 GMT_

----

MD?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Mar 01, 2014 at 17:17 GMT_

----

I think it rather goes by M&darr; these days :)

**Comment by gerardroche** [comment]
<a href="https://github.com/JesseLeite"><img src="https://avatars0.githubusercontent.com/u/5187394?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JesseLeite](https://github.com/JesseLeite)**
_Saturday Mar 01, 2014 at 20:43 GMT_

----

I'm so confused! :(

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Mar 01, 2014 at 20:46 GMT_

----

:) It's markdown, the lightweight markup language GitHub uses. GH tries to detect hyperlinks in comments but the last single quote trips up the parser, I guess.

**Comment by gerardroche** [comment]
<a href="https://github.com/JesseLeite"><img src="https://avatars0.githubusercontent.com/u/5187394?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [JesseLeite](https://github.com/JesseLeite)**
_Saturday Mar 01, 2014 at 21:32 GMT_

----

Ohhhhh markdown yeah lol. That went over my head. But shouldn't have :)

**Comment by gerardroche** [comment]
<a href="https://github.com/ebrady"><img src="https://avatars3.githubusercontent.com/u/1985373?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ebrady](https://github.com/ebrady)**
_Monday Apr 13, 2015 at 18:28 GMT_

----

Just thought I'd check in on the case sensitive / and ? search capability.  I too would much prefer the default be case sensitive (like vim/vi) if that is possible (with perhaps a setting to control it).  Anyhow, thanks much for all the great work (and your responsiveness on previous requests I've had).

**Comment by gerardroche** [comment]
@JesseLeite This is fixed in the next version, 1.7.2 (NeoVintageous is a fork of Vintageous).

**Comment by jesseleite** [comment]
Thanks!  I've moved on to terminal Vim myself, but appreciate your work on this 😊
