### ISSUE TITLE
Trying to enter visual block mode by pressing CTRL-V does not enable visual block mode but moves one page forward

### ISSUE THREAD

**Issue by Tijs-B** [NeoVintageous/NeoVintageous#356]
### Description
Trying to enter visual block mode by pressing CTRL-V does not enable visual block mode but moves one page forward (on OS X).
### Steps to Reproduce
- Open a file containing multiple lines
- While not in insert mode, press ctrl-V
### Expected behaviour
The mode switches to visual mode.
### Actual behaviour
The mode doesn't switch and the cursor moves forward one page.
### Versions
Sublime text 3.1.1, build 3176
NeoVintageous v.1.6.2
macOS 10.13.4
### Additional Information

Command logging shows the following log when pressing ctrl-V:
```
command: move {"by": "pages", "forward": true}
```

Input logging shows the following log when pressing ctrl-V:
```
key evt: control+v
key evt: control+v
```

Probably just a easy fix by overriding the key bindings. Thanks in advance.

**Comment by gerardroche** [comment]
Have you got the ctrl keys enabled?


Menu: `Preferences > Settings`

```
    {
        "vintageous_use_ctrl_keys": true
    }
```

**Comment by Tijs-B** [comment]
That fixed it. Many thanks.
