### ISSUE TITLE
NeoVintageous messes with LatexTools quickpanel

### ISSUE THREAD

**Issue by DrBones** [NeoVintageous/NeoVintageous#357]
### Description
When typing \input{ and then choosing something from the quickpanel that pops up from LatexTools the completion is inserted one character earlier, e.g \inpu{CompletedFilenameHere}t
This also happens with all other command that use the quickpanel, like \cite{ or \ref{

I am not quite sure if this is a bug in NeoVintageous or LatexTools, it does not happen with Vintage/Vintageous or Six though.

### Steps to Reproduce
Clean Sublime Text portable 
Install Package control
Install LatexTools and NeoVintageous

Create new LaTex file and type `\input{`
Select any autocompletion
### Expected behaviour
`\input{CompletedFileNameHere}`
### Actual behaviour
`\inpu{CompletedFileNameHere}`t

### Versions
Windows 10
Sublime Build 3176
LatexTools 3.15.1
NeoVintageous 1.6.2

### Additional Info

I have asked on the LatexTools github as well, I actually have no clue if this counts as cross posting :) If yes please close the issue.

**Comment by gerardroche** [comment]
Relates to #47. 

The issue explained here: 

https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346

I fixed the issue when using the Command Palette, but there's no way I see fixing it for overlays. The timer fix referenced in the commit is not a good workaround imo. The only real way to fix this is as explained at the end commit message.

**Comment by DrBones** [comment]
Thanks for  your quick response, 

until this redesign is made ,I guess I just deal with it or ask the LatexTools guys how to implement a workaround on their end.

On a side note, is this redesign planned or even ongoing? Maybe I can somehow help there?

**Comment by gerardroche** [comment]
It's a huge change, because it has the potential to break a lot of stuff, so it could be long while coming. There needs to be a lot more functional test coverage of the commands before a internal redesign like that. The functional test suite is growing well: https://github.com/NeoVintageous/NeoVintageous/tree/master/tests/functional

I'll try get a patch a LatextTools. It shouldn't be that difficult to patch.

**Comment by DrBones** [comment]
Ok, this redesign is well beyond my capabilities then :). I take a look at writing tests, since I that seems like something that is worthy to learn!

A patch for LatexTools would be greatly appreciated! 
Might be out of line but since NeoVintageous is mostly a one man show and I rely on it that much...is there a way to donate at least a coffee or so? I could not find anything regarding that in the readme.

**Comment by gerardroche** [comment]
Thanks for the thought, but I don't want to deal with donations. I should put something in readme about it.

**Comment by DrBones** [comment]
Then have my greatest respect instead! Have a great day :)

**Comment by gerardroche** [comment]
@DrBones I wonder if https://github.com/NeoVintageous/NeoVintageous/issues/547 fixes this issue?

**Comment by DrBones** [comment]
Yes it does! 

To be honest, I don't know if #547 fixed the issue or anything else but fact is, with Sublime Text 3.2.1 (build 3207) with LaTeXTools 3.15.1 and NeoVintageous 1.14.2, the issue does not exist. The cursor is now inserted just before the closing curly brace in insert mode.

Thank you!

**Comment by gerardroche** [comment]
I had a feeling this might fix it, because the issue was a side effect of the fact that when Sublime lost focus the mode was always reset to normal mode. I've been trying to figure out how to fix that issue for ages.

**Comment by dougalsutherland** [comment]
This is still an issue for me, with ST build 3207, LaTeXTools 3.15.1, NeoVintageous 1.15.1.

Autocompletion for e.g. `\cite{}` works fine for me if there's more content on the line after the `{`, but not if it's the end of the line (as it usually is when you're writing new text) – if it's the end of the line, I end up with `\cit{whatever-key}e`. This is the same behavior for me as it's been for a long time.

**Comment by dlguo** [comment]
> This is still an issue for me, with ST build 3207, LaTeXTools 3.15.1, NeoVintageous 1.15.1.
> 
> Autocompletion for e.g. `\cite{}` works fine for me if there's more content on the line after the `{`, but not if it's the end of the line (as it usually is when you're writing new text) – if it's the end of the line, I end up with `\cit{whatever-key}e`. This is the same behavior for me as it's been for a long time.

The same for me with ST 3211, LatexTools 3.15.1 and NeoVintageous 1.17.5. It looks like all completions have the issue.
