### ISSUE TITLE
Searching for regex characters like "(" and "[" doesn't work.

### ISSUE THREAD

**Issue by Sheepolution** [NeoVintageous/NeoVintageous#363]
### Description
When searching for regex-characters like "(" or "[" (using / or ?) NeoVintageous is not able to find these unless you escape the characters. I think the best solution is to search for the text literally when nothing is found with regex.

Note that this does work in Vim.

### Steps to Reproduce

1. Open a new tab
2. Insert the following text: "Here is ( some text"
3. Set your cursor at the start.
4. Use /( to navigate to this character.

### Expected behaviour
( is highlighted.

### Actual behaviour
( is not found.

### Versions
1.6.3
Windows 10

**Comment by gerardroche** [comment]
You can disable that behaviour by setting `vintageous_magic` to false. See `:h nv` and `:h 'magic'`.

That said `vintageous_magic` doesn't seem to work like it does in Vim. It needs revising.

**Comment by gerardroche** [comment]
The `magic` option determines if regular expressions should be used in **?** or **/** searches. When disabled regular expressions are never used so you can search for characters like **[** and **(** without needing to escape them.  

To disable it go to **Menu > Preferences > Settings**

```
{
	"vintageous_magic": false,
}
```

When enabled, Vim tries to be smart about it e.g. if you are just searching for `[` then it knows it's not a regular expression, so it just searches as as literal and you don't need to escape, however if you search `[0-9]` then it knows it is a regular expression.

In version 1.8.0 searching will be a little smarter when magic is enabled.

Vimdocs:

```
						*'magic'* *'nomagic'*
'magic'			boolean	(default on)
			global
	Changes the special characters that can be used in search patterns.
	See |pattern|.
```
