### ISSUE TITLE
dot cannot repeat substitution operation

### ISSUE THREAD

**Issue by michaelHL** [NeoVintageous/NeoVintageous#365]
When I have something to replace, I often locate the first occurrence of the word, `cw` / `r<somekey>` and type new characters, `esc`. And next I can just replace the remained same words by `n.`

Unfortunately, NeoVintageous keep searching the next occurrence of the word when I type `.`

So in many cases I have to record a macro to do the work... Could you please fix it ? Thanks !

Demo (type `/@ r.  n.n.n.n.n.`):

![](https://i.imgur.com/xnn1mss.gif)

**Comment by gerardroche** [comment]
I can't reproduce this issue. 

The sequence I try is `/@<Enter>r.n.n.n.`.

What version of Sublime Text are you using and what OS? Also if you can provide some additional infor that would be great. See https://github.com/NeoVintageous/NeoVintageous/blob/master/ISSUE_TEMPLATE.md.

**Comment by michaelHL** [comment]
@gerardroche Something in detail:

- OS: Windows 10.0.16299
- Sublime Text: 3126
- NeoVintageous: 1.6.3 - 2018-05-31

And this is my `.vintageousrc`:

```vim
let mapleader=<space>

nnoremap U <C-r>
nnoremap j gj
nnoremap k gk
nnoremap n         nzz
nnoremap N         Nzz
nnoremap {         {zz
nnoremap }         }zz
nnoremap *         *zz
nnoremap #         #zz
nnoremap g*        g*zz
nnoremap <leader>q :q<CR>
nnoremap <leader>w :w<CR>
nnoremap <C-w> :q<CR>
```

And there's the same issue with previous versions of NeoVintageous.

Should I try the newest ST3 ? Thanks !

**Comment by gerardroche** [comment]
You have **n** remapped to **nzz**. So when you're pressing **n** it's actually remapping to **nzz**.

**Comment by michaelHL** [comment]
Thanks a lot! It worked!
