### ISSUE TITLE
Folding with zc enters visual mode.

### ISSUE THREAD

**Issue by hweom** [NeoVintageous/NeoVintageous#366]
### Description

When folding code with zc, editor folds the scope, but switches to visual mode at the same time. 

![myimage](https://user-images.githubusercontent.com/4531463/42413193-2290f764-81d0-11e8-9e6d-bc63962c6709.gif)

### Steps to Reproduce
Install NeoVintageous, add the following to the keyboard settings:

```
	{ "keys": ["z", "c"], "command": "fold" },
	{ "keys": ["z", "o"], "command": "unfold" },
```
Inside a code block, press `z`, `a`.

### Expected behaviour

Folding without entering visual mode.

### Actual behaviour

NeoVintageous enters visual mode after block folding.

### Versions

Version 3.1.1 build 3176

Archlinux 64 bit.

**Comment by gerardroche** [comment]
Try using NeoVintageous mappings. Sublime Text mappings won't work so well. See `:h nv` or https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt. 

Also maybe my mappings will help, I've played around with some folding mappings: https://github.com/gerardroche/sublimefiles/blob/master/User/.vintageousrc

**Comment by carlevison** [comment]
Then he would have the issue which relates to #308

Due to his key binding both starting with the same letter and muscle memory.

**Comment by gerardroche** [comment]
@carlevison No I don't think that issue relates. The other issue is triggered when trying to map a single key like **f** and also use it as a prefix **fb**. Neo doesn't have the ability to trigger the first mapping after n secs, if no other key is pressed. There is no single key  **z** command.

**Comment by hweom** [comment]
I've removed all entries from my `.sublime-keymap` and added the following to the `.vintageousrc`:

```
" Type :h vintageousrc for help.

" Folds
nnoremap zc :Fold<CR>
nnoremap zo :Unfold<CR>
nnoremap zM :FoldAll<CR>
nnoremap zR :UnfoldAll<CR>
```

But it still exhibits the same behavior.

**Comment by gerardroche** [comment]
Make sure you reload your vintageousrc file via the Command Pallette: `Reload My .vintageousrc File`. Or try a restart.

**Comment by hweom** [comment]
Tried both. In fact, it's happening even if I fold with `:Fold` command.

Recorded some more examples with logs:

![example1](https://user-images.githubusercontent.com/4531463/42593133-78bf489c-8500-11e8-97e0-47569325f9ca.gif)

![example2](https://user-images.githubusercontent.com/4531463/42593137-7be8b10c-8500-11e8-8f2a-a7db7bf34527.gif)

**Comment by gerardroche** [comment]
I can't reproduce it. When I close via **zc** my cursor is put on the first character at the start of the fold i.e. on the **s** of struct, and I'm in normal mode.

**Comment by gerardroche** [comment]
Everything looks good. For some reason after you run the fold command it's triggering 3 `j` presses.

I'm assuming it doesn't happen with commands like unfold. My guess is that you have a rouge key binding a plugin is overriding the fold command. Check your User directory for keymap files (`Menu > Preferences > Borwse Packages...` go to the User directory). Also look for any py files that probably shouldn't be there.

**Comment by hweom** [comment]
It *does* happen for unfolding with `zo` and `:Unfold`. Note that folding/unfolding by clicking the triangle left to the code block does not start the visual mode.

Here is the context of the `User` directory:
```
$ ls -a
 .                                'Package Control.merged-ca-bundle'
 ..                               'Package Control.sublime-settings'
'Default (Linux).sublime-keymap'  'Package Control.user-ca-bundle'
'Package Control.cache'            Preferences.sublime-settings
'Package Control.last-run'         .vintageousrc
```
```
$ cat Default\ \(Linux\).sublime-keymap 
[
]
```
```
$ cat .vintageousrc 
" Type :h vintageousrc for help.

" Folds
nnoremap zc :Fold<CR>
nnoremap zo :Unfold<CR>
nnoremap zM :FoldAll<CR>
nnoremap zR :UnfoldAll<CR>
```
```
$ cat Preferences.sublime-settings 
{
  "font_size": 11,
	"ensure_newline_at_eof_on_save": true,
	"ignored_packages":
	[
		"Six",
		"Vintage",
		"Vintageous"
	],
	"rulers":
	[
		80
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"vintageous_use_ctrl_keys": true
}
```
```
$ cat Package\ Control.sublime-settings 
{
	"bootstrapped": true,
	"in_process_packages":
	[
	],
	"installed_packages":
	[
		"NeoVintageous",
		"Package Control"
	],
	"repositories":
	[
	]
}
```

**Comment by carlevison** [comment]
After copying @hweom .vintageousrc file I can confirm I am experiencing the same issue that i'm being taken into VISUAL mode.

**Comment by gerardroche** [comment]
Found it. Thanks.

The reason I couldn't reproduce it is because I have a custom fix to work around the issue:

https://github.com/gerardroche/sublimefiles/blob/983466569aeedd5455b74a73bbd15b22b27427a7/User/user_folds.py

There's no easy way for Neo to work around this issue. The fold commands themselves enter VISUAL mode. The workaround overrides the fold commands and fixes the cursor after fold commands are run. We can't really add this fix to Neo because overriding the default commands is a bit hacky.

**Comment by hweom** [comment]
> The fold commands themselves enter VISUAL mode.

I don't know what part of original Sublime functionality these commands use. Just FYI, folding by clicking on the triangles right to the code blocks does not start VISUAL mode.
