### ISSUE TITLE
Swapping 'f' and 'h' doesn't work

### ISSUE THREAD

**Issue by lukedegruchy** [NeoVintageous/NeoVintageous#369]
### Description
Swapping 'f' and 'h' doesn't work in .vintageousrc.

### Steps to Reproduce
Neovintageous: Open My .vintageousrc File

Add the following content:

noremap f h
noremap h f
noremap H F
noremap F H

### Expected behaviour

I can use the 'f' key to move the cursor left/

### Actual behaviour

While 'h' seems to take the place of the 'f' key, the 'f' key doesn't move the cursor left.

### Versions

Sublime Text Version 3.11, Build 3176

macOS High Sierra 10.13.6 

### Additional Information

The above configuration was working perfect fine under Vintageous, until it was deactivated.

**Comment by gerardroche** [comment]
I can't reproduce it. Did you try reload you vintageourc file? Run the command `Neovintageous: Reload My .vintageousrc File`, or try a restart.

**Comment by lukedegruchy** [comment]
I figured out what was causing this.    It's because of this configuration left over in my Default sublime-keymap left over from when I had Vintageous:

``
    {"keys": ["h", "<character>"], "command": "set_motion", "args": {
		"motion": "vi_move_to_character",
		"motion_args": {"extend": true },
		"inclusive": true,
		"clip_to_line": true },
		"context": [{"key": "setting.command_mode"}]},
	{"keys": ["f"], "command": "set_motion", "args": {
		"motion": "vi_move_by_characters_in_line",
		"motion_args": {"forward": false, "extend": true }},
		"context": [{"key": "setting.command_mode"}]}
``

Once I commented out this config NeoVintageous remapping worked.   This means the bug I filed is invalid and I'm going to close it.
