### ISSUE TITLE
Original post repeat command cursor behavior missing

### ISSUE THREAD

**Issue by burgreen** [NeoVintageous/NeoVintageous#370]
Vintageous had a really nice behavior that I am seeking to enable.

After repeating the last command using ".", the cursor would stay in the starting column where the "." was initiated. This behavior allowed for some really quick and easy mods.

Can I enable NeoVintageous to do this? If not, I would like to make a feature request.

**Comment by burgreen** [comment]
Eh, this does exactly what I want.
https://stackoverflow.com/questions/14567868/how-to-return-the-cursor-to-its-previous-position-after-the-dot-command/14568298

**Comment by gerardroche** [comment]
You can maybe get the desired behavior using your vintagousrc file. See `h nv` or https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt for details.

**Comment by gerardroche** [comment]
The current behavior works like this:

Given the text, where the cursor is represented by `|` (bar) in INSERT mode:

    abc |def

Pressing `123<Space><Esc>...` (three repeats), will result in:

    abc 123|123 123 123  def


Can you show me what you expect to happen, or would like it to do?

Also, you can configure mapping just like in vim by using your vintageousrc file. See the docs at https://raw.githubusercontent.com/NeoVintageous/NeoVintageous/master/res/doc/neovintageous.txt or from within Sublime Text `:help nv`.
