### ISSUE TITLE
vii does not select the whole indented line

### ISSUE THREAD

**Issue by haolly** [NeoVintageous/NeoVintageous#373]
### Description
indented line will not be selected when there is an empty line
### Steps to Reproduce
```lua
function mt:fine()
	local a = 1;
	
	local b = 2;
end
```

put cursor in line 2, issue command **vii**
### Expected behaviour
line 2-4 will be selected
### Actual behaviour
only line 2 be selected
### Versions
1.6.3
OS: OSX 10.13.3

**Comment by gerardroche** [comment]
`vii` ? I can't find any documentation in Vim on this command?

**Comment by haolly** [comment]
@gerardroche  This is not a standard command, see https://github.com/VSCodeVim/Vim#vim-indent-object , but  It looks like partial support for this feature

**Comment by gerardroche** [comment]
You might be able to get something workable using your vintageourc file. See `:h nv` or https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt

**Comment by gerardroche** [comment]
For future reference:

I didn't realise there is already some support for the Indent Object plugin. The implementation is a little broken, as you've rightly highlighted.  

Plugin: https://github.com/michaeljsmith/vim-indent-object
