### ISSUE TITLE
No surround key mappings seem to be valid

### ISSUE THREAD

**Issue by mqudsi** [NeoVintageous/NeoVintageous#375]
### Description
All surround.vim key mappings trigger a visual bell on a clean installation of Sublime Text 3 and neovintageous via package control with the default neovintageousrc.

### Steps to Reproduce
Create a new document and type in `(hello world)` then type `ds)` in visual mode.

### Expected behaviour
Surround.vim should be triggered. The parentheses should be deleted.

### Actual behaviour
The visual bell is triggered after `cs` and the command is invalidated.

### Versions

3.1.1 Build 3176 under Windows 10 64-bit

### Additional Information

`ys`, `ds`, and `S` all behave similarly.

**Comment by gerardroche** [comment]
I'm unable reproduce this. If you could provide some debug information it would be great. See: https://github.com/NeoVintageous/NeoVintageous/blob/master/ISSUE_TEMPLATE.md#additional-information.

**Comment by gerardroche** [comment]
Maybe you have surround plugin disabled, Check your settings for `vintageous_enable_surround`:

**Menu > Preferences > Settings** 

Set `vintageous_enable_surround` to true and see if that fixes it.
