### ISSUE TITLE
Scrolling with ctrl-f and ctrl-b

### ISSUE THREAD

**Issue by plbowers** [NeoVintageous/NeoVintageous#378]
### Description

I want to scroll down (pgdn) with ctrl-f and up (pgup) with ctrl-b, like vim/vi/etc

### Steps to Reproduce

Press ctrl-f or ctrl-b

### Expected behaviour

Scroll down or up a page

### Actual behaviour

Ctrl-f triggers "find" and ctrl-b apparently does nothing

### Versions

startup, version: 3176 windows x32 channel: stable

Also, please include the OS and what version of the OS you're running.

Windows 10

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

I had vintage installed before and just included it in ignored_packages to get rid of it

**Comment by gerardroche** [comment]
Enabled **vintageous_use_ctrl_keys**.


**Menu > Preferences > Settings**

    {
        "vintageous_use_ctrl_keys": true
    }

```

See also `:h nv` for more documentation.

**Comment by plbowers** [comment]
Sorry - I had mis-typed the command. I had "vintageous_ctrl_keys" instead of "vintageous_use_ctrl_keys". My mistake. Thanks for the help.
