### ISSUE TITLE
Visual mode with ]} movement doesn't appear to work

### ISSUE THREAD

**Issue by slifin** [NeoVintageous/NeoVintageous#379]
To replicate move into the top of a function inside a C like language and press, ```v ] }``` I expected that it would select everything between the function curly braces, instead the cursor blinked twice and selected no characters

**Comment by gerardroche** [comment]
:+1: It works in NORMAL mode, but not VISUAL.

**Comment by gerardroche** [comment]
Relates a litle to https://github.com/NeoVintageous/NeoVintageous/issues/32
