### ISSUE TITLE
esc directly after O or o does not remove whitespace from autoindent

### ISSUE THREAD

**Issue by davea1** [NeoVintageous/NeoVintageous#380]
Using `O` or `o` followed immediately by `esc` will leave behind whitespace in cases where an autoindent has occurred.

With Vim, all such whitespace is removed as soon as `esc` is hit, leaving only a blank line.

**Comment by davea1** [comment]
Note - the Vim emulation extension available for VSCode, the Vim emulation that is built into SlickEdit and also the Six package for Sublime Text all correctly emulate Vim behavior in this respect.

I utilize this feature all the time whenever using Vim (or VSCode) since it has now been well engrained into my muscle memory ever since discovering it as a commonly known procedure for quickly inserting a blank line in code.

I do realize that I could optionally use the `]<Space>` and `[<Space>` commands that are specific to NeoVintageous for this functionality, but again...muscle memory.    :)

Hopefully, you can fix this feature soon. Thanks!

**Comment by gerardroche** [comment]
I'm wondering if whitespace should always be removed on `<Esc>` (if the line is empty), and not just after commands like **0** and **o**, and only if `auto_indent` setting is enabled.

**Comment by davea1** [comment]
It would appear that your theory is indeed correct. Some quick tests with Vim have revealed that this behavior should apply across other scenarios.

For example: While typing multiple lines of code in insert mode, whenever a new auto-indented line is initially created, subsequently hitting `<Esc>` before typing any characters will cause the whitespace to be removed leaving a blank line.

I have actually encountered this aspect of the bug many times in the past, but had simply forgotten.

Brilliant deduction!

**Comment by davea1** [comment]
Works great. Thanks!

I created a new issue (#440) to track the other scenario that was discussed/discovered.
