### ISSUE TITLE
Implement cgn

### ISSUE THREAD

**Issue by EmperorEarth** [NeoVintageous/NeoVintageous#382]
Requesting implementation of `cgn`

![Explanatory gif](https://cdn-images-1.medium.com/max/800/1*xrEmsNKaOguADXWAKkeSEA.gif)

Excerpt from [blog detailing it](https://medium.com/@schtoeffel/you-don-t-need-more-than-one-cursor-in-vim-2c44117d51db):

> In vim selecting and editing is one step. This can be done with the gn text-object. Normally you will search for a word you want to change and the change the next found occurrence with cgn once and then use vim’s most powerful command the . (dot). Using . you can apply the change to the next word or skip one word with n which will jump to the next word.

Currently, we have to use `ciw` ... `n` `.` `n` `.`...
With `cgn`, we could use: `cgn` ... `.` `.` ...

**Comment by gerardroche** [comment]
This is certainly possible. I think implementing `gn` will be enough to add this feature.
