### ISSUE TITLE
line delete (dd) no longer works in command mode

### ISSUE THREAD

**Issue by realchrisolin** [NeoVintageous/NeoVintageous#383]
### Description
The line delete hotkey (dd) is no longer working

### Steps to Reproduce
1). install latest versions of sublime 3 and neovintageous
2). open a text file with multiple lines of data
3). press the 'd' key twice while in command mode

### Expected behaviour
current line is deleted

### Actual behaviour
The character cursor moves to the beginning of the line

### Versions
DPI mode: per-monitor v2
startup, version: 3176 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/Chris Olin/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/Chris Olin/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/Chris Olin/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Six", "Vintage", "Vintageous"]
pre session restore time: 0.200136
startup time: 0.284136
first paint time: 0.286136
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.01-pygments
reloading plugin 0_package_control_loader.50-backrefs
reloading plugin 0_package_control_loader.50-markupsafe
reloading plugin 0_package_control_loader.50-pymdownx
reloading plugin 0_package_control_loader.50-python-markdown
reloading plugin 0_package_control_loader.50-pyyaml
reloading plugin 0_package_control_loader.51-python-jinja2
reloading plugin 0_package_control_loader.55-mdpopups
reloading plugin BracketHighlighter.bh_core
reloading plugin BracketHighlighter.bh_logging
reloading plugin BracketHighlighter.bh_plugin
reloading plugin BracketHighlighter.bh_popup
reloading plugin BracketHighlighter.bh_regions
reloading plugin BracketHighlighter.bh_remove
reloading plugin BracketHighlighter.bh_rules
reloading plugin BracketHighlighter.bh_search
reloading plugin BracketHighlighter.bh_swapping
reloading plugin BracketHighlighter.bh_wrapping
reloading plugin BracketHighlighter.support
reloading plugin FileDiffs.file_diffs
reloading plugin Git blame.git-blame
reloading plugin Git.git_commands
reloading plugin GitGutter.plugin
reloading plugin Indent XML.indentxml
reloading plugin Indent XML.setup
reloading plugin JSON Reindent.sublime_json_reindent
reloading plugin NeoVintageous.plugin
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin SublimeGit.SublimeGit
reloading plugin ToggleNeoVintageous.plugin
reloading plugin HTML-CSS-JS Prettify.HTMLPrettify
reloading plugin SublimeREPL.__init__
reloading plugin SublimeREPL.completions
reloading plugin SublimeREPL.lang_integration
reloading plugin SublimeREPL.run_existing_command
reloading plugin SublimeREPL.sublimerepl
reloading plugin SublimeREPL.sublimerepl_build_system_hack
reloading plugin SublimeREPL.text_transfer
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2018-10-25 14:16:05, next run at 2018-10-25 15:16:05 or after
Unable to open /C/Users/Chris Olin/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings

You can get Sublime Text version information from copy and pasting the output of the console `Menu > View > Show Console`.

Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

You can get debugging information by copy and pasting the output of the console `Menu > View > Show Console`.

Command and input logging can be enabled from the console (run the commands in input box at the bottom of the console): `sublime.log_commands(True)` for command logging, and `sublime.log_input(True)` input logging. See the [debugging guide](https://github.com/NeoVintageous/NeoVintageous/CONTRIBUTING.md#debugging) for more detailed debugging information.

You may also want to review the help documentation using the command `:h nv` or visit the [documentation online](https://github.com/gerardroche/sublimefiles/blob/master/User/.vintageousrc).

**Comment by gerardroche** [comment]
I'm unable to reproduce the issue. 

I see from your debug log that Sublime Text is having an issue loading your Sublime Text settings file:

```
Unable to open /C/Users/Chris Olin/AppData/Roaming/Sublime Text 3/Packages/Default/Preferences.sublime-settings
```

Your settings file is probably invalid (corrupted). It should be a valid json file. Try fixing the settings file and see if that resolves the issue.

If that doesn't resolve it, a plugin might be overriding the keymaps, or you might have some custom keymaps. Check your Keymaps file **Menu > Preferences > Key Bindings**. And also check if you have any .vintageousrc keymaps configured, open them via the Command Palette **NeoVintageous: Open My vintagesousrc File**.
