### ISSUE TITLE
Errors caused jj to exit insert mode 

### ISSUE THREAD

**Issue by adamgajzlerowicz** [NeoVintageous/NeoVintageous#384]
### Description
Sublime is confused by what is in the contents of the file. It is possible that this is an issue with LSP or combination of two. I was hoping you can help with this. It happens most of the time when I type and it is quite annoying.

### Steps to Reproduce
Write your document. Press `j j` to exit insert mode. 

### Expected behaviour
What is visible on the screen is what is interpreted by other plugins

### Actual behaviour
LSP seems to think that on of pressed `j`s is still there

### Versions
sublime version `version: 3176` stable.
macOS Mojave

### Additional Information

![image](https://user-images.githubusercontent.com/675615/47650956-1cc98380-db82-11e8-896f-71aadf8cd26e.png)

**Comment by gerardroche** [comment]
You closed the issue. Did you resolve the issue?

**Comment by adamgajzlerowicz** [comment]
Hi, yes - I had LSP misconfigured. Changing config setting `complete_all_chars` to false fixed it... 

Thank you for coming back to me anyway!
