### ISSUE TITLE
NeoVintageous dot command (repetition command) does not account for autocomplete

### ISSUE THREAD

**Issue by asamolion** [NeoVintageous/NeoVintageous#387]
### Description
One of the issues I mostly face is that the dot command which is used to repeat the last input does not correctly repeat if I have used the Tab key to auto complete the last input.

### Steps to Reproduce
Type any autocompletable word into the editor

![](https://forum.sublimetext.com/uploads/default/original/3X/7/5/7574b44c1f6ad8eb029dfb7b6be42bb020e28569.png)

Then Autocomplete using Tab or Enter
![](https://forum.sublimetext.com/uploads/default/original/3X/f/a/fa1a581d85c235b0762e26d8eea8db373a0479df.png)

Then press dot to repeat, It only repeats the text typed manually
![](https://forum.sublimetext.com/uploads/default/original/3X/a/9/a99ffcc04fb9c1c63c787f4547375fa2019f1b41.png)

### Expected behaviour
Dot command ignores the text inserted using autocomplete

### Actual behaviour
Dot command should include the autocompleted text when it is used to repeat text.

### Versions
Linux Mint 19
Sublime Text 3 Build 3176

**Comment by asamolion** [comment]
After going through the source code, I found a fix for this. 
Sublime Text issues a separate command when autocompletion is done using the Tab key vs the Enter key. 

If I autocomplete using the Tab key then the dot command works perfectly. So I simply added the following key mapping to my editor.

```
{
  "keys": [
    "enter"
  ],
  "command": "insert_best_completion",
  "args": {
    "default": "\t",
    "exact": false
  },
  "context": [
    {
      "key": "auto_complete_visible",
      "operand": true
    }
  ]
}
```

**Comment by rkoval** [comment]
The behavior of my Sublime Text setup seemed to act a bit differently. @asamolion's suggestion didn't work for me, but led me down the right path. For me, I needed to add the following mapping (for `ctrl+k` autocomplete) instead:
```json
{
  "keys": ["ctrl+k"],
  "command": "commit_completion",
  "context": [{ "key": "auto_complete_visible" }]
}
```
The dot command then respected autocomplete afterwards.
