### ISSUE TITLE
.vintageousrc doesn't load in windows

### ISSUE THREAD

**Issue by eduardoarandah** [NeoVintageous/NeoVintageous#419]
Plugin doesn't  load .neovintageousrc file in windows. 

![image](https://user-images.githubusercontent.com/4065733/51407772-6e9afd80-1b22-11e9-8ac4-6a7fab8fb6fb.png)

I opened console, with this to see if any errors occured, then "reload my .neovintageousrc file"
but nothing happens:

`sublime.log_commands(True); sublime.log_input(True); sublime.log_commands(True); sublime.log_result_regex(True);`

### Versions
Windows 10, ST 3.1.1, neovintageous 1.7.5

**Comment by gerardroche** [comment]
The **vintagousrc** file has limited support. `let` currently only supports the mapleader. `:set` commands are not supported. `highlightedyank=false` is invalid. Remove lines 6 through 17.

Your **vintageousrc** file is loading, some of your configs are just not supported. See `:h nv` for the docs, or https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L101

**Comment by gerardroche** [comment]
To disable highlightedyank

`Menu > Preferences > Settings`: >

```
    {
        "highlightedyank": false
    }
```

See `:h nv-options`
