### ISSUE TITLE
Direct shell command exec in project

### ISSUE THREAD

**Issue by duraki** [NeoVintageous/NeoVintageous#421]
### Description
The exclamation mark (`!`) followed by a command (ie `!ls -la`) executes and yield output on a host level. The problem arise user want exec in the current working directory (set to working directory by default **on Vim**, pointing to Sublime Text installation path on **NeoVintageous**).  
  
### Steps to Reproduce
```sh
$ mkdir -p /tmp/my_project /tmp/my_project/src && echo "oi" > /tmp/my_project/README.md && cd /tmp/my_project

$ vim .
# => !pwd
/tmp/my_project

...

$ subl .
# => !pwd
/Users/<user>/Library/Application Support/Sublime Text 3/Packages
```

### Expected behaviour
NeoVintageous should register current working directory as a working path. User will be able to exec commands on this tree.

### Actual behaviour
NeoVintageous register `/Packages` subdirectory as a working path. User is not able to interact with source files on actual project tree until switching path.

### Versions

ST3//3176
MacOS Mojave

Possibly related to #284.

**Comment by gerardroche** [comment]
The fix in the next should mostly resolve the issue. The fix leverages some global variables that Sublime extracts from the environment. I've tested commands like `!ls` and `:browse` (which is now a useful command).

**Comment by duraki** [comment]
Excellent, that was fast 🥇 ! Will try and test the patch.
