### ISSUE TITLE
:e open a file path relative to another file opened

### ISSUE THREAD

**Issue by ljgago** [NeoVintageous/NeoVintageous#436]
### Description
The command `:e` or `:edit` open a file path relative to the file path that I am using, but the autocomplete path is working relative to project folder.
If I not open a file previously the command `:e` does not work

### Steps to Reproduce
I have this in my project folder:

```
cmd/log/log.go
cmd/server.go
README.md
```
- I open `README.md` and write `:e cmd/server.go` or `:e cmd/log/log.go`  with autocomplete and work fine.
- I open `cmd/server.go` and write `:e README.md` with autocomplete and open a new empty file.
`Unable to open /home/.../cmd/README.md`
- I open `cmd/log/log.go` and write `:e ../../README.md` without autocomplete (it shows nothing) and open the file.

### Expected behaviour
- I open `cmd/server.go` and write `:e README.md` with autocomplete and open the file `README.md`.
- I open `cmd/log/log.go` and write `:e README.md` with autocomplete and open the file.

### Versions
1.8.0

**Comment by gerardroche** [comment]
This is related to a recent change in the way the current working directory for commands like :e and :w work #421. The cwd is now the project root, which more closely works like Vim. This has fixed various issues. Previously the cwd would be set to whatever file was active when you started ST. The change was significant and has highlighted more issues around how the cwd is initialized e.g. https://github.com/NeoVintageous/NeoVintageous/issues/423#issuecomment-458749011.

The next release [1.9.0](https://github.com/NeoVintageous/NeoVintageous/milestone/18?closed=1), coming shortly, has fixes for some of the issues. But it looks like there is still some issues in the develop branch relating to this issue, for example `:e unknown.txt` looks broken:

```
NeoVintageous: DEBUG   [ex_cmds.py:1620] do ex cmdline >>>:e foo<<<
NeoVintageous: DEBUG   [parser.py:64] parsing source >>>e foo<<<
NeoVintageous: DEBUG   [parser.py:74] parsed edit {'params': {'count': None, '++': None, 'file_name': 'foo', 'cmd': None}, 'name': 'edit', 'content': 'edit', 'forced': False, 'target': 'edit', 'cooperates_with_global': False, 'addressable': False}
NeoVintageous: DEBUG   [ex_cmds.py:1666] execute ex command: edit {'count': None, 'view': <sublime.View object at 0x7fd1b88b46d0>, '++': None, 'file_name': 'foo', 'cmd': None}
NeoVintageous: DEBUG   [ex_cmds.py:86] original cwd: /home/code/sublime_text_3
NeoVintageous: DEBUG   [ex_cmds.py:90] cmdline cwd: /home/code/.config/sublime-text-3/Packages/NeoVintageous
NeoVintageous: DEBUG   [ex_cmds.py:93] changing cwd to /home/code/.config/sublime-text-3/Packages/NeoVintageous from /home/code/sublime_text_3
NeoVintageous: could not find a parent directory
NeoVintageous: DEBUG   [ex_cmds.py:99] resetting cwd to /home/code/sublime_text_3
command: drag_select {"event": {"button": 1, "x": 391.547851562, "y": 353.034881592}}
NeoVintageous: DEBUG   [cmds_vi_actions.py:410] _enter_normal_mode mode=mode_normal, from_init=True
NeoVintageous: DEBUG   [cmds_vi_actions.py:497] _enter_normal_mode_impl mode=mode_normal
NeoVintageous: DEBUG   [state.py:252] sequence >>><<<
NeoVintageous: DEBUG   [state.py:265] partial sequence >>><<<
```

**Comment by gerardroche** [comment]
In the next version the cwd is the project root. Auto complete will always be based off the cwd. I've also fixed the other related issues with the `:e` command.

Thanks btw for reporting this issue.
