### ISSUE TITLE
[Surround] Expose "append_addition_space" flag

### ISSUE THREAD

**Issue by lvalkov** [NeoVintageous/NeoVintageous#455]
Hi, would it be possible to make the `surround.py` `append_addition_space` flag accessible?
Example (`*` denotes current cursor position):

given `foo*bar`, `ysiw(` results in `*( foobar )`

I don't know what the exact behavior is, as far as the original Surround plugin is concerned, but I find these extra spaces undesirable.

If it isn't possible, I am open to other solutions(preferably, besides editing and outright overriding `surround.py` since that's what I'm already doing and would like to avoid).

Thanks.

**Comment by gerardroche** [comment]
Opening tags append a space, closing tags omit the space. For example:

* `ysiw(` -> `( foobar )`
* `ysiw)` -> `(foobar)`

This works with other tags too:  `)`, `}`, and `]`, in other surround commands too `cs`, `ds`, etc.

> If either ), }, ], or > is used, the text is wrapped in the appropriate pair
of characters.  Similar behavior can be found with (, {, and [ (but not <),
which append an additional space to the inside.  Like with the targets above,
b, B, r, and a are aliases for ), }, ], and >.

**Comment by lvalkov** [comment]
Understood, thanks for the information.  I'll create multiple mappings to override the _add-space_ case.
