### ISSUE TITLE
Cannot map build command

### ISSUE THREAD

**Issue by darkermatter** [NeoVintageous/NeoVintageous#463]
### Description
I am trying to map the build command as follows:
```
nnoremap <leader>r :Build variant=Run<CR>
``` 

If I go into command mode and type the command it works.

### Steps to Reproduce
Type ```<leader>r```

### Expected behaviour
Build with "Run" variant

### Actual behaviour
Nothing happens

### Versions
ST3: version: 3197 osx x64 channel: dev
NV: latest - no upgrade available
OS: macOS Mojave 10.14.3

**Comment by gerardroche** [comment]
> If I go into command mode and type the command it works.

It works in normal mode, but **not** in other modes? That probably means you need to change the mapping to something like:

```
noremap <leader>r :Build variant=Run<CR>
```

Notice the difference between **nnoremap** and **noremap**.

* **nnoremap** means only apply the mapping **only** in normal mode
* **noremap** means apply the mapping in normal, visual, and operator modes

For example, you can also create mappings to apply only in visual mode:

```
vnoremap <leader>r :Build variant=Run<CR>
```

See `:h nv-rc` for the help.

Note that only the non-recursive mappings are currently supported:

```
:noremap    {lhs} {rhs}
:nnoremap   {lhs} {rhs}
:onoremap   {lhs} {rhs}
:snoremap   {lhs} {rhs}
:vnoremap   {lhs} {rhs}
```

**Comment by darkermatter** [comment]
Thanks for your reply @gerardroche

I am aware of the difference. It only really makes sense to map the command in normal mode as my ```<Leader>``` is ```<space>```.

The command works if I type it manually after invoking command mode with ```:``` but it doesn't work if I invoke it with the mapping.

**Comment by gerardroche** [comment]
I can't reproduce it. Can you post some debug info? 

On Linux you an start Neo via the command line with a debug env variable:

```
$ SUBLIME_NEOVINTAGEOUS_DEBUG=y subl
```

## Debugging

The Sublime Text startup log is found in the console: `Menu > View > Show Console`.

Command and input logging can be enabled from the console (run the commands in input box at the bottom of the console): `sublime.log_commands(True)` for command logging, and `sublime.log_input(True)` input logging.

Neovintageous debug messages are disabled by default. You can enable them by setting an environment variable named `SUBLIME_NEOVINTAGEOUS_DEBUG` to a non-blank value. See [set a Sublime Text environment variable](https://github.com/gerardroche/sublime-phpunit#debugging) for a step by step guide on how to set environment variables for Sublime Text. The debug log is located at `Packages/User/NeoVintageous.log`. Debug messages are also printed to the console: `Menu > View > Show Console`.

**Comment by gerardroche** [comment]
You should get something like:

```
chr evt: B (0x42)
chr evt: u (0x75)
chr evt: i (0x69)
chr evt: l (0x6c)
chr evt: d (0x64)
chr evt:   (0x20)
chr evt: v (0x76)
chr evt: a (0x61)
chr evt: r (0x72)
chr evt: i (0x69)
chr evt: a (0x61)
chr evt: n (0x6e)
chr evt: t (0x74)
chr evt: = (0x3d)
chr evt: R (0x52)
chr evt: u (0x75)
chr evt: n (0x6e)
NeoVintageous: DEBUG   [ex_cmds.py:1601] do ex cmdline >>>:Build variant=Run<<<
NeoVintageous: DEBUG   [ex_cmds.py:1615] execute user ex command: {'cmd': 'build', 'args': {'variant': 'Run'}}


via `<leader>r`

chr evt: , (0x2c)
command: _nv_feed_key {"key": ","}
NeoVintageous: INFO    [commands.py:423] key evt: , repeat_count=None do_eval=True check_user_mappings=True
NeoVintageous: DEBUG   [commands.py:455] mode: mode_normal
NeoVintageous: DEBUG   [state.py:252] sequence >>>,<<<
NeoVintageous: DEBUG   [state.py:265] partial sequence >>>,<<<
NeoVintageous: DEBUG   [commands.py:500] found incomplete mapping
NeoVintageous: DEBUG   [commands.py:439] key evt took 0.0053s (key=, repeat_count=None do_eval=True check_user_mappings=True)
chr evt: r (0x72)
command: _nv_feed_key {"key": "r"}
NeoVintageous: INFO    [commands.py:423] key evt: r repeat_count=None do_eval=True check_user_mappings=True
NeoVintageous: DEBUG   [commands.py:455] mode: mode_normal
NeoVintageous: DEBUG   [state.py:252] sequence >>>,r<<<
NeoVintageous: DEBUG   [state.py:265] partial sequence >>>,r<<<
NeoVintageous: DEBUG   [mappings.py:204] resolved None None or ,r -> ,r <NeoVintageous.nv.mappings.Mapping object at 0x7f60dd76ab90>
NeoVintageous: DEBUG   [commands.py:505] command <NeoVintageous.nv.mappings.Mapping object at 0x7f60dd76ab90> (<class 'NeoVintageous.nv.mappings.Mapping'>, <class 'object'>)
NeoVintageous: DEBUG   [commands.py:516] found user mapping...
NeoVintageous: DEBUG   [commands.py:519] evaluating user mapping (mode=mode_normal)...
NeoVintageous: DEBUG   [state.py:252] sequence >>><<<
NeoVintageous: DEBUG   [state.py:265] partial sequence >>><<<
NeoVintageous: INFO    [commands.py:532] user mapping ,r -> :Build variant=Run<CR>
NeoVintageous: DEBUG   [ex_cmds.py:1674] do ex user cmdline >>>:Build variant=Run<CR><<<
NeoVintageous: DEBUG   [ex_cmds.py:1601] do ex cmdline >>>:Build variant=Run<<<
NeoVintageous: DEBUG   [ex_cmds.py:1615] execute user ex command: {'cmd': 'build', 'args': {'variant': 'Run'}}
NeoVintageous: DEBUG   [commands.py:439] key evt took 0.0204s (key=r repeat_count=None do_eval=True check_user_mappings=True)

```

**Comment by darkermatter** [comment]
Hi @gerardroche ...
I installed Sublime Text on another machine with just NV installed and it worked so I wiped my config (it was full of cobwebs anyway) and it works on my other machines now. Maybe there was some configuration from an older VIM plugin causing problems?

Anyway, thanks so much and I'm sorry for wasting your time.

**Comment by gerardroche** [comment]
Yes, there was probably a rogue configuration skewing expectations. No worries. I'm happy it's resolved for you.
