### ISSUE TITLE
Support granular vim vs sublime CTRL shortcuts

### ISSUE THREAD

**Issue by lukedegruchy** [NeoVintageous/NeoVintageous#470]
### Description

Currently, Neovintageous supports only binding all CTRL keyboard shortcuts to either Vim or Sublime bindings via "vintageous_use_ctrl_keys": true/false.  It's all or nothing.  I set this to true on macOS because almost all Sublime shortcuts use Command, but I set it to false on Linux because too many useful Sublime shortcuts would be nullified and it's too much effort to remap them all to other combinations.  In fact, this would be even trickier given the list of all possible CTRL shortcuts in Vim

On the other hand, IntelliJ's IDEAVim plugin supports choosing between vim and IntelliJ for a given vim keyboard shortcut.   So, for example, I've bound CTRL-T to "Run" as opposed to "Jump back in tag stack.  However, I've bound CTRL-R to Vim's "Redo".

Less ambitious behaviour is implemented by Eclipse's vrapper.   vrapper will only take over a shortcut that Eclipse hasn't configured.  So, for example, CTRL-D deletes a line by default.  If a user unbinds CTRL-D, then vim's pagedown behaviour for that shortcut takes over.

This feature request is to implement either IDEAVim or vrapper's Vim shortcut behaviour.  IMHO, the current all or nothing model is too blunt of an instrument for configuring CTRL key behaviour.

**Comment by gerardroche** [comment]
I'm not sure how best to resolve this issue. I'm reluctant to add configurable settings for every CTRL key.

There are currently two options to remapping:

1. Use built in keymaps:

```
	{ "keys": ["ctrl+delete"], "command": "delete_word", "args": { "forward": true } },
```

2. Use your rc file:

```
nnoremap <C-d> dw
```

The difference is that 2 deletes the word into the delete register, whereas 1 uses the builtin sublime delete word which is not Vim aware.

You can also map to builtin Sublime commands:

```
nnoremap <C-f> :ShowOverlay overlay=goto text=@<CR>
```

I've added a wip PR possibly implementation of mapping presets, where neo would provide out-of-the-box mapping presets. A few common presets might alleviate the issue of needing to configure common ctrl key setups. You can still override them in your rc file too.

**Comment by gerardroche** [comment]
I've been testing a few different ways to support granular control of keys. There is a WIP here:

https://github.com/NeoVintageous/NeoVintageous/pull/566

This potentially allows control of **all** keys, not just the ctrl keys, though the wip currently only supports control of the ctrl keys.

Let me know what you think, does this look like something that you would use? What are your suggestions, questions?

**Comment by lukedegruchy** [comment]
> Does this look like something that you would use? Let me know what you think. What are your suggestions, questions?

If I understand correctly, all CTRL combinations would default to vim commands unless I explicitly opt out.  So, for example, if I opt out of CTRL-S, then that key combination will map to Save in Sublime.

How difficult would this be to flip around?  Meaning, instead of opting *out* of vim commands, I would opt *in* to vim commands.   So, for example, if I want CTRL-D to map to pagedown, then I would add this to the list of shortcuts.  Otherwise, the CTRL shortcuts map to Sublime commands.

**Comment by gerardroche** [comment]
> If I understand correctly, all CTRL combinations would default to vim commands unless I explicitly opt out. So, for example, if I opt out of CTRL-S, then that key combination will map to Save in Sublime.

Yes. For example I'm currently using it to ignore the `ctrl+c` so that it defaults to Sublime's copy command:

```
	"vintageous_ignore_keys": "ctrl+c",
	"vintageous_use_ctrl_keys": true,
```

Previously I had to redefine it as a key binding:

```
{ "keys": ["ctrl+c"], "command": "copy" },
```

> How difficult would this be to flip around? Meaning, instead of opting out of vim commands, I would opt in to vim commands. So, for example, if I want CTRL-D to map to pagedown, then I would add this to the list of shortcuts. Otherwise, the CTRL shortcuts map to Sublime commands.

It's certainly possible, but I think the behaviour would need to be configurable because for example I use all ctrl keys except `ctrl+c` and it would mean I'd have to create a long list of all ctrl keys just to enable them or by default the list would be populated with all ctrl keys:

```
"vintageous_whitelist_keys": "ctrl+a,ctrl+b,ctrl+c,ctrl+d,ctrl+e,ctrl+f,ctrl+g,ctrl+h,ctrl+i,ctrl+j,ctrl+k,ctrl+l,ctrl+m,ctrl+n,ctrl+o,ctrl+p,ctrl+r,ctrl+q,ctrl+r,ctrl+s,ctrl+t,ctrl+u,ctrl+v,ctrl+w,ctrl+x,ctrl+y,ctrl+z,ctrl+ç,ctrl+ñ,ctrl k,ctrl+[,ctrl+],ctrl+."
```

The inverse is of course true for people who only want a few ctrl keys. The difference I think is that Vim by default has ctrl keys enabled. 

In theory it could either/or i.e. define a blacklist or define a whitelist. If you define a blacklist then all keys are enabled except the ones in the blacklist, if you define a whitelist, then all keys are disabled except the ones in the whitelist. By default all keys would need to be enabled.

**Blacklist**

If a setting `vintageous_blanklist_keys` is defined then all keys are **enabled** except what is the blacklist:

```
"vintageous_blanklist_keys": "ctrl+c,ctrl+l"
```

**Whitelist**

If a setting `vintageous_whitelist_keys` is defined then all keys are **disabled** except what is the whitelist:

```
"vintageous_whitelist_keys": "ctrl+c,ctrl+"
```

If the feature is extended to allow configuring **all** keys, then the whitelist approach becomes much less useful because the list of keys would be too long.

What about other ctrl keys too e.g. `shift+ctrl+x`, `ctrl+f{a-z}`, `ctrl+shift+f{a-z}`? It's a lot of keys. I think it depends on what the majority use-case is, one group of users is going to end up needing to define either a whitelist or a blacklist. I suspect that people will generally only ignore a limited set of keys.

**Comment by lukedegruchy** [comment]
> What about other ctrl keys too e.g. shift+ctrl+x, ctrl+f{a-z}, ctrl+shift+f{a-z}? 

Hadn't considered that.  Under your proposal, what happens when I invoke a shortcut like SHIFT-CTRL-N (Sublime New Window) if I've set _vintageous_use_ctrl_keys_ to true?

**Comment by gerardroche** [comment]
`SHIFT-CTRL-N` is controlled by the *vintageous_use_ctrl_keys* setting meaning is it's set to true the keymap is enabled. 

The *vintageous_use_ctrl_keys* controls any keymap that contains the `ctrl` key. Though I'm discovering some oversights e.g. ctrl+digits  like `ctrl+1`, `ctrl+2`, etc and the ctrl+function-keys are currently not controlled by the setting, but that can be considered a bug/oversight #567.

There is also the **vintageous_use_super_keys** setting that controls any key using `super` e.g. `super+d`, `shift+super+d` (`super+D`).

Those settings are to just make it a little easier for people to enable or disable ctrl and super keys wholesale. I think these settings will apply regardless of blacklists or whitelists.

**Comment by lukedegruchy** [comment]
One thing I'll mention is that VS Code Vim uses something in between a whilelist and a blacklist.

https://github.com/VSCodeVim/Vim

It has two settings:

```
vim.useCtrlKeys | Enable Vim ctrl keys overriding common VS Code operations such as copy, paste, find, etc. 
vim.handleKeys | Delegate configured keys to be handled by VS Code instead of by the VSCodeVim extension. Any key in keybindings section of the package.json that has a vim.use<C-...> in the when argument can be delegated back to VS Code by setting "<C-...>": false. Example: to use ctrl+f for find (native VS Code behaviour): "vim.handleKeys": { "<C-f>": false }
```
In my settings.json, I have the following mapped:

* Nothing specified for vim.useCtrlKeys 

```
        "vim.handleKeys": {
            "<C-a>": false,
            "<C-c>": false,
            "<C-e>": false,
            "<C-f>": false,
            "<C-h>": false,
            "<C-n>": false,
            "<C-o>": false,
            "<C-p>": false,
            "<C-t>": false,
            "<C-v>": false
        },
```
So at this point I don't think whether it's a whitelist or blacklist matters to me.  I could use as easily do this:

```
vim.handleKeys: {
     "<C-d>": true,
    "<C-r>": true,
    <C-u>": true
}
```

So bottom line is it doesn't make a difference to me.  I'll happily take whichever of the three approaches (blacklist, whilelist, combination of the two) that's easiest to implement.  That will be a massive improvement over the status quo of all or nothing.

**Comment by gerardroche** [comment]
You're right, a solution that satisfies the 80% use case is better than nothing. 

I've implemented basic support (currently in the develop branch) that allows delegating the handling of keys back to ST.  For example, the following will delegate the listed keys back to ST:

```
    "vintageous_use_ctrl_keys": true,
    "vintageous_handle_keys": {
        "<C-h>": false,
        "<C-v>": false,
        "<C-c>": false,
        "<C-f>": false,
        "<C-d>": false,
    }
```

There is an exhaustive list of keys that can be disabled posted below.

Will this resolve the 80% use case?

## List of keys that can be delegated back to ST

```
<M-bs>
<M-del>
<M-down>
<M-end>
<M-cr>
<M-escape>
<M-home>
<M-left>
<M-pagedown>
<M-pageup>
<M-right>
<M-space>
<M-tab>
<M-up>
<M-#>
<M-'>
<M-,>
<M-->
<M-.>
<M-/>
<M-0>
<M-1>
<M-2>
<M-3>
<M-4>
<M-5>
<M-6>
<M-7>
<M-8>
<M-9>
<M-;>
<M-=>
<M-[>
<M-bslash>
<M-]>
<M-`>
<M-a>
<M-b>
<M-c>
<M-d>
<M-e>
<M-f>
<M-g>
<M-h>
<M-i>
<M-j>
<M-k>
<M-l>
<M-m>
<M-n>
<M-o>
<M-p>
<M-q>
<M-r>
<M-s>
<M-t>
<M-u>
<M-v>
<M-w>
<M-x>
<M-y>
<M-z>
<M-A>
<M-B>
<M-C>
<M-D>
<M-E>
<M-F>
<M-G>
<M-H>
<M-I>
<M-J>
<M-K>
<M-L>
<M-M>
<M-N>
<M-O>
<M-P>
<M-Q>
<M-R>
<M-S>
<M-T>
<M-U>
<M-V>
<M-W>
<M-X>
<M-Y>
<M-Z>
<C-[>
<C-c>
<C-l>
<C-w>
<C-x>
<C-bs>
<C-del>
<C-down>
<C-cr>
<C-home>
<C-left>
<C-pagedown>
<C-pageup>
<C-right>
<C-space>
<C-up>
<C-.>
<C-0>
<C-1>
<C-2>
<C-3>
<C-4>
<C-5>
<C-6>
<C-7>
<C-8>
<C-9>
<C-[>
<C-]>
<C-a>
<C-b>
<C-c>
<C-d>
<C-e>
<C-f>
<C-g>
<C-h>
<C-i>
<C-j>
<C-k>
<C-l>
<C-m>
<C-n>
<C-o>
<C-p>
<C-q>
<C-r>
<C-s>
<C-t>
<C-u>
<C-v>
<C-w>
<C-x>
<C-y>
<C-z>
<C-ç>
<C-ñ>
<C-M-p>
<S-down>
<S-cr>
<S-left>
<S-right>
<S-space>
<S-up>
<C-S-cr>
<C-P>
<C-S-.>
<C-A>
<C-B>
<C-C>
<C-D>
<C-E>
<C-F>
<C-G>
<C-H>
<C-I>
<C-J>
<C-K>
<C-L>
<C-M>
<C-N>
<C-O>
<C-P>
<C-Q>
<C-R>
<C-S>
<C-T>
<C-U>
<C-V>
<C-W>
<C-X>
<C-Y>
<C-Z>
<C-Ç>
<C-Ñ>
<D-bs>
<D-del>
<D-down>
<D-cr>
<D-home>
<D-left>
<D-pagedown>
<D-pageup>
<D-right>
<D-space>
<D-up>
<D-.>
<D-[>
<D-]>
<D-a>
<D-b>
<D-c>
<D-d>
<D-e>
<D-f>
<D-g>
<D-h>
<D-i>
<D-j>
<D-k>
<D-l>
<D-m>
<D-n>
<D-o>
<D-p>
<D-q>
<D-r>
<D-s>
<D-t>
<D-u>
<D-v>
<D-w>
<D-x>
<D-y>
<D-z>
<D-S-.>
<D-A>
<D-B>
<D-C>
<D-D>
<D-E>
<D-F>
<D-G>
<D-H>
<D-I>
<D-J>
<D-K>
<D-L>
<D-M>
<D-N>
<D-O>
<D-P>
<D-Q>
<D-R>
<D-S>
<D-T>
<D-U>
<D-V>
<D-W>
<D-X>
<D-Y>
<D-Z>
<f1>
<f2>
<f3>
<f4>
<f5>
<f6>
<f7>
<f8>
<f9>
<f10>
<f11>
<f12>
<f13>
<f14>
<f15>
<f16>
<f17>
<f18>
<f19>
<f20>
<M-f1>
<M-f2>
<M-f3>
<M-f4>
<M-f5>
<M-f6>
<M-f7>
<M-f8>
<M-f9>
<M-f10>
<M-f11>
<M-f12>
<M-f13>
<M-f14>
<M-f15>
<M-f16>
<M-f17>
<M-f18>
<M-f19>
<M-f20>
<C-f1>
<C-f2>
<C-f3>
<C-f4>
<C-f5>
<C-f6>
<C-f7>
<C-f8>
<C-f9>
<C-f10>
<C-f11>
<C-f12>
<C-f13>
<C-f14>
<C-f15>
<C-f16>
<C-f17>
<C-f18>
<C-f19>
<C-f20>
<S-f1>
<S-f2>
<S-f3>
<S-f4>
<S-f5>
<S-f6>
<S-f7>
<S-f8>
<S-f9>
<S-f10>
<S-f11>
<S-f12>
<S-f13>
<S-f14>
<S-f15>
<S-f16>
<S-f17>
<S-f18>
<S-f19>
<S-f20>
<C-S-f1>
<C-S-f2>
<C-S-f3>
<C-S-f4>
<C-S-f5>
<C-S-f6>
<C-S-f7>
<C-S-f8>
<C-S-f9>
<C-S-f10>
<C-S-f11>
<C-S-f12>
<C-S-f13>
<C-S-f14>
<C-S-f15>
<C-S-f16>
<C-S-f17>
<C-S-f18>
<C-S-f19>
<C-S-f20>
<k0>
<k1>
<k2>
<k3>
<k4>
<k5>
<k6>
<k7>
<k8>
<k9>
<kdivide>
<kenter>
<kminus>
<kmultiply>
<kperiod>
<kplus>
```

**Comment by gerardroche** [comment]
I added the ability to disable keys (delegate them to ST) by specific modes.

Doc:


Delegate configured keys to be handled by Sublime Text. 

For example to use ctrl+f for find (native ST behaviour):

    "vintageous_handle_keys": {
        "<C-f>": false
    }

Keys can be delegated by mode too e.g. i_<C-w>, v_<C-w>. The following
will only delegate <C-w> back to ST when in insert or visual mode:

    "vintageous_handle_keys": {
        "i_<C-w>": false
        "v_<C-w>": false
    }

The valid mode prefixes are:

    n_ - Normal
    i_ - Insert
    v_ - Visual
    V_ - Visual line
    b_ - Visual block
    s_ - Select

No prefix implies all modes.

Any keybinding defined in the default keymap file that has
a "nv_handle_key" context constraint can be configured to delegate
back to ST.
See https://github.com/NeoVintageous/NeoVintageous/blob/master/Default.sublime-keymap

**Comment by gerardroche** [comment]
I just released 1.23.0 with new granular control of keys feature.

Blog post here: https://blog.gerardroche.com/2020/12/12/neovintageous-1.23.0/

Let me know if this implementation works for you.

**Comment by lukedegruchy** [comment]
@gerardroche Thank you!

I've been playing around with it this morning and it works great!

As an aside, the ctrl-w split window functionality is also a great new feature I'll be using a lot.

	"vintageous_handle_keys": {
	    "<C-a>": false,
	    "<C-b>": false,
	    "<C-c>": false,
	    "<C-e>": false,
	    "<C-f>": false,
	    "<C-g>": false,
	    "<C-h>": false,
	    "<C-i>": false,
	    "<C-j>": false,
	    "<C-l>": false,
	    "<C-m>": false,
	    "<C-n>": false,
	    "<C-o>": false,
	    "<C-p>": false,
	    "<C-s>": false,
	    "<C-t>": false,
	    "<C-u>": false,
	    "<C-v>": false,
	    "<C-x>": false,
	    "<C-y>": false,
	    "<C-z>": false,
	},

**Comment by gerardroche** [comment]
In ST, keys case sensitive. So you need `<C-N>` instead of `<C-S-n>`. In Vim, keys are not case sensitive, which means you can't map to both CTRL-n and CTRL-N because they are the same. In ST, you can map to both CTRL-n and CTRL-N. There is a small note in the docs, but it needs to be better explained: https://neovintageous.github.io/reference/key-mapping#mapping-case-sensitivity

**Comment by sricks** [comment]
> EDIT2: Also wondering about e.g. Alt+X, which is useful for this package: https://packagecontrol.io/packages/MarkdownEditing
>
> Alt+X to complete a task item works in insert mode, but not in command mode.

Figured out solution today, there are two possible solutions:

1. `set winaltkeys=yes` in neovintageousrc OR `"vintageous_winaltkeys": "yes"` in sublime settings
2. Use `vintageous_handle_keys`, but `Alt` is synonymous with character `M` eg meta. So if you want to use `Alt+X` hotkey, add `"<M-x>": false` instead of `A-x`

**Comment by gerardroche** [comment]
@sricks The keys work in insert mode because NeoVintageous doesn't implement very many insert mode commands, so insert mode keys mostly default to the default Sublime Text key bindings.

The `'winaltkeys'` option is quirky feature. That will do the job in some cases: https://neovintageous.github.io/reference/options#winaltkeys-wak

Otherwise the `vintageous_handle_keys` is usually the best approach. It's flexible enough to disable keys in all modes or specific modes. Disabled keys will fallback to Sublime Text. https://neovintageous.github.io/reference/settings#vintageous-handle-keys

The `<M-` meta key for `alt` can be confusing. Perhaps we should note it in the docs: https://neovintageous.github.io/reference/key-mapping

See also https://blog.gerardroche.com/2022/09/22/neovintageous-key-handler/

**Comment by momadacoding** [comment]
@gerardroche vintageous_handle_keys does not work, use this rc file below

![Image](https://github.com/user-attachments/assets/a4288876-e8f9-473c-9316-e0d2ba1eea82)

**Comment by gerardroche** [comment]
@momadacoding Settings and rc file are different. Settings go in sublime text settings. 

Command Palette → Preferences: NeoVintageous Settings

https://neovintageous.github.io/reference/settings
https://neovintageous.github.io/reference/neovintageousrc
