### ISSUE TITLE
Default mapleader does not appear to be working

### ISSUE THREAD

**Issue by davea1** [NeoVintageous/NeoVintageous#501]
### Description
Default mapleader does not appear to be working.

NeoVintageous documentation states: 

> If "mapleader" is not set or empty, a backslash is used instead.

### Steps to Reproduce
Add the following to .neovintageous file:
`noremap <leader>s :TrimTrailingWhiteSpace<CR>`

Test with:
`\s`

### Expected behaviour
Command should be executed removing trailing whitespace.

### Actual behaviour
Command does not execute.

It only appears to work if you explicitly define mapleader by also adding the following to your .neovintageous file:
`let mapleader=\`

### Versions
1.11.2
OS: Windows 10

**Comment by gerardroche** [comment]
This is a regression since #429. A quick fix is to specify it as the special key:

```
let mapleader=<bslash>
```

I'll have a fix shortly.

**Comment by davea1** [comment]
Works great. Thanks!
