### ISSUE TITLE
e in visual mode doesn't work

### ISSUE THREAD

**Issue by nlack** [NeoVintageous/NeoVintageous#504]
### Description
When i crossed the visual mode starting point backwards and press `e` again to go forward, the first jump works to the next space but the next `e` press doesn't go past the next space. Pressing `l` to go forward works or pressing `E`.

![test](https://user-images.githubusercontent.com/5786288/55908135-edab4980-5bd8-11e9-84b3-a768ab3e2afb.gif)

Is it related with https://github.com/NeoVintageous/NeoVintageous/issues/18 ?
### Versions
startup, version: 3207 linux x64 channel: dev
NeoVintageous in package manager list v1.11.3

**Comment by gerardroche** [comment]
Thanks. This is a regression from the fix in #451 "{Visual}e in reverse selection should move to end of word".

It will be fixed in 1.12.0.
