### ISSUE TITLE
Home/end key behavior differs in Insert mode vs normal mode on MacOS

### ISSUE THREAD

**Issue by tmepple** [NeoVintageous/NeoVintageous#507]
### Description

Thanks for this great plugin!

With NeoVintageous on ST3 (3206) on MacOS the Home/End keys behave as you'd expect in Normal mode... moving the cursor to the beginning or end of line.  In Insert mode, Home/End scrolls to the beginning or end of the file without moving the cursor.

I'm not sure why the behavior is different depending on mode as this doesn't happen in vim.

I thought about adding a remap command in my `.neovintageousrc` file mapping Home and End to the Sublime commands `moveTo bol` and `moveTo eol` but I don't think `inoremap` is supported by NeoVintageous so couldn't figure out how to have it affect insert mode.

I realize it's recommended to exit insert mode and move the cursor easily using the vim-standard keys `0` and `$` but I'd like to be able to do it without leaving insert mode also.

### Versions

version: 3206 osx x64 channel: dev

**Comment by gerardroche** [comment]
NeoVintageous currently doesn't support Insert mode like VIm. All commands run in Insert mode are built-in Sublime commands, which is why those keys work differently in Insert vs Normal/Visual/etc. There's no roadmap for implementing Insert mode like Vim.

**Comment by tmepple** [comment]
Thanks for getting back to me... I didn't realize insert mode basically works like normal Sublime behavior, thus no `inoremap`.  It makes sense I can just modify the standard keybindings file to get the handling I wanted which works.
