### ISSUE TITLE
Need help with colon command ":/{find your text here}"

### ISSUE THREAD

**Issue by JW9506** [NeoVintageous/NeoVintageous#529]
![Kapture 2019-05-04 at 21 34 15](https://user-images.githubusercontent.com/34848995/57186856-6a69d480-6eb4-11e9-947a-464fdfa0efc2.gif)

I am trying to use `:/apple` to highlight apple and hit 'n' to find the next one. But it says "Unclosed search pattern apple"

How do I work around this?

**Comment by gerardroche** [comment]
If you're just looking to do a search try pressing just `/searchterm` i.e. a slash instead of colon. You can also do a reverse search via `?searchterm`.

It's should still work as `:/searchterm` and `:/searchterm/` too, so that's a bug/enhancement.

**Comment by gerardroche** [comment]
Actually, `:/term` is slightly different than `/term`.

* Using the cmdline line (`:/term`) version moves the cursor to the first non-blank of the line where the next match is.
* Using `/term` moves the cursor to the first character of the next match.

**Comment by JW9506** [comment]
> Actually, `:/term` is slightly different than `/term`.
> 
> * Using the cmdline line (`:/term`) version moves the cursor to the first non-blank of the line where the next match is.
> * Using `/term` moves the cursor to the first character of the next match.
> 
> The cmdline version `:/term/` (with the closing slash) kind of works, but it's a bit buggy.

Thanks. I was only confused because `:/term` works in normal vim editor. This issue can be closed now.
