### ISSUE TITLE
c does not work with multiple selections

### ISSUE THREAD

**Issue by xtian** [NeoVintageous/NeoVintageous#530]
### Description

I can't change selected text in a multi-select using <kbd>c</kbd> anymore. I think this stopped working in the past few months and still doesn't work using latest master.

### Steps to Reproduce

1. Open a new file and enter some text
1. Create a multi-selection using <kbd>gh</kbd> 
1. Use <kbd>c</kbd> to change selected text

### Expected behaviour

Selected text should be deleted and editor should enter insert mode.

### Actual behaviour

Nothing happens and no errors are printed in the debug console.

### Versions

`startup, version: 3207 osx x64 channel: stable`

### Additional Information

<kbd>c</kbd> fails to have any effect regardless of whether the multi-select contains just one selection or multiple.

<details>
<summary>Debug console:</summary>

```
chr evt: o (0x6f)
command: _nv_feed_key {"key": "o"}
key evt: backspace
command: left_delete
chr evt: a (0x61)
chr evt: s (0x73)
chr evt: d (0x64)
chr evt: f (0x66)
key evt: control+c
command: _enter_normal_mode {"mode": "mode_insert"}
chr evt: b (0x62)
command: _nv_feed_key {"key": "b"}
chr evt: g (0x67)
command: _nv_feed_key {"key": "g"}
chr evt: h (0x68)
command: _nv_feed_key {"key": "h"}
chr evt: c (0x63)
command: _nv_feed_key {"key": "c"}
```

</details>

**Comment by gerardroche** [comment]
Relates to https://github.com/NeoVintageous/NeoVintageous/issues/251

**Comment by xtian** [comment]
@gerardroche Thank you!
