### ISSUE TITLE
Use normal mode when other plugins selects text.

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#54]
<a href="https://github.com/haakenlid"><img src="https://avatars0.githubusercontent.com/u/1686266?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [haakenlid](https://github.com/haakenlid)**
_Sunday Jun 08, 2014 at 12:49 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/632_

----

Sublime Text's built-in "Goto Symbol" and Sublimelint's "Goto Lint Error" will select some text and automatically make Vintageous enter visual mode. I find this very annoying and counter-intuitive, because I want to stay in normal mode unless I explicitly need to use visual mode.

Is there some way to automatically exit visual mode when some other plugin selects text on my behalf? Of course I would like to still be able to use the mouse to select text and enter visual mode.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Jun 28, 2014 at 16:51 GMT_

----

Vintageous can only easily control the selections of commands it knows about. I will try to make the Goto Symbol command to leave the user in normal mode, but Sublimelint's commands are basically free to do whatever they want.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Saturday Jun 28, 2014 at 16:55 GMT_

----

One dumb way of solving this now would be by intercepting the relevant Sublimelint's command via `.on_text_command()` and reset the selection somehow.

**Comment by gerardroche** [comment]
@haakenlid In NeoVintageous (this plugin, a fork of the discontinued Vintageous plugin), there are built in goto error commands included with the out-of-the box plugin Unimpaired `[l` and `]l`. There is also GitGutter support with `[c` and `]c`. For other commands, you can create custom wrapper commands, or mappings in your vintageousrc file e.g. `nnoremap <leader>m :GotoSymbolInProject<CR>`. See the document via the ex command `:h neovintageous`. Also the release announcments for [1.4.0](http://blog.gerardroche.com/2017/11/01/neovintageous-1.4.0-released/) and [1.5.0](http://blog.gerardroche.com/2018/02/21/neovintageous-1.5.0-released/).

**Comment by dvcrn** [comment]
Is the only way to get around this issue to rebind the default keybindings such as `CMD+R` with the NeoVintageous version?

**Comment by gerardroche** [comment]
@dvcrn I'm not sure I understand the issue. I think `cmd+r` is like `ctrl+r` which in vim means **undo**, at least if you have the ctrl keys enabled. If you want `ctrl+r` to open the symbol finder, default sublime text keybinding, then yes you'd need to rebind it. There's an open issue about granular control of keys: https://github.com/NeoVintageous/NeoVintageous/issues/470.

**Comment by dvcrn** [comment]
Ah sorry I didn't explain correctly. I meant the problem @haakenlid mentioned is that when you use CMD+R to `Jump To Symbol`, NeoVintageous hops into visual mode so `j` / `k` just expands the selection. 

You mentioned we can use the NeoVintageous variants like `:GotoSymbolInProject` which correctly jumps to a symbol and then enters normal mode. I like the built-in CMD+R / CMD+Shift+R Goto Symbol keybindings but want it to enter normal mode after jumping

**Comment by dvcrn** [comment]
I started embracing the vintageous style of doing things but still have issues with this. As written above, when I use CMD+R (aka `Goto Symbol`) or the vim variant `ShowOverlay overlay=goto text=@`, then navigate to any symbol, NeoVintageous stays in select mode. 

![out](https://user-images.githubusercontent.com/688326/67554489-7d19e380-f74a-11e9-9ba0-380190ade6e2.gif)

This holds true for most actions that jump to something. Any way to tell it to not stay in select mode after the jump?

**Comment by gerardroche** [comment]
@dvcrn The issue is that the Sublime Text command **goto symbol** is visually selecting the symbol after the jump. The **goto symbol in project** works properly because it doesn't visually select anything after the jump. 

You can test it by disabling Neovintageous and trying both commands:

![goto](https://user-images.githubusercontent.com/44148/67770334-164c4100-fa4e-11e9-8b88-d96930803acb.png)

One visually selects the symbol, the other doesn't. 

There's no way good way for neovintageous to work around this. I've opened an Sublime Text issue requesting a command option to disable the visual selection: https://github.com/SublimeTextIssues/Core/issues/3032

**Comment by dvcrn** [comment]
Ah I see! Thanks for clarifying

**Comment by gerardroche** [comment]
Also see open Vintage issue: https://github.com/sublimehq/Vintage/issues/147

**Comment by gerardroche** [comment]
Closing and moving the issue to the [known issues](https://github.com/NeoVintageous/NeoVintageous/issues/404) section of the roadmap.
