### ISSUE TITLE
"gqq" command does not exist

### ISSUE THREAD

**Issue by taylorthurlow** [NeoVintageous/NeoVintageous#580]
### Description
Using the command `gqq` in normal mode does not perform a line-wrap on the currently selected line.

### Steps to Reproduce
Move your cursor onto a line containing a code comment which is longer than 80 characters. While in normal mode, press `gqq`.

### Expected behaviour
The current line is wrapped at 80 characters.

### Actual behaviour
The command is ignored (the line highlight blinks rapidly). The line is not formatted. No errors are printed to the console.

### Additional Information
I'm currently able to get around the issue by creating the following binding to manually engage visual-line mode and wrap the selection instead:

~~~
nnoremap gqq Vgq
~~~

**Comment by gerardroche** [comment]
Note: discovered a sublime text bug while implementation this: https://github.com/SublimeTextIssues/Core/issues/2867

**Comment by gerardroche** [comment]
Added for the next minor release. I also added `gqgq` which is a alias of `gqq`.

**Comment by gerardroche** [comment]
Also, you can use a count too e.g `3gqq`

**Comment by taylorthurlow** [comment]
Great stuff, thanks!
