### ISSUE TITLE
Move command (:m) has inconsistent behavior with cursor position

### ISSUE THREAD

**Issue by taylorthurlow** [NeoVintageous/NeoVintageous#583]
### Description
When using the move command (`:m`), I expect that the current line is moved some distance. For example, if I use the following command:

~~~
:m .+1
~~~

I expect my current line to be essentially swapped with the line below it, *and also that my currently selected line moves with it*. Sometimes it does not happen, I cannot figure out why it happens.

### Steps to Reproduce
Open the following code in a new window. I'll be using Ruby for the example.

~~~ruby
require "simplecov"
unless ENV["NO_COVERAGE"]
~~~

Position your cursor on the first line, and execute the command `:m .+1`.

### Expected behaviour
The code should now read:

~~~ruby
unless ENV["NO_COVERAGE"]
require "simplecov"
~~~

**And**, the current line should be the second line (the `require` statement).

### Actual behaviour
The current line stays as the first line, not moving with the moved line.

### Versions
Sublime Text v3207
Neovintageous v1.16.1
macOS 10.13.6

**Comment by taylorthurlow** [comment]
I hope you don't mind the barrage of issues I'm opening! This package is so far and away better than the alternatives for other IDE's that I've tried that I think it'll be the thing that keeps me using Sublime Text.

**Comment by taylorthurlow** [comment]
Okay, I've now encountered this issue with lines which aren't comments. Here's the pair of lines I just had a problem with:

~~~ruby
require "simplecov"
unless ENV["NO_COVERAGE"]
~~~

Same thing moving the first line down past the second.

**Comment by gerardroche** [comment]
Thanks.

> I hope you don't mind the barrage of issues I'm opening! 

I don't mind at all. It's good to be aware of the issues.
