### ISSUE TITLE
"gq" formatting adds extra character

### ISSUE THREAD

**Issue by taylorthurlow** [NeoVintageous/NeoVintageous#592]
### Description
When formatting a line with `gqq` (or `gq` in visual mode), sometimes an extra character is added.

### Steps to Reproduce
Start with the following Ruby code:

~~~ruby
def cart_service_params
  params.require(:cart_service).permit(
    :cart_product_id, :option_id, :option_name, :service_id, :service_name, :service_price, :hidden
  )
end
~~~

Put your cursor on the middle line, the one starting with `:cart_product_id`, and press `gqq`. 

### Expected behaviour
The code reads:

~~~ruby
def cart_service_params
  params.require(:cart_service).permit(
    :cart_product_id, :option_id, :option_name, :service_id, :service_name,
    :service_price, :hidden
  )
end
~~~

### Actual behaviour
The code reads:

~~~ruby
def cart_service_params
  params.require(:cart_service).permit(
    :cart_product_id, :option_id, :option_name, :service_id, :service_name,
    ::service_price, :hidden
  )
end
~~~

Notice the extra `:` before `:service_price`.

### Versions
NeoVintageous `v1.16.2`
Sublime Text Build `3207`
macOS `10.13.6`

**Comment by gerardroche** [comment]
This is actually a bug in an Sublime Text internal command: https://github.com/SublimeTextIssues/Core/issues/2873. I've opened a ticket for it, so closing it here. There are other issues related to that internals command too e.g. https://github.com/SublimeTextIssues/Core/issues/2867
