### ISSUE TITLE
action di(  ignores the brackets indention

### ISSUE THREAD

**Issue by asfktz** [NeoVintageous/NeoVintageous#597]
Hi there 😀
First, thank you so much for your amazing work!

I notices that the action `dib` / `di(`  ignores the brackets indention:

### Before `di(`:
![Screen Shot 2019-06-19 at 0 40 24](https://user-images.githubusercontent.com/199747/59724541-e769c700-9232-11e9-8bb4-3902c78a51e2.png)

### After `di(`:
![Screen Shot 2019-06-19 at 0 40 28](https://user-images.githubusercontent.com/199747/59724545-e89af400-9232-11e9-9c0c-a103171fbe74.png)

The bug exists for a while now, it started at version 1.6.0 (older version works fines)
Also, It relates to this commit https://github.com/NeoVintageous/NeoVintageous/commit/65ae2b0fbadc23edb37a6f7d7af9314a20da9b26
When I revert this commit, the issue resolved (but I guess it breaks something else.. 🙃)

Here's a working fork with this commit reverted: https://github.com/asfktz/NeoVintageous/commits/fix-vib

**Comment by asfktz** [comment]
## Another case
also resolved by reverting the commit <br>

### Before `di{`
![Screen Shot 2019-06-19 at 2 27 04](https://user-images.githubusercontent.com/199747/59726327-da9ca180-9239-11e9-910f-3ad0e720bf2c.png)
### After `di{`
![Screen Shot 2019-06-19 at 2 27 13](https://user-images.githubusercontent.com/199747/59726332-dc666500-9239-11e9-9322-b6ac88846447.png)

**Comment by gerardroche** [comment]
Thanks. I fixed lots of related issues for example https://github.com/NeoVintageous/NeoVintageous/issues/598. There are no doubt some more issues. Please open issues for any unexpected behaviours. Yanking, cutting, deleting, and pasting text objects should be much better.

**Comment by asfktz** [comment]
Wow, you are fast.
Thanks @gerardroche, I will let you know if I find any (:

Should I work with branch `develop` to see the changes?

**Comment by gerardroche** [comment]
All the latest work for the next minor versions happens in the develop branch. If like the bleeding edge then that's the branch you want.
