### ISSUE TITLE
Implement <leader>hu undo the hunk under the cursor

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#603]
This is a default mapping bound by the plugin vim-gitgutter.

**Comment by eproxus** [comment]
Unimpaired also has `[n` and `]n` to navigate between conflicts/hunks:
```
                                                 *[n*
[n                      Go to the previous SCM conflict marker or diff/patch
                         hunk.  Try d[n inside a conflict.

                                                *]n*
]n                      Go to the next SCM conflict marker or diff/patch hunk.
                        Try d]n inside a conflict.
```

**Comment by gerardroche** [comment]
Undoing hunks can be mapped:

```
let mapleader=,
nnoremap <leader>hu :RevertHunk<CR>
```

Read https://blog.gerardroche.com/2022/11/13/undoing-diff-hunks-in-neovintageous/

**Comment by eproxus** [comment]
I found that the above mapping cannot be undone once performed (in contrast, pressing the default Sublime shortcut <kbd>⌘</kbd><kbd>K</kbd>,<kbd>⌘</kbd><kbd>Z</kbd> the operation is added to the undo stack). Is this a bug? Do you want me to open a new issue?

**Comment by gerardroche** [comment]
You should be able undo it with `u` or the `Ctrl+z` and `Ctrl+u` built-in st commands. Not sure what the difference is between the two built-in st undo commands. I tried both and they work. The revert hunk command is the built-in st command so it should do the same as the built-in st keymap.

**Comment by gerardroche** [comment]
If you use the ctrl keys in neo, you can enter insert mode and many ctrl keys will now invoke the built-in st commands. I use this quirk a lot e.g. `ctrl+z`, `ctrl+u`. I have `ctrl+u` disabled in insert mode specifically for this purpose:

```
	"vintageous_handle_keys":
	{
		"<C-f12>": false,
		"<S-f1>": false,
		"<S-tab>": false,
		"<f1>": false,
		"i_<C-u>": false,
	},
```
