### ISSUE TITLE
C-e / C-y doesn't work in visual line mode

### ISSUE THREAD

**Issue by nlack** [NeoVintageous/NeoVintageous#609]
### Description
`<C-e>` and `<C-y>` should in Visual Line mode doesn't work.
### Steps to Reproduce
Enter visual line mode with `V` and try scrolling the buffer with `<C-e>` or `<C-y>`.

### Expected behaviour
In (neo)vim it moves the view one line down or up without changing the selected area.
### Actual behaviour
Nothing happened
### Versions
`startup, version: 3208 linux x64 channel: dev`
`Package Control: Upgraded NeoVintageous to git commit 5f3cbea8`

**Comment by gerardroche** [comment]
Do you have ctrl keys enabled?

Configure settings via **Menu > Preferences > Settings** or by the Command
Palette. To use the command palette:

1. Press `Ctrl+Shift+P`
2. Select the "Preferences: Settings" command
3. Press `Enter`

For example to enable the ctrl keys:

```
    {
        "vintageous_use_ctrl_keys": true
    }
```

Or use the Command Palette **Toggle ctrl keys** command.

**Comment by nlack** [comment]
> Do you have ctrl keys enabled?

Yes, it works with visual mode and in normal mode.
Only visual line mode is not working for me with this keys.
