### ISSUE TITLE
A search bound to a key in .neovintageousrc is not repeatable by 'n' or 'N'

### ISSUE THREAD

**Issue by jotjotjes** [NeoVintageous/NeoVintageous#612]
### Description

I bound a search to a key in the .neovintageousrc file. The search is executed correctly, but I can't repeat it using the 'n' or 'N' key.

### Steps to Reproduce

I bound a search for three repeating characters to leader key plus 'm' by putting the following line into .neivintageousrc:

`nnoremap <leader>m /([^0-9w# ])\1\1<CR>`

### Expected behaviour

After pressing <leader>m any three repeated characters are found. Pressing 'n' / 'N' repeats the search forward / backward. 

### Actual behaviour

After pressing <leader>m any three repeated characters are found. I can press <leader>m again to repeat the search. 'n' and 'N' do not repeat the search. It does either nothing or repeats the last search I did manually.

### Versions

`startup, version: 3207 linux x64 channel: stable`

### Additional Information

If I type `/([^0-9w# ])\1\1` to search manually instead of using the mapping, the search is repeatable with 'n' and 'N'.

**Comment by gerardroche** [comment]
It looks like the search from mapping is not being saved, because if you do a search say `/foo` then the search from the mapping `<leader>m`, then `n/N` will actually search for "foo".

**Comment by gerardroche** [comment]
It looks like other searches like `?`, `*`, `f{char}`, etc might be impacted by this bug too, but `/{pattern}` will be fixed in 1.17.0.
