### ISSUE TITLE
Is there possible to change block cursor to underline in visual mode?

### ISSUE THREAD

**Issue by 0xk175un3** [NeoVintageous/NeoVintageous#614]
I want to change my block caret in visual mode to _ (underline) symbol. Is it possible?

**Comment by gerardroche** [comment]
My block caret is an underline. Is this what you mean:

![Screenshot from 2019-07-04 13-49-15](https://user-images.githubusercontent.com/44148/60667813-59acef00-9e62-11e9-8a3c-95248fb8efdd.png)

I'm using the color scheme MonokaiFree: https://packagecontrol.io/packages/MonokaiFree.

I slightly tweak the color with the following override, which gives me square style selections and a more vibrant yellow cursor:

```
{
     "variables": {
        "bg0": "#272822",
        "bg1": "#3e3d32",
        // "bg2": "???????",
        // "bg3": "???????",

        "fg0": "#f8f8f2",
        "fg1": "#cfcfc2",
        "fg2": "#75715e",
        // "fg3": "???????",

        "blue": "#66d9ef",
        "cyan": "#a1efe4",
        "green": "#a6e22e",
        "magenta": "#fd5ff0",
        "orange": "#fd971f",
        "red": "#f92672",
        "violet": "#ae81ff",
        "yellow": "#e6db74",
    },
    "globals": {
        "caret": "yellow",
        "block_caret": "yellow",
        "selection_border_width": "0",
        "selection_corner_style": "square",
    },
    "rules": [

    ]
}
``

**Comment by 0xk175un3** [comment]
Thx you a lot!
