### ISSUE TITLE
Character , (coma) not supported as string in ex command

### ISSUE THREAD

**Issue by dindon-sournois** [NeoVintageous/NeoVintageous#618]
### Description

I would like to call Sublime's `switch_file` from a vim binding but it seem the character `,` isn't well interpreted. I can reproduce the issue with a simpler Sublime command like `open_file`.

### Steps to Reproduce

`:OpenFile file=foo contents=bar,`

### Expected behaviour

Open a file called `foo` and fill it with the string "bar," if it does not exist.

### Actual behaviour

Getting `Invalid command` in the status bar.

### Versions

startup, version: 3207 windows x64 channel: stable

### Additional Information

The type of the `contents` key of `open_file` is a string. However, the type of the `extensions` key of `switch_file` look more like a list so fixing this issue may not fix my problem.

For reference, the sublime keybinding looks like this : 
`{ "keys": ["alt+o"], "command": "switch_file", "args": {"extensions": ["cu", "cpp", "cxx", "cc", "c", "hpp", "hxx", "hh", "h", "ipp", "inl", "m", "mm"]} },`

The ex command I actually want to run is :
`:SwitchFile extensions=c,h<CR>`

**Comment by gerardroche** [comment]
User ex commands were originally only implemented in basic cases so this is why some characters are being treated as invalid, but I'm more than happy update the validator as cases arise. Ideally the parser can rewritten to be a little more expansive in the basic cases.
