### ISSUE TITLE
Typing a bracket/quote while in normal mode insert two bracket/quote when auto match is enabled

### ISSUE THREAD

**Issue by dindon-sournois** [NeoVintageous/NeoVintageous#619]
### Description

Typing an opening bracket (`[` `(` `{`) or a quote (`'` `"`) while in normal mode insert two brackets/quotes when the Sublime setting `auto_match_enabled` is set to `true`.

### Steps to Reproduce

Activate the auto match feature in `Preferences.sublime-settings` :
```
{
 "auto_match_enabled": true,
}
```
Enter normal-mode, put your cursor where the auto-pairing feature would work like an empty line for example and press `"` (double quote).

### Expected behaviour

Typing `"` while in normal mode allow us to use registers to copy or move text even with the setting activated.

### Actual behaviour

Insert two `"`, stays in normal-mode.

### Versions

startup, version: 3207 windows x64 channel: stable

### Additional Information

I guess the troublemaker is Sublime keybinding for `"` :

```
// Auto-pair quotes
{ "keys": ["\""], "command": "insert_snippet", "args": {"contents": "\"$0\""}, "context":
  [
    { "key": "setting.auto_match_enabled", "operator": "equal", "operand": true },
    { "key": "selection_empty", "operator": "equal", "operand": true, "match_all": true },
    { "key": "following_text", "operator": "regex_contains", "operand": "^(?:\t| |\\)|]|\\}|>|$)", "match_all": true },
    { "key": "preceding_text", "operator": "not_regex_contains", "operand": "[\"a-zA-Z0-9_]$", "match_all": true },
    { "key": "eol_selector", "operator": "not_equal", "operand": "string.quoted.double - punctuation.definition.string.end", "match_all": true }
    ]
},
```

I don't think it can easily be fixed but any feedback is welcome as always.

**Comment by gerardroche** [comment]
I'm not I understand the issue.

Pressing `"` (double quote), for example, should allow you to use a register so `"ayy` should yank the current line into register **a**. You can check the registers via `:registers`. It shouldn't matter what `auto_match_enabled` is set to.

If double quote is doing something else it might mean you have custom key binding overriding neovintageous, or another plugin is overridiing it. You can check it by looking at the logs: https://github.com/NeoVintageous/NeoVintageous/blob/master/CONTRIBUTING.md#debugging

Show the Sublime Text console log: **Menu > View > Show Console**.

Command and input logging are enabled by running the following commands in input box at the bottom of the console: `sublime.log_commands(True)` and `sublime.log_input(True)`.

You should get something like:

```
chr evt: " (0x22)
command: _nv_feed_key {"key": "\""}
chr evt: a (0x61)
command: _nv_feed_key {"key": "a"}
chr evt: y (0x79)
command: _nv_feed_key {"key": "y"}
chr evt: y (0x79)
command: _nv_feed_key {"key": "y"}
```

**Comment by dindon-sournois** [comment]
Sorry, this one is on me ! 
I duplicated all Sublime keybindings in the User keybindings to disable them or remap them and `\"` was one of them.
