### ISSUE TITLE
iskeyword configuration support

### ISSUE THREAD

**Issue by pkrefta** [NeoVintageous/NeoVintageous#622]
Hello,

In my `.vintagegousrc` and `init.vim` I have `let iskeyword-=_` which adds `_` as word separator so I can easily jump in string like `PACKAGE_MODAL_OPEN` but unfortunately this doesn't work in NeoVintageous. Am I doing something wrong or this simply has to be implemented ? 😃

**Comment by gerardroche** [comment]
Sorry this feature isn't supported yet. It could be long time before it's implemented.

**Comment by gerardroche** [comment]
Moved to the roadmap:

https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md
