### ISSUE TITLE
:goto_line doesn't move screen to keep cursor in view

### ISSUE THREAD

**Issue by EmperorEarth** [NeoVintageous/NeoVintageous#623]
### Description
When using [`:goto_line`](https://vim.fandom.com/wiki/Go_to_line), neovintageous doesn't scroll keep cursor on screen.

### Steps to Reproduce
If lines 1-40 are currently on-screen
1. Press `Esc` to enter normal mode
2. Type `:100`
3. Press `Enter`
4. Cursor is now off-screen

(If I press `j`/`k`/etc to move cursor, screen scrolls correctly to bring cursor back into view)

### Expected behaviour
Scroll screen as necessary to keep cursor in view when using `:goto_line`

### Actual behaviour
Moves cursor to correct line but doesn't scroll screen as necessary when using `:goto_line`

### Versions
* Both on `Windows 7x64` and `macOS 10.15 Catalina`
* `Sublime Text 3.2.1 Build 3207`
* `Neovintageous v1.17.2`

### Additional Information
* empty `.neovintageousrc` file

Potentially relevant `User/Preferences.sublime-settings`
* `	"font_size": 15,`
* `	"neovintageous_build_version": 11100,`
* `	"theme": "Adaptive.sublime-theme",`
* `	"vintageous_autoindent": false,`
* `	"vintageous_ignorecase": true,`
* `	"vintageous_use_ctrl_keys": true,`
* `	"vintageous_use_super_keys": null,`
* `	"vintageous_use_sys_clipboard": true,`

**Comment by xtian** [comment]
I'm seeing this as well. I have `"highlight_line": true` in my Sublime settings and when I use `:` to jump to a line the highlighted line changes but the cursor position does not.

**Comment by xtian** [comment]
@gerardroche Thanks!
