### ISSUE TITLE
"change" surround commands don't work for `/` or `_`

### ISSUE THREAD

**Issue by rkoval** [NeoVintageous/NeoVintageous#631]
## Description

vim-surround supports change motions for `/` and `_` characters, but NeoVintageous does not. These delimiters are somewhat common in my dev workflow (any regex for `/` or any snake_cased variable for `_`), so it would be nice to have this functionality in NeoVintageous as well.

### Steps to Reproduce
Cursor being `|`...

`/foo|bar/` --> type `ci/`

### Expected behaviour

Insert mode is entered without deleting characters between `/`. This behavior is the same for surrounding `_`.
(Working variant: `"foo|bar"` --> type `ci"`)

### Actual behaviour

Insert mode should be entered with everything deleted between `/`. I notice the same behavior for the `ca/` motion.

### Versions

`startup, version: 3207 osx x64 channel: stable`

### Additional Information

Any additional information, configuration, or data that might be necessary to reproduce the issue.

Show the Sublime Text console log: `Menu > View > Show Console`.

Command and input logging are enabled by running the following commands in input box at the bottom of the console: `sublime.log_commands(True)` and `sublime.log_input(True)`.

For `ci/` and then `ca/`:
```
chr evt: c (0x63)
command: _nv_feed_key {"key": "c"}
chr evt: i (0x69)
command: _nv_feed_key {"key": "i"}
chr evt: / (0x2f)
command: _nv_feed_key {"key": "/"}
key evt: escape
command: _nv_feed_key {"key": "<esc>"}
chr evt: c (0x63)
command: _nv_feed_key {"key": "c"}
chr evt: a (0x61)
command: _nv_feed_key {"key": "a"}
chr evt: / (0x2f)
command: _nv_feed_key {"key": "/"}
```

**Comment by gerardroche** [comment]
`ci` is actually part of core vim, `cs{t}{r}` is a surround feature.  `ci` is used with text objects (`:help text-object`: http://vimdoc.sourceforge.net/htmldoc/motion.html#text-objects). For example, `ciw` changes an inner word, `ci"` inner quotes, etc. It doesn't work with arbitrary characters. Similarly with the surround commands, they don't work with all arbitrary characters.

One way to do what you want is `T{char}ct{char}` (move back till `{char}` then change till `{char}`. 

There's probably a plugin that helps optimise the above so I'll keep this open as a potential plugin implementation. My initial thoughts would be a plugin that provides a mapping in the form `<leader>c{char}` equivalent to `T{char}ct{char}`.

**Comment by gerardroche** [comment]
Implemented in the upcoming 1.20.0 release as text objects e.g. `ci/`, `ca/`, `ci_`, `ca_` and work for other operators too e.g. `di/`, `yi/`.

These text objects are custom specific to neovintageous, there not in the original vim.

**Comment by sourcevault** [comment]
I am having a similar issue, `ci"` is not working as I expected.

`vim-surround` is enabled. Not sure where the error is.

https://github.com/NeoVintageous/NeoVintageous/assets/20347647/18a2bb0d-fa34-41ca-a956-9be8d369e503

**Comment by sourcevault** [comment]
@gerardroche I am really sorry, it was my mistake. 

I had this remapping in my `.neovintageousrc` file 

`nnoremap ciw ciW`

I am still very new to vim and writing configs.

I have a separate question if you do not mind me asking:

how do I see all the marks in `neovintageous` ? 

in `neovim` you can do `:marks` and all your marks are shown, is there a similar command ?

**Comment by gerardroche** [comment]
There is some support for marks:

You can set marks and jump to them and use in operators. No lists marks support.

```
7. Marks					*mark-motions* *E20* *E78*

Jumping to a mark can be done in two ways:
1. With ` (backtick):	  The cursor is positioned at the specified location
			  and the motion is |exclusive|.
2. With ' (single quote): The cursor is positioned on the first non-blank
			  character in the line of the specified location and
			  the motion is linewise.

						*m* *mark* *Mark*
m{a-zA-Z}		Set mark {a-zA-Z} at cursor position (does not move
			the cursor, this is not a motion command).


						*'* *'a* *`* *`a*
'{a-z}  `{a-z}		Jump to the mark {a-z} in the current buffer.

						*'A* *'0* *`A* *`0*
'{A-Z0-9}  `{A-Z0-9}	To the mark {A-Z0-9} in the file where it was set (not
			a motion command when in another file).


```

**Comment by gerardroche** [comment]
@sourcevault I've enabled Discussions https://github.com/NeoVintageous/NeoVintageous/discussions

**Comment by sourcevault** [comment]
@gerardroche thank you for enabling discussion 🙏.
