### ISSUE TITLE
NeoVintageous and highlight_line

### ISSUE THREAD

**Issue by chiumichael** [NeoVintageous/NeoVintageous#634]
Hi there!

I recently set `highlight_line = true` in my sublime settings and notice that essentially hides the blinking carrot that marks the current position of the cursor. Is there a way that we can set the color value of the carrot so that I can use neoVintageous in conjunction with the `highlight_line` setting?

Thanks!

**Comment by gerardroche** [comment]
There is Sublime issue https://github.com/SublimeTextIssues/Core/issues/2695

See https://github.com/NeoVintageous/NeoVintageous/issues/342#issuecomment-473039146 for a custom workaround:

> Some color schemes are impacted like Mariana. Color schemes like Monokai are unaffected. Also if you use Monokai, try [MonokaiFree](https://packagecontrol.io/packages/MonokaiFree).
> 
> I use MonokaiFree with a few tweaks. Some don't like the vibrant yellow cursor, but I really like it. Also square borders are nice.
> 
> User/MonokaiFree.sublime-color-scheme
> 
> ```
> {
>     "globals":
>     {
>         "caret": "yellow",
>         "block_caret": "yellow",
>         "selection_border_width": "0",
>         "selection_corner_style": "square"
>     },
> }
> ```
