### ISSUE TITLE
Pass context to keybindings in .neovintageousrc

### ISSUE THREAD

**Issue by dvcrn** [NeoVintageous/NeoVintageous#643]
### Description

It doesn't seem to be possible to pass `context` to keybindings within .neovintageousrc. 

I scope a lot of my keybindings to be syntax specific like so (golang specific):

```
     {
        "keys": ["g", "d"],
        "command": "lsp_symbol_definition",
        "context": [
            { "key": "vi_command_mode_aware" },
            { "key": "selector", "operator": "equal", "operand": "source.go" }
        ]
    },
```

(see the selector context key)

and would like to bring this over to the .neovintageousrc. This allows me to use the same keybindings for goto and friends in multiple languages with different tools behind the action 

In vim itself I am using autocmd and lazyloading plugins to achieve this.

Is this possible with neovintageous?

**Comment by gerardroche** [comment]
Yes I think it's possible to implement. On the face of it I'm guessing implemented `autocmd` in the neovintageousrc file will be enough. The `autocmd` command is big, but It can implemented little by little focusing on the most used parts first.  


So where you might normally create a mapping like:

```
let mapleader=,
nnoremap <leader>gd :LspSymbolDefinition<CR>
```

To map it specific to file or syntax I think implementing some basic `autocmd` features should be enough to start:

```
let mapleader=,
autocmd FileType go nnoremap <leader>gd :LspSymbolDefinition<CR>
autocmd Syntax source.go nnoremap <leader>gd :LspSymbolDefinition<CR>
```

At least that's how I currently understand the autocmd. I'll need to look into it more, but I think that's about right.

**Comment by dvcrn** [comment]
@gerardroche If you can give me some pointers, I could also try to submit a PR for this myself :)

**Comment by gerardroche** [comment]
I almost don't where to start myself. The core stuff around resolving mappings is still very messy and fragile. I'll take a look this weekend. I've been wanting to address [granular keybindings](https://github.com/NeoVintageous/NeoVintageous/issues/470) which can probably been implemented at the same time. These are two of main features I'd like to see in the next minor version. After that I'd be happy to bump to [2.0](https://github.com/NeoVintageous/NeoVintageous/issues/711) which would be mostly a symbolic version bump that changes some default settings.

**Comment by gerardroche** [comment]
In the next version you will be able to specify a `FileType` in mappings. This is not a normal Vim feature. The proper Vim way would be to use an `autocmd` but it's not so easy to implement those so I decided to implement this as a compromise. It should mostly solve the problem of context specific mappings: 

    nnoremap FileType go gd :LspSymbolDefinition<CR>

**Comment by dvcrn** [comment]
Whoa that's amazing! I didn't expect to see this anytime soon (or ever) so this notification was a nice surprise ❤️

**Comment by gerardroche** [comment]
The FileType is based on the file name extension. Currently to bind to multiple file types you have to write multiple mappings for each file type:

    nnoremap FileType go gd :LspSymbolDefinition<CR>
    nnoremap FileType html gd :LspSymbolDefinition<CR>

Or with a fallback:

    nnoremap gd :DoSomethingElse<CR>
    nnoremap FileType go gd :LspSymbolDefinition<CR>
    nnoremap FileType html gd :LspSymbolDefinition<CR>

These will only work if the file has a file name. A `Syntax` argument for specifying a syntax instead of file type might be added later.

I think adding multiple file types might be doable as a comma delimited list:

    nnoremap FileType go,html gd :LspSymbolDefinition<CR>

**Comment by gerardroche** [comment]
You will be able specify multiple file types as a comma-delimited string:

    nnoremap FileType go,html gd :LspSymbolDefinition<CR>

**Comment by gerardroche** [comment]
1.29.0 has just been tagged and released so should be available in package control soon. I expect there may be one or two bugs with the FileType mappings as it was a bit tricky implementing it. Let me know if you find any.
