### ISSUE TITLE
Replace character Bug

### ISSUE THREAD

**Issue by anhlt** [NeoVintageous/NeoVintageous#647]
### Description
Since SublimeText 4,In COMMAND mode, when I press R to replace a single character, it randomly  replace number of following characters .

Same feedback from the other user

> I'm seeing this behaviour too. It doesn't appear to be random though—it depends on the index of the character in the word as to how many characters it will replace and insert.

### Steps to Reproduce

For example, this is the result of pressing `r` then `a` on each letter of the word hello in command mode:
```
aello
haallo
heaaalo
helaaaao
hellaaaaa
```

### Versions

Show the Sublime Text console log: `Menu > View > Show Console`.

Sublime 4057

### Additional Information
```
chr evt: r (0x72)
command: _nv_feed_key {"key": "r"}
chr evt: r (0x72)
command: _nv_feed_key {"key": "r"}
LSP:  --> textDocument/didChange
```

**Comment by gerardroche** [comment]
This a backwards compat. issue with the Sublime API `view.split_by_newlines()`.

**Comment by jipumarino** [comment]
May I ask what is this reference to ST4?

**Comment by gerardroche** [comment]
There's an alpha build of Sublime Text 4 available on the [Sublime Text discord channel](https://forum.sublimetext.com/t/sublime-text-discord-server/26063).
