### ISSUE TITLE
cit deletes inside the wrong tag

### ISSUE THREAD

**Issue by assertcarlos** [NeoVintageous/NeoVintageous#654]
### Description
When typing `cit` the wrong tag is being changed

### Steps to Reproduce
Where `|` represents the cursor type `cit`
```html
<header>
 |      <h1>Experience VR</h1>
<header>
```

### Expected behaviour
Delete the text inside the `h1` tag

### Actual behaviour
Deletes everything inside the `<header>` tag

### Versions

startup, version: 3211 osx x64 channel: stable

and using the latest version of NeoVintageous

**Comment by gerardroche** [comment]
Similar to https://github.com/NeoVintageous/NeoVintageous/issues/570
