### ISSUE TITLE
Update marks

### ISSUE THREAD

**Issue by kvazhir** [NeoVintageous/NeoVintageous#670]
Is there a possibility to make marks be dynamic? (If Sublime API allows it) What I mean by that is when you set a mark with `m` NeoVintageous keeps in mind exact line and location, whereas vim would update if a new line was added before.

Example:
```
a
b
mark me
c
d
```
I use `mq` on the "mark me" line then add a few lines above it. Then I use `` `q`` or `'q` to jump at the marked line, it will jump to the 3rd line, not to the "mark me" line.
Vim would correctly jump to the "mark me" line, no matter how many lines would be added above or below.

Thanks a lot for the package though, it's a lifesaver. Keep up the good work.

**Comment by gerardroche** [comment]
Yes I think this possible and shouldn't be too difficult to implement.

**Comment by kvazhir** [comment]
Beautiful, thanks a lot!
