### ISSUE TITLE
Press and hold move not working

### ISSUE THREAD

**Issue by gigavinyl** [NeoVintageous/NeoVintageous#673]
In regular vim, when you press and hold one of the direction keys h,j,k,l, you continuously move. This doesn't work on MacOS Catalina

**Comment by gerardroche** [comment]
This is a feature of OS X Lion and newer versions. To make a key repeat a
command when holding it down, run this once at the terminal:

    defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false

**Comment by burgreen** [comment]
This does not fix this issue on Catalina 10.15.4.
