### ISSUE TITLE
Search is always case-sensitive

### ISSUE THREAD

**Issue by sricks** [NeoVintageous/NeoVintageous#695]
**Describe the bug**  
Using `/` or `?` to search is always case sensitive. I tried setting neovintageous_smart: true and neovintageous_ignorecase: true in my settings, but it's always exact-case-sensitive.

**To Reproduce**  
- Press `/` to init search
- Type eg `bob`

**Expected behavior**  
String `Bob` is located

**Actual behavior**  
only `bob` is located

**Versions**  
Show the Sublime Text console log: `Menu > View > Show Console`. 
`startup, version: 3211 linux x64 channel: stable`

**Additional Information**  
I put the settings in my normal sublime user settings, because there are no package-specific settings for neovintageous. I'm pretty sure this is how it's supposed to work though.

I've also had problems with yank highlighting not working on multiple sublime installs in the past, but I always get it working somehow. Maybe I'm doing something wrong, I just install neovintageous via package control like every other plugin.

**Comment by gerardroche** [comment]
The default for `ignorecase` was changed in the last release to be case-sensitive by default.

> I put the settings in my normal sublime user settings, because there are no package-specific settings for neovintageous. I'm pretty sure this is how it's supposed to work though.

Yes that's correct way to set neovintageous settings, but most of the settings are still using the `vintageous_` prefix so `'vintageous_ignorecase': true` would work. However, that's a deprecated way to set *options*. Instead you can use your RC file to set options (open your RC file via the command palette).

## Options

Some vim options are supported in your rc file. For example, to always start
with the 'ignorecase' option on, add the following line your rc file: >

    set ignorecase

To always start with it off:

    set noignorecase

List of available options:

    'autoindent', 'belloff', 'hlsearch', 'ignorecase', 'incsearch', 'list',
    'magic', 'menu', 'minimap', 'modeline', 'modelines', 'number', 'sidebar',
    'spell', 'statusbar', 'winaltkeys', 'wrap', 'wrapscan'

Examples:

    set noignorecase
    set nomenu
    set nominimap
    set nomodeline
    set sidebar
    set statusbar
    set winaltkeys=menu

Try `:help 'option name'` for help on individual options. 

**Note that settings and options are different. Options are what vim uses, settings are specific to Sublime Text. See `:help nv` or go to [res/doc/neovintageous.txt](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt) for more details.**

**Comment by gerardroche** [comment]
> I've also had problems with yank highlighting not working on multiple sublime installs in the past, but I always get it working somehow. Maybe I'm doing something wrong, I just install neovintageous via package control like every other plugin.

If it doesn't work after a restart there's a problem. If it occurs again try to grab some debug information. See https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/ISSUE_TEMPLATE/bug_report.md.

**Comment by sricks** [comment]
Thanks, `set ignorecase` in my rc file worked. The documentation currently has some conflicting advice regarding the options, but no worries, greatly appreciated!
