### ISSUE TITLE
Support smartcase option

### ISSUE THREAD

**Issue by pvanb** [NeoVintageous/NeoVintageous#697]
Instead of having to use `:set ic` or `:set noic` to override `ignorecase` behaviour each time, it would be very helpful to have support for `:set smartcase` (and `:set nosmartcase`). Perhaps the best explanation comes directly from the [Vim documentation](http://vimdoc.sourceforge.net/htmldoc/options.html#'smartcase'):

                            *'smartcase'* *'scs'* *'nosmartcase'* *'noscs'*
    'smartcase' 'scs'	boolean	(default off)
        Override the 'ignorecase' option if the search pattern contains upper
        case characters.  Only used when the search pattern is typed and
        'ignorecase' option is on.  Used for the commands "/", "?", "n", "N",
        ":g" and ":s".  Not used for "*", "#", "gd", tag search, etc..  After
        "*" and "#" you can make 'smartcase' used by doing a "/" command,
        recalling the search pattern from history and hitting <Enter>.
        NOTE: This option is reset when 'compatible' is set.

**Comment by gerardroche** [comment]
Also see the [blog post](https://blog.gerardroche.com/2020/03/22/neovintageous-1.20.0/).
