### ISSUE TITLE
Add builtin settings to enable jj and jk map to escape

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#718]
Some developers like to map `jj`, `jk`, or some other two key combination, to `<Esc>` in Vim. This is not so easy in Sublime Text. Currently to do this is NeoVintageous is a bit cumbersome:

## Mapping jj or jk to Esc

**Menu > Preferences > Key Bindings**

Map: `jj` to `Esc`:

```
    {
        "keys": ["j", "j"],
        "command": "_enter_normal_mode",
        "args": {"mode": "mode_insert"},
        "context": [{"key": "vi_insert_mode_aware"}]
    }
```

Map: `jk` to `Esc`:

```
    {
        "keys": ["j", "k"],
        "command": "_enter_normal_mode",
        "args": {"mode": "mode_insert"},
        "context": [{"key": "vi_insert_mode_aware"}]
    }
```

## Suggestion

Add built in settings for two most common combinations: `jj` and `jk`.

setting | type | default
--------- | ------ | ---------
`vintageous_i_escape_jj` | `boolean` | `false`
`vintageous_i_escape_jk` | `boolean` | `false`

Users will still be able to create custom mappings for other two key combinations.

## Related

* https://github.com/NeoVintageous/NeoVintageous/issues/384
* https://github.com/NeoVintageous/NeoVintageous/issues/137
* https://github.com/NeoVintageous/NeoVintageous/issues/80
* https://github.com/NeoVintageous/NeoVintageous/issues/648

**Comment by sourcevault** [comment]
https://github.com/NeoVintageous/NeoVintageous/assets/20347647/b60a2dca-486d-4ff7-b034-3b9b4506571f

**Comment by denysmiller** [comment]
> 2023-05-12.07-06-32.mp4

just use "nv_enter_normal_mode", not "_enter_normal_mode"
Menu > Preferences > Key Bindings
    {
        "keys": ["j", "j"],
        "command": "nv_enter_normal_mode",
        "args": {"mode": "mode_insert"},
        "context": [{"key": "vi_insert_mode_aware"}]
    }
