### ISSUE TITLE
page up/down should not leave select mode

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#73]
<a href="https://github.com/bnovc"><img src="https://avatars2.githubusercontent.com/u/141912?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bnovc](https://github.com/bnovc)**
_Saturday Aug 02, 2014 at 21:51 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/706_

----

1. Hit shift+v
2. Hit page down (fn+down arrow on my MacBook)

I should continue to select, but it leaves select mode.

**Comment by gerardroche** [comment]
@bnovc This has been implemented in 1.15.0 (NeoVintageous is a fork of the discontinued Vintageous).

**Comment by lukedegruchy** [comment]
Confirmed!  Thank you so much for fixing this!
