### ISSUE TITLE
S key starts search rather than correct Vi behaviour

### ISSUE THREAD

**Issue by JonathanHolvey** [NeoVintageous/NeoVintageous#731]
I have an issue where the <kbd>S</kbd> key isn't behaving correctly in command mode. This is such a commonly used command I can't believe that it's a general bug in NeoVintageous, but more likely a configuration issue.

## To reproduce
1. Enter command mode
2. Position the cursor over a character in the buffer
3. Press <kbd>S</kbd>

## Expected behaviour 
The character below the cursor should be deleted and insert mode entered to allow insertion of replacement text, as per Vi. This is equivalent to typing <kbd>X</kbd> followed by <kbd>I</kbd>.

## Actual behaviour
Instead of the expected Vi behaviour, Sublime Text waits for two more key presses, then looks for the typed characters in the current buffer, as a kind of two-character search.

## Versions
Sublime Text v3.3.2 build 3211
NeoVintageous v1.21.0

**Edit:** This is a duplicate of #729

**Comment by johnathanz** [comment]
+1 on this issue. Just found this today - likely with latest release

Sublime Text: v3.3.2 build 3211
NeoVintageous 1.21.0

**Comment by gerardroche** [comment]
The recent release implemented a port of [sneak](https://github.com/NeoVintageous/NeoVintageous/issues/457) which overrides some keys like **S** and **s**. 

Sneak is invoked with **S** or **s** followed by exactly two characters:

```
s{char}{char} 
```

Type `sab` to move the cursor immediately to the next instance of the text "ab" or `Sab` to moe the previous instance.

**You can disable the plugin with the setting: `"vintageous_enable_sneak": false`.**

Perhaps I [underestimated](https://github.com/NeoVintageous/NeoVintageous/issues/729) the usage of commands  like `s` and `S`. 

Do you think sneak should be *disabled* by default? 

## Sneak commands

```
NORMAL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | s{char}{char}            | Go to the next occurrence of {char}{char}
[x]    | S{char}{char}            | Go to the previous occurrence of {char}{char}
[x]    | s{char}<Enter>           | Go to the next occurrence of {char}
[x]    | S{char}<Enter>           | Go to the previous occurrence of {char}
[x]    | s<Enter>                 | Repeat the last Sneak.
[x]    | S<Enter>                 | Repeat the last Sneak, in reverse direction.
[x]    | ;                        | Go to the [count]th next match
[x]    | , or \                   | Go to the [count]th previous match
[ ]    | s                        | Go to the [count]th next match (see NOTE)
[ ]    | S                        | Go to the [count]th previous match (see NOTE)
[ ]    | [count]s{char}{char}     | Invoke |sneak-vertical-scope|
[ ]    | [count]S{char}{char}     | Invoke backwards |sneak-vertical-scope|
[x]    | {operator}z{char}{char}  | Perform {operator} from the cursor to the next
                                  | occurrence of {char}{char}
[x]    | {operator}Z{char}{char}  | Perform {operator} from the cursor to the
                                  | previous occurrence of {char}{char}

[ ] NOTE: s and S go to the next/previous match immediately after invoking Sneak, if
|sneak-clever-s| is enabled.

VISUAL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[x]    | s{char}{char}            | Go to the next occurrence of {char}{char}
[x]    | Z{char}{char}            | Go to the previous occurrence of {char}{char}
[x]    | s{char}<Enter>           | Go to the next occurrence of {char}
[x]    | Z{char}<Enter>           | Go to the previous occurrence of {char}
[x]    | s<Enter>                 | Repeat the last Sneak.
[x]    | Z<Enter>                 | Repeat the last Sneak, in reverse direction.
[x]    | ;                        | Go to the [count]th next match
[x]    | , or \                   | Go to the [count]th previous match
[ ]    | s                        | Go to the [count]th next match (NOTE above)
[ ]    | S                        | Go to the [count]th previous match (NOTE above)

[ ] NOTE: Z goes backwards in visual-mode, because S is taken by the |surround|
plugin).

LABEL-MODE

Status | Key Sequence             | Description
-------|--------------------------|----------------------------------------------
[ ]    | <Space> or <Esc>         | Exit |sneak-label-mode| where the cursor is.
[ ]    | <Tab>                    | Label the next set of matches.
[ ]    | <BS> or <S-Tab>          | Label the previous set of matches.
```

*See the [roadmap, part 2](https://github.com/NeoVintageous/NeoVintageous/issues/711) for full details of the status of all plugins.*

**Comment by JonathanHolvey** [comment]
I think that overriding such a basic command by default is going to be very confusing for users, both new and established. Most people will expect the default configuration to match that of common Vi/Vim implementations, as well as many manuals and online tutorials.

**Comment by gerardroche** [comment]
I think I agree. the other plugins don't really override anything whereas sneak specifically overrides both **s** and **S**.

**Comment by johnathanz** [comment]
Agree with @JonathanHolvey that as a design philosophy for NeoVintageous, we shouldn't override basic vim commands.

So having Sneak off by default would help. 

Alternatively, I'm used to plugins like [easymotion](https://github.com/easymotion/vim-easymotion), or it's [Sublime Text port](https://github.com/tednaleid/sublime-EasyMotion) that use an unused Vim key combo to initiate motion (e.g. CTRL-;). Could be something to consider.

Thanks for the quick response @gerardroche , good to know there's a way to switch off Sneak too 😀
