### ISSUE TITLE
Alt + - jump_back is not working

### ISSUE THREAD

**Issue by sundarv85** [NeoVintageous/NeoVintageous#735]
With NeoVintageous enabled in Linux Sublime Text 3, I'm not able to jump_back.

When I press `Alt + -`, the line just blinks. When I use the menu to Jump Back `Menu > Goto > Jump Back`, and then when I use `Alt + Shift + -`, then the forward works. 

The behavior is the same even if I set below `ctrl` and `super` keys to `true` or `null`.

```
	"vintageous_use_ctrl_keys": true,
	"vintageous_use_super_keys": true,
```

Sublime version 3.2.2 Build 3211

**Comment by gerardroche** [comment]
In vim you use `Ctrl+i` and `Ctrl+o` to jump forward and backwards (in/out).

If you want to remap `Alt+-` to jump back add this to your neovintageousrc file:

```
noremap <M--> :JumpBack<CR>
```

Tip: `<C-]>` is mapped to goto definition. You can then immediately press `<C-o>` to jump back.

Documentation: https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt or `:help nv`. Also see https://blog.gerardroche.com.

**Comment by FrankFang** [comment]
```
"vintageous_handle_keys": {
		"<M-->": false,
		"<M-+>": false,
	},
```
