### ISSUE TITLE
Is there a way to have the behaviour to keep moving when the key is keeping pressed?

### ISSUE THREAD

**Issue by ciaoben** [NeoVintageous/NeoVintageous#746]
I am playing around with this great package in the last weeks, but I can't find any hint of how (if it is possible) to support the behaviour that when I keep press a move key (e.g. `j`) the movement is repeated while I keep pressed the key.
It is the default behaviour in vim, is there a way to have it with this package?

**Comment by babygau** [comment]
chances are you're using macOS, 

to enable key-repeating execute the following in your terminal and restart sublime text:
```
defaults write -g ApplePressAndHoldEnabled -bool false
```
this should work

**Comment by ciaoben** [comment]
Thanks, that did the trick!!!

**Comment by gerardroche** [comment]
For everyone on Linux see https://github.com/NeoVintageous/NeoVintageous/issues/709
