### ISSUE TITLE
viw, vaw behaviour does not copy Vim behaviour

### ISSUE THREAD

**Issue by craigmac** [NeoVintageous/NeoVintageous#748]
**Describe the bug**  
When using 'vih' on last letter of a word, it should select the word, or with vaw select the word, plus any trailing whitespace up to but not including the next non-whitespace character.

**To Reproduce**  
1. Open a /tmp/test.txt file with these contents:
will this do selection! correctly?
                *
2. Put cursor where asterisk marked above.                    
3. Try 'viw'
4. Try 'vaw'

**Expected behavior**  
1. 'viw' should select 'do'
2. 'vaw' should select 'do ' (notice trailing space)

**Actual behavior**  
1. ' ' is selected (trailing space behind the word)
2. ' ' is selected (trailing space behind the word)

**Versions**  
startup, version: 4086 windows x64 channel: dev
NeoVintageous version 11100

**Additional Information**  

'yiw' and 'yaw' work like Vim does on any other letter of a word except for the last character of the word, it seems to me. There might be further edge cases that I haven't detected here of course.

**Comment by gerardroche** [comment]
It looks like your examples are missing some text, but I think I understand some of the issues. I've noticed a few differences in `iw` and `aw` text objects with Vim. 

When the cursor is on the last char of a word `fo|o bar` -> `viw` should equal `|foo| bar`, however if the selection is greater than one `f|oo| bar` -> `viw` should be `f|oo |bar`.

There are a few nuanced issues.

**Comment by gerardroche** [comment]
* [ ] `a fi|zz b` -> `caw` should be: `a |b`
* [ ] `a fi|zz    b` -> `caw` should be: `a |b`
