### ISSUE TITLE
Using <space> in motions and leader in sublime keybindings at the same time? Any way to see if we are currently inside a motion?

### ISSUE THREAD

**Issue by dvcrn** [NeoVintageous/NeoVintageous#752]
This is more a question and not a bugreport, but:

I have a bunch of these keybindings that use <space> as leader and work in normal mode:

```
    { "keys": [" ", "g", "d"], "command": "lsp_symbol_definition", "context": [{"key": "vi_command_mode_aware"}], "operand": "source.go", },

```

So in normal mode I can hit `<space> g d`, and it will jump to definition of what's under the cursor. This is inspired by spacemacs and other systems that use <space> as the leader

The problem is that when I'm in normal mode, I can't use motions that use space like `f <space>` to jump to the next space because it's being blocked by the sublime keybindings until it times-out or I hit another key. 

I guess a solution is to remove the sublime keybindings and migrate them to neovintageous variants, but the `operand:` stuff isn't supported yet to pass along. 

Is there anything else I can do to remove the delay when I use `<space>` inside a motion? For example, is there a context like `vi_in_motion` that I can use to filter my keybindings down to only trigger when I'm not inside a vintageous motion?

**Comment by gerardroche** [comment]
I can't think of any workaround. At the moment you can't contrain mappings in the rc file to operand. I think https://github.com/NeoVintageous/NeoVintageous/issues/643 is the only thing that will resolve it.

**Comment by dvcrn** [comment]
Would it be possible to include a `vi_in_motion` context? Like, setting it once a motion starts, and unsetting it on motion end. I'm not fully familiar with how sublimetext works under the hood though..

**Comment by LPGhatguy** [comment]
I ended up working around this by just pressing space twice when it comes up. At least on the latest build of ST4, that seems to put a space into the motion buffer.

I agree that it would be useful to have a `vi_in_motion` context.
