### ISSUE TITLE
Can you pass more complex args into : commands? 

### ISSUE THREAD

**Issue by dvcrn** [NeoVintageous/NeoVintageous#759]
Hi, this is more a question than a bug report. Sorry for always coming up with these weird edge cases :) 

I started migrating my keybindings from sublime keybindings into vintageous aware ones, so for example:

```
{ "keys": [" ", "p", "f"], "command": "show_overlay", "args": {"overlay": "goto", "show_files": true}, "context": [{"key": "vi_command_mode_aware"}], },

```

is becoming:
```
nnoremap <space>pf :ShowOverlay overlay=goto show_files=true<CR>

```

So far so good, but I was wondering if this supports more complex actions. For example, I wrote the [multicommand](https://packagecontrol.io/packages/Multicommand) plugin that allows you to chain a couple commands in series:

```
    { "keys": [" ", "p", "r"], "command": "multicommand", "args": {
        "commands": [
            {"command": "slurp_find_string"},
            {"command": "slurp_replace_string"},
            {"command": "show_panel", "args": {"panel": "find_in_files"}},
        ]
    }, "context": [{"key": "vi_command_mode_aware"}], },
```

Is it possible to move this into `.neovintageousrc`? I tried something like

```
nnoremap <space>pr :Multicommand commands=[{"command": "slurp_find_string"}]<CR>
```

but that's not working sadly. Is this doable with a different syntax or out of scope?

**Comment by gerardroche** [comment]
No that feature isn't available at the moment. The mappings only accept simple arg=value parameters.

To workaround it you would need to write wrapper commands and have the commands call the multicommand with the complex arguments.

**Comment by dvcrn** [comment]
Ah I see! We can close this if it's out of scope for now 👍

**Comment by gerardroche** [comment]
I think it's possible. It's just a case allowing a format for for a list of simple arg=value's. 

Right now the format allows for roughly:

````
arg=value arg=value *<CR>
``` 

So I'm thinking maybe something like 

```
[arg=value arg=value *] [arg=value arg=value *] *<CR>
```

**Comment by gerardroche** [comment]
Support for chaining user commands has been added. The special `<Bar>` character can be used to separate commands from the next command:

```
nnoremap <leader>m :SlurpFindString<Bar>:SlurpReplaceString<Bar>:ShowPanel panel=find_in_files<CR>
```

**Comment by gerardroche** [comment]
Added support for chaining ex commands too:

```
noremap <C-s> :w<Bar>:SomeOtherCommand<CR>
```
