### ISSUE TITLE
Multiple Cursor Selecting Wrong Value

### ISSUE THREAD

**Issue by pvanb** [NeoVintageous/NeoVintageous#761]
**Describe the bug**  
When a search term matches a substring, using `gh` to start multiple cursor mode will select the word under the cursor instead of the matching term. Using `gH` to select all matching occurrences selects all the matches as expected.

**To Reproduce**  
1. Open a new file containing the following text:

    `nowhere somewhere anywhere everywhere`

2. Move cursor to start of file then search for `where`
3. `gh` (or `<C-n>`)
4. Word `nowhere` is selected instead of `where`. It is not possible to add or skip matches.

**Expected behavior**  
After starting multiple cursor with `gh` (or `<C-n>`) only the search term `where` should be selected, and it should be possible to use `j` (or `<C-n>`) and `l` (or `<C-x>`) to add or skip matches of the original search term (`where`).

**Actual behavior**  
After starting multiple cursor with `gh` (or `<C-n>`) the match is expanded to select the word under the cursor (`nowhere`). Using `j` (or `<C-n>`) and `l` (or `<C-x>`) will only add or skip matches of the term `nowhere`.

**Versions**  
SublimeText:
startup, version: 4099 osx x64 channel: dev

NeoVintageous:
v1.23.0

**Additional Information**  

Contents of `.neovintageousrc`:

    " Type :help nv for help.
    :set ignorecase
    :set smartcase

Quick demo of the issue:

https://user-images.githubusercontent.com/823278/111181579-8183ae00-8584-11eb-966a-7beeb3f99c32.mov

1. First, using `gh`
2. Second, using `gH`

**Comment by gerardroche** [comment]
I  think what you want is `gn` visually select last search.

Do a search:

```
/where<CR>
```

This will highlight the "where", now press `gn` to visually select the highlighted search.

Now press `gh` or `<C-n>` to start the multiple cursor and then `j`, `l`, `<C-x>`, etc will work.
