### ISSUE TITLE
`P` and `p` aren't supposed to paste lines starting from the current cursor position

### ISSUE THREAD

**Issue by chenglou** [NeoVintageous/NeoVintageous#762]
**Describe the bug**  
Title.

**To Reproduce**  
1. yank a few lines
2. Go to the middle of another line
3. `p` or `P`

**Expected behavior**  
The yanked lines should have been pasted below/above the current line.

**Actual behavior**  
The yank lines are now interleaved within the current line

**Versions**  
startup, version: 3211 osx x64 channel: stable

**Additional Information**  
Suuuper annoying =P

**Comment by gerardroche** [comment]
I fixed it for the motions j and k e.g. `3yj`, `3yk`, etc. If some other motions and missing and should be linewise on multiline yank-paste let me know.
