### ISSUE TITLE
Keyboard input stops being accepted after some time passes in Sublime Text 4

### ISSUE THREAD

**Issue by asfaltboy** [NeoVintageous/NeoVintageous#766]
**Describe the bug**  

Started to happen to me since I switched to Sublime Text 4, after having the editor open for a while it randomly stops taking input. To work around the bug I disable and re-enable the NeoVintagous plugin; this hints at NeoVintageous as being the culprit (or one of them).

**To Reproduce**  
1. Open sublime
2. Work with the editor / let it stay running for a while
3. Cannot use hjkl or arrow keys any longer, until reloading neovintagous.

**Expected behavior**  

I'm not 100% sure the plugin is supported fully under ST4, but it does seem to work as far as I can tell, except for this nuisense.

**Actual behavior**  

As in the description.

**Versions**  

Log didn't have anything interesting, will add log once and issue is reproduced and some debug info is emitted.

Using: Sublime Text 4, Dev channel, Build 4102, NeoVintageous installed from package control.

**Additional Information**  

I just ran `sublime.log_commands(True)` and `sublime.log_input(True)` with `SUBLIME_NEOVINTAGEOUS_DEBUG=y`, and will monitor the console. The issue recurred, but alas I closed the original window (project) I had running and in the new window the log is shorter. I've noticed an error that is logged upon disable/enable of NeoVintageous and that is visible int he log below:

[console_log.txt](https://github.com/NeoVintageous/NeoVintageous/files/6374968/console_log.txt)

**Comment by gerardroche** [comment]
It looks like there are several errors. Maybe you're sublime settings file is corrupted?

Go to Menu > Settings and check `neovintageous_build_version` is not None, if it is set it to int `0` 

You can check what they return via this too:

```
sublime.load_settings('Preferences.sublime-settings').get('neovintageous_build_version', 0)
```

Also check `ignored_packages` is a valid list e.g:

```
	"ignored_packages":
	[
		"Vintage",
		"Vintageous",
	],
``` 

Try toggling the relativenumber option:


```
:set relativenumber
:set norelativenumber
:set relativenumber
```

**Comment by asfaltboy** [comment]
Thanks @gerardroche . The settings values return `None` in `plugin.py:92`, when the package is being reloaded. But the correct setting values when  I manually run `sublime.load_settings('Preferences.sublime-settings')` in the console.

I also noticed this nasty issue often happens when I create a new Sublime Text window. And, the only output in that new window's console is:

```
Unable to open /Users/pavelsavchenko/Library/Application Support/Sublime Text 3/Packages/Default/Preferences.sublime-settings
```

As far as I know this is harmless, as the preferences file does exist in `Packages/User`.

Note: toggling relative-number option on/off is not possible while no input is acceptable by NeoVintageous. I've tried to turn it off in my `.neovintageousrc` file but it didn't fix the issue.

Does this help get us closer to the root cause? Any other actions I can do to debug the problem?

**Comment by gerardroche** [comment]
Does the error occur only when disable the package and re-enable it? 

I'm able to reproduce some of the errors by disabling Neo and re-enabling. It seems the preferences are not being reloaded properly. A restart fixes it. 

ToggleNeoVintageous is available for quick toggling neo https://packagecontrol.io/packages/ToggleNeoVintageous, but even that breaks now too.

**Comment by asfaltboy** [comment]
The error in console only display when toggling yes. But, the issue I reported with keyboard input stopping happens (seemingly) randomly, with nothing weird in the console (the console of the new window includes a shorter log).

I only mentioned toggling the extension as that is the workaround I used for the problem.

**Comment by axsuul** [comment]
I'm also experiencing this issue
