### ISSUE TITLE
Remove CTRL-G mapping

### ISSUE THREAD

**Issue by Amparose** [NeoVintageous/NeoVintageous#777]
I can't work out what <C-g> is meant to do (just seems to show current file path in status bar) and it hijacks the useful GoToLine input of ST4. There doesn't seem to be any mention of this shortcut in `:help nv` so is there a way to remove the mapping?

EDIT: it seems that [printing the file name](http://vimdoc.sourceforge.net/htmldoc/editing.html#CTRL-G) is actually what it does, which isn't all that useful in ST. So I would definitely like to unmapped this and get GoToLine back.

**Comment by gerardroche** [comment]
You can remap `<C-g>` to the GoToLine in your neovintageousrc file:

Open it to edit via the Command Palette  `NeoVintageous: Open RC File` and add:

```
noremap <C-g> :ShowOverlay overlay=goto text=:<CR>
```

**Comment by bfulop** [comment]
Another solution is to set in `Preferences.sublime-settings` to ignore this key combo:

```json
	"vintageous_handle_keys": {
		"<C-g>": false,
		"<K>": false,
	},
```
