### ISSUE TITLE
Navigating in the command palette not working in ST4

### ISSUE THREAD

**Issue by JonathanHolvey** [NeoVintageous/NeoVintageous#780]
In Sublime Text 3, NeoVintageous allows navigation through entries in the command palette using <kbd>Ctrl</kbd>+<kbd>J</kbd> and <kbd>Ctrl</kbd>+<kbd>K</kbd>. This doesn't appear to work in the recently released Sublime Text 4.

**To Reproduce**
1. Open Sublime Text 4
2. Enable Ctrl keys in NeoVintageous if using Windows or Linux
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> to open the command palette
4. Press <kbd>Ctrl</kbd>+<kbd>J</kbd> or <kbd>Ctrl</kbd>+<kbd>K</kbd> to move down or up in the list of commands

**Expected behavior**  
The key combinations above should move up and down in the list of commands

**Actual behavior**  
<kbd>Ctrl</kbd>+<kbd>J</kbd> (on the second press) prompts a message about keybindings changing in ST4, while <kbd>Ctrl</kbd>+<kbd>K</kbd> does nothing. The keypresses appear to be consumed by Sublime Text itself, without being intercepted by NeoVintageous.

**Versions**  
Sublime Text 4 build 4107
Neovintageous v1.24.0

**Additional Information**  

Here's the output from the console when performing the steps above:

```
key evt: shift+ctrl+p
command: nv_feed_key {"key": "<C-P>"}
command: show_overlay {"overlay": "command_palette"}
key evt: ctrl+j
key evt: ctrl+j
command: primary_j_changed
key evt: ctrl+k
key evt: ctrl+k
command: run_macro_file {"file": "res://Packages/Default/Delete to Hard EOL.sublime-macro"}
```

**Comment by gerardroche** [comment]
When I try it I get a dialog message. I've seen this already I just haven't had time to look into it, but now that ST4 has been released I guess it should be fixed.

![Screenshot from 2021-06-22 12-15-01](https://user-images.githubusercontent.com/44148/122915557-c4a7a700-d353-11eb-8d3a-f5463dea3348.png)

**Comment by JonathanHolvey** [comment]
Thanks @gerardroche
