### ISSUE TITLE
Text objects from targets.vim

### ISSUE THREAD

**Issue by jabirali** [NeoVintageous/NeoVintageous#781]
First of all, thanks for making this great plugin :).

One of my favorite Vim/NeoVim plugins is [targets.vim][1], which defines additional text objects. Examples:

- **MarkDown:** `ci*` to change an emphasized phrase when the cursor `|` is located as in `this is *a t|est*`;
- **LaTeX:** `ci$` to change an inline equation when the cursor `|` is located as in `this is $a^{te|st}$`;
- **Python:** `ci,` to change a list element or function argument in the examples `def f(a, |b=c, d)` and `[12, 3|4, 56]`.

In fact, I think these would be even more useful in Sublime than in Neovim, as e.g. ⌘-clicking in *roughly* the right areas of a Python list and pressing `vi,` would be an easy way to access the multiple selection features of Sublime. 

For a more extensive list of text objects, this is what `targets.vim` lists in their `README`:

	i, i. i; i: i+ i- i= i~ i_ i* i# i/ i| i\ i& i$
	a, a. a; a: a+ a- a= a~ a_ a* a# a/ a| a\ a& a$

If believe these should not interfere with any existing bindings in Neovintageous, and should be simple to implement. If I understand correctly, we would just need to add a few lines like `'*': (('*', '*'), QUOTE),` to the `PAIRS` dict in `nv/vi/text_objects.py`? Would you be open to including this functionality in Neovintageous?

Note that `targets.vim` has a few other nice text objects, like `cin(` (change inside next parens) and `caa` (change an argument, like `ca,` but also works at the ends). These may require a bit more code and testing than the above though.

[1]: https://github.com/wellle/targets.vim

**Comment by gerardroche** [comment]
Roadmap

## i

- [ ] `i,`
- [ ] `i.`
- [ ] `i;`
- [ ] `i:`
- [ ] `i+`
- [ ] `i-`
- [ ] `i=`
- [ ] `i~`
- [ ] `i_`
- [ ] `i*`
- [ ] `i#`
- [ ] `i/`
- [ ] `i|`
- [ ] `i\`
- [ ] `i&`
- [ ] `i$`

## a

- [ ] `a,`
- [ ] `a.`
- [ ] `a;`
- [ ] `a:`
- [ ] `a+`
- [ ] `a-`
- [ ] `a=`
- [ ] `a~`
- [ ] `a_`
- [ ] `a*`
- [ ] `a#`
- [ ] `a/`
- [ ] `a|`
- [ ] `a\`
- [ ] `a&`
- [ ] `a$`

**Comment by gerardroche** [comment]
I've added all the new text objects. Please open separate for additional specific features from the targets plugin.

**Comment by jabirali** [comment]
Awesome, thanks a lot for implementing this! 🎉
