### ISSUE TITLE
Toggle-able option to keep sublime open when quitting out of last file

### ISSUE THREAD

**Issue by 11** [NeoVintageous/NeoVintageous#782]
### Description

Is it possible to add a setting to keep sublime open after `:q`-ing out of the last file buffer?

I understand that this feature has been asked for before, but I was wondering if this could be open to change? 

From what I saw in the previous threads that asked for this, it seems like the goal for `:q` was to replicate the same exact Gvim/vim behavior. But other vim emulators, like the one in vs-code, allow this to be an option you can set. It would be amazing if there was a way toggle this, or even just map `:q` to a custom command like `cmd + w`

(sorry if there is a fix for this already - I couldn't find a solution anywhere across google/stackoverflow/and `:help nv`)

**Comment by gerardroche** [comment]
I think you may want `:close` and `:close!`. But yeah, I think a setting to disable it is reasonable.

**Comment by 11** [comment]
ahh yes, `vintageous_exit_when_quiting_last_window` was what I was looking for! thanks for the kind response
