### ISSUE TITLE
Support keypad numbers as count prefix

### ISSUE THREAD

**Issue by jipumarino** [NeoVintageous/NeoVintageous#784]
Keypad numbers (`<k0>`-`<k9>`) don't currently work as count prefix for NV commands (for instance, typing `5j` in normal mode makes the cursor go down 5 lines, but typing `<k5>j` doesn't work, the argument 5doesn't even show up in the status line).

I tried working around this by creating the following keybinding, but NV interprets this as two 5 keypresses, so now typing `<k5>j` moves the cursor down 55 lines:
```
nnoremap <k5> 5
```

From my understanding, the special treatment of keypad numbers is to make them available for shortcuts. I'd like to have an option to disable this and make them behave like regular number keys or, if I'm missing something, have some way to work around it in order to make them available for count prefix.

**Comment by jipumarino** [comment]
I'm closing this one because I found that I could rebind keys like this:
```
{"keys": ["keypad0"], "command": "nv_feed_key", "args": {"key": "0"}, "context": [{"key": "vi_command_mode_aware"}]},
```

**Comment by gerardroche** [comment]
hmm, these mappings already exist:

```

    {"keys": ["keypad0"], "command": "nv_feed_key", "args": {"key": "<k0>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k0>"}]},
    {"keys": ["keypad1"], "command": "nv_feed_key", "args": {"key": "<k1>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k1>"}]},
    {"keys": ["keypad2"], "command": "nv_feed_key", "args": {"key": "<k2>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k2>"}]},
    {"keys": ["keypad3"], "command": "nv_feed_key", "args": {"key": "<k3>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k3>"}]},
    {"keys": ["keypad4"], "command": "nv_feed_key", "args": {"key": "<k4>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k4>"}]},
    {"keys": ["keypad5"], "command": "nv_feed_key", "args": {"key": "<k5>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k5>"}]},
    {"keys": ["keypad6"], "command": "nv_feed_key", "args": {"key": "<k6>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k6>"}]},
    {"keys": ["keypad7"], "command": "nv_feed_key", "args": {"key": "<k7>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k7>"}]},
    {"keys": ["keypad8"], "command": "nv_feed_key", "args": {"key": "<k8>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k8>"}]},
    {"keys": ["keypad9"], "command": "nv_feed_key", "args": {"key": "<k9>"}, "context": [{"key": "vi_command_mode_aware"}, {"key": "nv_handle_key", "operand": "<k9>"}]},

```
https://github.com/NeoVintageous/NeoVintageous/blob/master/Default.sublime-keymap#L544


If the numlock is engaged they should work the same as numbers. I wonder if Vim handles it the same.

**Comment by jipumarino** [comment]
Oh, note that I’m remapping to `0` instead of `<k0>`. In fact the sublime-keymap file is what gave me the idea.

I’ll try to find where exactly they’re handled different than numbers. Vim definitely treats them the same.

**Comment by jipumarino** [comment]
I think I identified the issue. The `isdigit()` check in lines 761 and 766 is returning true for regular numbers (`"2".isdigit()`) and false for keypad numbers (`"<k2>".isdigit()`)

https://github.com/NeoVintageous/NeoVintageous/blob/890d47c/nv/commands.py#L761-L766
