### ISSUE TITLE
Can't use Command Palette with ctrl+shift+p

### ISSUE THREAD

**Issue by jatinhemnani01** [NeoVintageous/NeoVintageous#785]
I Can't use Command Palette with ctrl+shift+p. I'm using Sublime Text 4
I can't change the shortcut for Neo​Vintageous

**Comment by gerardroche** [comment]
I'm unable to reproduce this issue. Can you provide some additional information:

Show the Sublime Text console log: `Menu > View > Show Console`.

Command and input logging are enabled by running the following commands in input box at the bottom of the console: `sublime.log_commands(True)` and `sublime.log_input(True)`.

Running `$ SUBLIME_NEOVINTAGEOUS_DEBUG=y; subl` (unix), `> set SUBLIME_NEOVINTAGEOUS_DEBUG=y& "C:\Program Files\Sublime Text 3\subl.exe"` (windows), will run NeoVintageous in debug mode. Debug messages are printed to the console log. See the [contributing guide](https://github.com/NeoVintageous/NeoVintageous/blob/master/CONTRIBUTING.md) for more detailed debugging instructions.

You may also want to review the help file: `:help neovintageous`, or visit the [online help file](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt).

**Comment by jatinhemnani01** [comment]
I fixed it. I think it was something because of Linux

**Comment by elsha-phytech** [comment]
I'm having this issue with latest version (1.26.0, installed via package manager).
I use sublime 4 in wsl.
One weird thing is that it works when my cursor is in the console view.
