### ISSUE TITLE
Asynchronous file saving with :w, :wq, ...

### ISSUE THREAD

**Issue by graudtV** [NeoVintageous/NeoVintageous#790]
I use Sublime Text to edit files on a remote machine, and it may take a couple of seconds to save a file. By default, Sublime saves files asynchronously, which is very convenient: one can continue scrolling file, switch tabs, etc. without feeling the lag. Unfortunately, :w does the stuff synchronously, making Sublime unresponsive to anything for a while. If one is making small changes and needs to save file frequently, it does hurt.

The following API, taken from default key bindings, enables async file saving:
``` { "keys": ["super+s"], "command": "save", "args": { "async": true } } ```
According to experimental research, If "args" are not specified, "async" considered being false

I suggest adding a setting like "vintageous_enable_async_save" which will propogate { "async": true } argument to calls like this: https://github.com/NeoVintageous/NeoVintageous/blob/e43e360a43bf0d0a5270a307160f5644f81db0ab/nv/ex_cmds.py#L1191

**Comment by gerardroche** [comment]
Due to a regression (#859) async saving has been disabled by default and the setting `vintageous_save_async` has been added.
