### ISSUE TITLE
Ctrl + k, Ctrl + j have wrong behaviour when autocomplete menu has only 1 item

### ISSUE THREAD

**Issue by Ghoul2077** [NeoVintageous/NeoVintageous#792]
**Describe the bug**  
Whenever there is autocomplete menu with only a single option and if you press Ctrl + k  or Ctrl + j it should do nothing but in this case it moves the actual cursor one line up and down respectively.

**To Reproduce**  
1. Make a new empty buffer
2. Press enter to make sure there are at least 2 lines
3. Type "lorem" in first line then press Ctrl + space to show its completion
3. Press Ctrl + j
4. Cursor actually moves to second line from "lorem"

**Expected behavior**  
Nothing should have happened as autocomplete popup is in focus and there is no more element above and below to navigate

**Actual behavior**  
The behavior of autocomplete up and down navigation is applied to view instead of autocomplete popup

**Versions**  
startup, version: 4113 windows x64 channel: stable
NeoVintageous v1.24.1

**Additional Information**  

Command & Input Log ->

```
chr evt: i (0x69)
command: nv_feed_key {"key": "i"}
command: mark_undo_groups_for_gluing
command: nv_enter_insert_mode {"count": 1, "mode": "mode_internal_normal"}
key evt: enter
command: insert {"characters": "\n"}
chr evt: j (0x6a)
chr evt: j (0x6a)
command: nv_enter_normal_mode {"mode": "mode_insert"}
command: hide_auto_complete
command: hide_overlay
command: glue_marked_undo_groups
command: sublime_linter_assigned {"filename": "<untitled 796>", "linter_names": []}
chr evt: k (0x6b)
command: nv_feed_key {"key": "k"}
command: nv_vi_k {"count": 1, "mode": "mode_normal", "xpos": 0}
chr evt: A (0x41)
command: nv_feed_key {"key": "A"}
command: mark_undo_groups_for_gluing
command: nv_vi_big_a {"count": 1, "mode": "mode_internal_normal"}
command: nv_enter_insert_mode {"mode": "mode_internal_normal"}
chr evt: l (0x6c)
chr evt: o (0x6f)
chr evt: r (0x72)
chr evt: e (0x65)
chr evt: m (0x6d)
key evt: ctrl+space
command: auto_complete
command: sublime_linter_assigned {"filename": "<untitled 796>", "linter_names": []}
key evt: ctrl+j
command: move {"by": "lines", "forward": true}
```

![Animation](https://user-images.githubusercontent.com/42601281/138552369-a8a30452-7d15-4f5a-a50e-71905405938f.gif)

**Comment by gerardroche** [comment]
I can't reproduce issue. When you upgrade to 4124 can you test again and let me know if the issue persists. Also try upgrading any plugins.

**Comment by Ghoul2077** [comment]
Tried on a fresh build of sublime text (4124) and only neovintageous installed. The bug still exists.
To reproduce there must be at least 1 lines available below the current line where you are triggering the autocomplete popup

Check as below :
![image](https://user-images.githubusercontent.com/42601281/146145944-4090aa36-4ba8-488b-91aa-11e19ca811b6.png)

Then open autocomplete on lorem and try navigating using ctrl+k and the cursor will close the popup move to next line

**Comment by gerardroche** [comment]
Try setting `"auto_complete_cycle": true` via **Menu > Preferences**

```
	// Controls what happens when pressing the up key while the first item in
	// the auto complete window is selected: if false, the window is hidden,
	// otherwise the last item in the window is selected. Likewise for the
	// down key when the last item is selected.
	"auto_complete_cycle": false,
```

**Comment by Ghoul2077** [comment]
> Try setting `"auto_complete_cycle": true` via **Menu > Preferences**
> 
> ```
> 	// Controls what happens when pressing the up key while the first item in
> 	// the auto complete window is selected: if false, the window is hidden,
> 	// otherwise the last item in the window is selected. Likewise for the
> 	// down key when the last item is selected.
> 	"auto_complete_cycle": false,
> ```

Yep that seems to have fixed it 😃
