### ISSUE TITLE
:wq saves but doesn't close unsaved files

### ISSUE THREAD

**Issue by ericstubley** [NeoVintageous/NeoVintageous#799]
**Describe the bug**  
The :wq command saves but doesn't close unsaved files. Once the file is saved :wq does close it.

**To Reproduce**  
1. open any file
2. make a change to the file
3. run :wq

**Expected behavior**  
An unsaved file should both save and close when :wq is run

**Actual behavior**  
A clear and concise description of what actually happened.

**Versions**  
Sublime stable channel, build 4121, NeoVintageous build 1.24.1, running on macOS 12.0.1.

**Additional Information**  

I'm getting this issue even on a reverted fresh Sublime text with nothing other than Package Control and NeoVintageous installed or changed.

When :wq is run on a file with unsaved changes the status bar seems to very briefly flash some message before saying the file was saved successfully. There's nothing in the Sublime console or console log if I set SUBLIME_NEOVINTAGEOUS_DEBUG=y 

This seems like such a basic issue that other people must have noticed it which makes me think it's something in my setup, but this seems to persist even with a fresh Sublime so I am confused! Happy to help debug/investigate if I get pointed in the right direction. Thank you!

**Comment by gerardroche** [comment]
When you set `SUBLIME_NEOVINTAGEOUS_DEBUG=y` you should see logging like:

```
hr evt: q (0x71)
key evt: enter
command: select
NeoVintageous: DEBUG   [     ex_cmds.py:1525] do ex cmdline >>>:wq<<<
NeoVintageous: DEBUG   [      parser.py:  79] parsing source >>>wq<<<
NeoVintageous: DEBUG   [      parser.py:  89] parsed wq {'content': 'wq', 'name': 'wq', 'target': 'wq', 'params': {}, 'forced': False, 'addressable': False, 'cooperates_with_global': False}
NeoVintageous: DEBUG   [     ex_cmds.py:1573] execute ex command: wq {'view': View(30)}
command: git_gutter {"events": 128}
command: git_gutter_blame {"is_event": true, "line": 1}
```

See https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md


I think I can reproduce the issue. If the file has unsaved changes the file is saved but not closed. If I run `:wq` again or on a file that has no unsaved changes then it closes. 

### Note about saving files that have no name i.e. not previously saved 

Only a status message is printed

![Screenshot from 2021-12-14 15-05-21](https://user-images.githubusercontent.com/44148/146024542-cda0e309-8484-4213-a257-908ea129c710.png)

From what I understand this is the same behaviour as Vim e.g.:

1. Open Vim: `vi`
2. Try to save `:wq` or create a new view and then try to save: `C-w n` then `:wq`

![Screenshot from 2021-12-14 15-07-57](https://user-images.githubusercontent.com/44148/146024870-0cbc7ecf-5f05-40d3-91bb-ea0e83c4d4ff.png)

**Comment by gerardroche** [comment]
This seems to have been introduced since ST 4114.

**Comment by gerardroche** [comment]
I just updated from 4122 to 4124 and it's fixed. I'll test again, but it looks like it was an ST internal issue. I don't see any specific fix related to this but there are some crash fixes and encoding issues that might be related https://www.sublimetext.com/dev.

**Comment by gerardroche** [comment]
Yeah, tested it again. Upgrading to 4124 should fix it. Let me know if it fixes it for you.

**Comment by ericstubley** [comment]
Ah awesome! I don't have an ST license so can't use the dev builds, but rolling back to 4113 fixed it for me. Thanks!
