### ISSUE TITLE
Delete register no longer working on selection made by other plugins

### ISSUE THREAD

**Issue by Ghoul2077** [NeoVintageous/NeoVintageous#807]
**Describe the bug**  
So I am using bracket highlighter for a long time combined with neovintageous as bracket highlighter gives easy way to select contents between brackets with a single key combination which can then be deleted using "d" or "c" keys of neovintageous but recently after last update "d" and "c" keys don't have any effect on the selections made.

**To Reproduce**  
1. Install BracketHighlighter
2. Make a new c++ file in sublime text
3. Insert round brackets with random content inside it
4. Invoke "BracketHighlighter : Select Bracket Content" from command panel while keeping cursor inside the brackets
5. Now after selection press "d" or "c" key

**Expected behavior**  
They should delete the selected content like it does in visual mode.

**Actual behavior**  
Nothing happens to the selected content.

**Versions**  
startup, version: 4126 windows x64 channel: stable
NeoVintageous v1.26.0

**Additional Information**  

Command & Input Log ->

```
command: nv_feed_key {"key": ";"}
command: nv_cmdline
command: gs_draw_status_bar
chr evt: n (0x6e)
chr evt: e (0x65)
chr evt: w (0x77)
key evt: enter
command: select
command: gs_draw_status_bar
command: new_file
command: gs_update_status
command: gs_draw_status_bar
command: nv_enter_normal_mode {"from_init": true, "mode": "mode_unknown"}
command: hide_auto_complete
command: hide_overlay
chr evt: i (0x69)
command: nv_feed_key {"key": "i"}
command: mark_undo_groups_for_gluing
command: nv_enter_insert_mode {"count": 1, "mode": "mode_internal_normal"}
key evt: shift+ctrl+p
command: nv_feed_key {"key": "<C-P>"}
command: mark_undo_groups_for_gluing
command: show_overlay {"overlay": "command_palette"}
command: gs_draw_status_bar
chr evt: s (0x73)
chr evt: s (0x73)
chr evt:   (0x20)
chr evt: c (0x63)
chr evt: + (0x2b)
chr evt: + (0x2b)
command: set_file_type {"syntax": "Packages/C++/C++.sublime-syntax"}
chr evt: ( (0x28)
command: insert_snippet {"contents": "($0)"}
chr evt: H (0x48)
chr evt: e (0x65)
chr evt: l (0x6c)
chr evt: l (0x6c)
chr evt: o (0x6f)
chr evt:   (0x20)
chr evt: W (0x57)
chr evt: O (0x4f)
chr evt: r (0x72)
chr evt: l (0x6c)
chr evt: d (0x64)
chr evt: j (0x6a)
chr evt: j (0x6a)
command: nv_enter_normal_mode {"mode": "mode_insert"}
command: hide_auto_complete
command: hide_overlay
command: glue_marked_undo_groups
key evt: shift+ctrl+p
command: nv_feed_key {"key": "<C-P>"}
command: show_overlay {"overlay": "command_palette"}
command: gs_draw_status_bar
chr evt: s (0x73)
chr evt: e (0x65)
chr evt: l (0x6c)
chr evt: e (0x65)
chr evt: c (0x63)
chr evt: t (0x74)
chr evt:   (0x20)
command: bh_async_key {"lines": true, "no_outside_adj": null, "plugin": {"command": "bh_modules.bracketselect", "type": ["__all__"]}}
command: gs_draw_status_bar
command: bracket_plugin_run
chr evt: d (0x64)
command: nv_feed_key {"key": "d"}
```
![Animation](https://user-images.githubusercontent.com/42601281/149158753-96572cb2-ce06-4160-bfda-0c1317f07f8c.gif)

**Comment by gerardroche** [comment]
Hmm, I can't reproduce the issue. Could you try get a neo log https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md

fyi you can delete the contents with the command `di(`.

You can also use any operator before `i(` e.g. `vi(` will visually select, `yi(` will yank it, `ci(` will cut it.

`i(` is a text object, there are others e.g. `i}`, `i"`, `iw`. See `:help text-objects`.

There is also `a(` which will select the text and the brackets.

**Comment by gerardroche** [comment]
There is also a plugin called surround built in. See `:help surround`.

**Comment by Ghoul2077** [comment]
> Hmm, I can't reproduce the issue. I see this:
> 
> ```
> chr evt: w (0x77)
> chr evt: o (0x6f)
> chr evt: r (0x72)
> chr evt: l (0x6c)
> chr evt: d (0x64)
> command: sublime_linter_assigned {"filename": "<untitled 25>", "linter_names": ["phpcsfixer", "php"]}
> key evt: escape
> command: nv_feed_key {"key": "<esc>"}
> command: nv_enter_normal_mode {"mode": "mode_insert"}
> command: hide_auto_complete
> command: hide_overlay
> command: glue_marked_undo_groups
> key evt: shift+ctrl+p
> command: nv_feed_key {"key": "<C-P>"}
> command: show_overlay {"overlay": "command_palette"}
> command: bh_async_key {"lines": true, "no_outside_adj": null, "plugin": {"command": "bh_modules.bracketselect", "type": ["__all__"]}}
> command: bracket_plugin_run
> chr evt: d (0x64)
> command: nv_feed_key {"key": "d"}
> command: nv_enter_visual_mode {"mode": "mode_normal"}
> command: nv_vi_d {"count": 1, "mode": "mode_visual", "register": "\""}
> command: left_delete
> command: nv_enter_normal_mode {"mode": "mode_visual"}
> command: hide_auto_complete
> command: hide_overlay
> command: sublime_linter_assigned {"filename": "<untitled 25>", "linter_names": ["phpcsfixer", "php"]
> ```
> 
> Could you try get a neo log https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md
> 
> fyi you can delete the contents with the command `di(`.
> 
> You can also use any operator before `i(` e.g. `vi(` will visually select, `yi(` will yank it, `ci(` will cut it.
> 
> `i(` is a text object, there are others e.g. `i}`, `i"`, `iw`. See `:help text-objects`.
> 
> There is also `a(` which will select the text and the brackets.

Well I didn't know those commands so thanks for the heads up but still I think I found why this issue is occurring on my side and this issue might still be a bug.
Try the steps in original post while keeping  "vintageous_reset_mode_when_switching_tabs": false and you will be able to replicate it. I myself tried it on a fresh sublime text build
