### ISSUE TITLE
NeovintageousToggleSideBar does not work

### ISSUE THREAD

**Issue by throwaway69420-69420** [NeoVintageous/NeoVintageous#811]
**Describe the bug**  
On entering NeovintageousToggleSideBar in command mode, nothing happens

**To Reproduce**  
Steps to reproduce the behaviour:
1. Press `:`
2. Type `NeovintageousToggleSideBar` and press enter

**Expected behavior**  
Side Bar should be toggled 

**Actual behavior**  
Nothing happens

**Comment by gerardroche** [comment]
It currently only works from the Command Palette.  Try `Ctrl+Shift+P` to open the command palette and type `tneo`, the `Toggle NeoVintageous` command should be first in the list, the command palette uses fuzz find search.

**Comment by throwaway69420-69420** [comment]
https://i.imgur.com/1laiLb6.png
I can only see this, plus there is no command for `NeovintageousToggleSideBar` as mentioned in https://forum.sublimetext.com/t/neovintageous-1-5-0-released-zap-kapow/35309

**Comment by gerardroche** [comment]
Did you install the **ToggleNeoVinategeous** plugin. The toggle plugin is a separate plugin:

https://packagecontrol.io/browse/authors/NeoVintageous

**Comment by throwaway69420-69420** [comment]
I did install ToggleNeoVinategeous plugin but the `:NeovintageousToggleSideBar` still does not work

I am talking about the command in this commit: https://github.com/NeoVintageous/NeoVintageous/commit/2fcad4741cb8042245c4b97b9db6d5bf7390f01e

**Comment by gerardroche** [comment]
Oh, sorry, I misread the issue. I though it was about the toggle **neovintageous** plugin.

**Comment by gerardroche** [comment]
I think it's because that command was renamed in v1.21.0

https://blog.gerardroche.com/2020/04/29/neovintageous-1.21.0/

Try

```
nnoremap <leader>d :Neovintageous action=toggle_side_bar<CR>
```

And update your Key Bindings (Menu > Preferences > Key Bindings`) with:

```
    {
        "keys": [",", "d"],
        "command": "neovintageous",
        "args": { "action": "toggle_side_bar" },
        "context": [ { "key": "control", "operand": "sidebar_tree" } ]
    },
``

**Comment by gerardroche** [comment]
You'll need to reload you rc file. Use the command palette reload rc file command, or restart sublime.

**Comment by gerardroche** [comment]
To use the command directly in ex mode:

```
:Neovintageous action=toggle_side_bar
```

**Comment by throwaway69420-69420** [comment]
`:Neovintageous action=toggle_side_bar` is working now, I haven't test
```
   {
        "keys": [",", "d"],
        "command": "neovintageous",
        "args": { "action": "toggle_side_bar" },
        "context": [ { "key": "control", "operand": "sidebar_tree" } ]
    },
``` 
yet
