### ISSUE TITLE
Sneak not working out of the box?

### ISSUE THREAD

**Issue by nk9** [NeoVintageous/NeoVintageous#812]
## Describe the bug
The NV README says "A number of popular Vim plugins have been ported and are available out-of-the-box." But when I use e.g. "sJu", I enter insert mode and the character under the cursor is replaced with "Ju". Sneak seems not to be enabled. Issue #729 implies that this should work without any changes. Unless things have changed since May 2020?

## To Reproduce
1. Install NeoVintageous via PackageControl
2. Attempt to use Sneak with the "s" key described in the documentation.

### Expected behavior
Given the wording in the README, I'd expect this to just work.

### Actual behavior
Some of the other plugins required a restart of Sublime (vim-abolish and vim-surround for example). But even after a relaunch, Sneak still isn't working.

## Versions
`startup, version: 4126 osx x64 channel: stable`
I'm using NV 1.26.1.

## Additional Information

When I press `s`, here's what shows up in the NV debug log:

```
chr evt: s (0x73)
command: nv_feed_key {"key": "s"}
command: mark_undo_groups_for_gluing
command: nv_vi_s {"count": 1, "mode": "mode_internal_normal", "register": "\""}
command: right_delete
command: nv_enter_insert_mode {"mode": "mode_internal_normal"}
```

**Comment by gerardroche** [comment]
The sneak plugin is disabled by default because it overrides some default Vim keys. 

To enable it set:

```
    "vintageous_enable_sneak": true,
```

See https://github.com/NeoVintageous/NeoVintageous/issues/731#issuecomment-624381629

**Comment by gerardroche** [comment]
I've updated the readme to note that the sneak plugin is off by default:

![Screenshot from 2022-04-03 16-41-34](https://user-images.githubusercontent.com/44148/161436009-cff467a6-4336-499a-bc79-b7a299080b92.png)

Edit preferences to turn it on: `Menu > Preferences > Settings`

```
"vintageous_enable_sneak": true,` 
```

**Comment by nk9** [comment]
Thanks, this answers the question. Happy to close this now, LMK.
