### ISSUE TITLE
Please add  'vintageous_i_escape_kj' to the available settings

### ISSUE THREAD

**Issue by effinsky** [NeoVintageous/NeoVintageous#815]
Sorry if this is a duplicate! Could we please add a 'vintageous_i_escape_kj' to the settings we have for neovintageous in ST?                                         
('vintageous_i_escape_jj' and 'vintageous_i_escape_jk'). Much appreciated small tweak :) Currently I think I need to keep a record in the keybindings file but NV could help us get rid of that.

Thanks!

**Comment by gerardroche** [comment]
If I understand correctly there are already settings for these:
Starting from version 1.21 there are two new settings that simplify mapping `jj` and `jk` to escape (you can configure settings via `Menu > Preferences > Settings`):

```
{
    "vintageous_i_escape_jj": true,
    "vintageous_i_escape_jk": true
}
```

See https://blog.gerardroche.com/2020/04/29/neovintageous-1.21.0/

**Comment by effinsky** [comment]
Yup, but I'd need kj, not jj or jk :)) "kj" is what i use--

**Comment by IshanChhangani** [comment]
Yes, please, if more such options are added like "J" or "kj"  it would be better. Or if somebody can suggest me a workaround for "J" Thanks.

**Comment by gerardroche** [comment]
Here are the escape mappings out-of-the-box:

```

    // Escape mappings.
    { "keys": ["j", "j"], "command": "nv_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}, {"key": "setting.vintageous_i_escape_jj"}]},
    { "keys": ["j", "k"], "command": "nv_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}, {"key": "setting.vintageous_i_escape_jk"}]},
    { "keys": ["k", "j"], "command": "nv_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}, {"key": "setting.vintageous_i_escape_kj"}]},

```

Yes `kj` is already there.

For `J` you could your own custom one (**Menu > Perferences > Key Bindings**):

```

    { "keys": ["J"], "command": "nv_enter_normal_mode", "args": {"mode": "mode_insert"}, "context": [{"key": "vi_insert_mode_aware"}, {"key": "setting.vintageous_i_escape_big_j"}]},
```

and then enable it:

```
{
    "vintageous_i_escape_big_j": true,
}
```

**Comment by IshanChhangani** [comment]
It worked, Thank you very much!
