### ISSUE TITLE
Allow key repeat to move the cursor when using navigation keys in Normal/Visual mode

### ISSUE THREAD

**Issue by nk9** [NeoVintageous/NeoVintageous#816]
When the user holds down the arrow keys or Page Up/Page Down for longer than half a second or so, the cursor begins to move repeatedly until the user stops pressing the key. This is standard text editor behavior, and it works this way in Vim as well.

However, when an NV user in Normal or Visual mode holds down a navigation key (e.g. "w"), NV only registers the key once. To move a second time, the user has to release the key and press it again. In Vim, after the short delay, navigation keys work like arrow keys and repeat the navigation until released.

Ideally, all the navigation keys would take advantage of the key repeat rate when in the appropriate mode, just like Vim.

NV v1.26.1
macOS 12.3
SublimeText 4126

**Comment by gerardroche** [comment]
If I understand correctly nv should do what you expect. I see you are using a mac so perhaps try this:

```
Holding down a key like j does not repeat the command                   *nv-j*

This is a feature of OS X Lion and newer versions. To make a key repeat a
command when holding it down, run this once at the terminal: >

    defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false
```

Re `:help nv`

**Comment by nk9** [comment]
Oh, great! Yeah, that was the problem. I just needed to use `com.sublimetext.4` and restart Sublime. Thanks very much!
