### ISSUE TITLE
`Esc` shouldn't close autocomplete-suggester *and* insert mode at the same time

### ISSUE THREAD

**Issue by chrisgrieser** [NeoVintageous/NeoVintageous#822]
**Describe the bug**  
When pressing `Esc` to close Sublime's autocomplete suggester, it also leaves insert mode at the same time. Often, however, I want you close the suggester, but *stay* in insert mode.

**To Reproduce**  
1. Go to Insert Mode
2. Type something which triggers a suggester
3. Press `Esc`

**Expected behavior**  
While the suggester is open, pressing `Esc` should only close the suggester, so that the user stays in insert mode.

**Versions**  

```
startup, version: 4126 osx arm64 channel: stable
```

**Additional Information**  
I assume the fix should be pretty straightforward, since the trigger for leaving Insert Mode should simply have an additional condition. At first, I thought modifying [this part of the `sublime-keymap`](https://github.com/NeoVintageous/NeoVintageous/blob/master/Default.sublime-keymap#L61) would fix it ­­­­­­however, that didn't change anything, probably I am simply missing something obvious here... 🤔 

```json
{
		"keys": ["escape"],
		"command": "nv_feed_key",
		"args": {"key": "<esc>"},
		"context": [
			{"key": "nv_command_or_insert"},
			{ "key": "auto_complete_visible", "operator": "equal", "operand": false }
		]
},
```

**Comment by gerardroche** [comment]
In the next release, 1.27.4, I added a setting: `vintageous_auto_complete_exit_from_insert_mode` (bool).

When set to `true`, `Esc` closes auto complete and enters normal mode.

When set to `false`, `Esc` will only close the auto complete.

The default is `true`.

You will want to set it to `false`.
