### ISSUE TITLE
FR: Implement `%`

### ISSUE THREAD

**Issue by chrisgrieser** [NeoVintageous/NeoVintageous#825]
goes to the other bracket, and makes it quite useful for making "smart expansion" like small macros.

**Comment by gerardroche** [comment]
This should already work e.g. place cursor on characters like `{` and `(` and press `%` and it should jump to the closing bracket `}`, `)`

**Comment by chrisgrieser** [comment]
ah yes, indeed, it works. When I tried it, it was brackets in commented code, but ti seems `%` ignores comments.
