### ISSUE TITLE
Visual Mode `Y` doesn't seem to yank

### ISSUE THREAD

**Issue by godbout** [NeoVintageous/NeoVintageous#827]
**Describe the bug**  
when in Visual Mode, yanking should be possible with uppercase `Y`.

**To Reproduce** 
1. enter Visual Mode
2. select a bunch of lines
3. press `shift y`

the selection should be yanked.

**Actual behavior**  
NeoVintageous blinks like "it didn't work"-style, and the selection is not yanked.

**Versions**  
startup, version: 4126 osx x64 channel: stable

**Comment by gerardroche** [comment]
I can't reproduce the issue, though I'm testing on linux so it could be os specific. Can you show how you're entering visual mode? And maybe some debug info: see https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md

**Comment by godbout** [comment]
my bad, i should have been more precise. it's when you're in Visual Mode Linewise (entered with `V`). the attached video shows 1) entering Visual Mode Linewise with `V`, selecting a few lines, then trying to yank with `Y`. it fails. then 2) entering Visual Mode Linewise with `V`, selecting a few lines, then trying to yank with `y`. it works.

so only the `Y` fails.

https://user-images.githubusercontent.com/121373/174633592-7d1d766b-5e03-4770-9dca-24853cd66089.mp4

i'll get the debug info. thanks!

**Comment by gerardroche** [comment]
ah yes. Pressing `y` when in visual line mode should work, but you're right `Y` should the same thing too.

**Comment by godbout** [comment]
yes! that's totally it. i'm just pointing it because the move is hardwired in my brain and i always end up using `Y` even though `y` works.

do you still need the debug info?

**Comment by godbout** [comment]
(btw the link to the contribution guide in the Debugging section is broken: https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md#debugging)
