### ISSUE TITLE
Surround doesn't work in the Visual Line mode

### ISSUE THREAD

**Issue by timfjord** [NeoVintageous/NeoVintageous#828]
**Describe the bug**  
Surround(`S`) doesn't work in the Visual Line mode but works correctly when select multiple line in Visual Model(e.g. `vii`)

**To Reproduce**  
Steps to reproduce the behaviour:
1. Make sure the surround plugin is active
2. Add multiple lines of text
3. Select them with `⇧V`
4. Type `S{` 
5. Observe the lines are deleted

**Expected behaviour**  
The lines should be wrapper in `{}`

**Actual behaviour**  
The lines are deleted

**Versions**  
`startup, version: 4126 osx x64 channel: stable`

**Comment by gerardroche** [comment]
y, visual mode works as expected:

```
f|iz|z
```

Press `S"` should 

```
f"|iz"z
```


Visual line mode should

```
|fizz|
```

Press `S"`

```
"
fizz
"
```

But it currently performs the default behaviour for `S`

```
["x]S			Delete [count] lines [into register x] and start
			insert.  Synonym for "cc" |linewise|.
```

**Comment by gerardroche** [comment]
y

**Comment by timfjord** [comment]
By the way, regarding the Surround plugin.  
When you wrap `S{` it doesn't format the code properly and literally adds `{}` at the beginning/end of the selection.  
For example, the original plugin does some formatting.  
https://user-images.githubusercontent.com/471335/174849212-c8f63116-8877-4a9c-a4df-b6485d4ab0d8.mov

It is not related, just letting you know
