### ISSUE TITLE
Support for `set clipboard`

### ISSUE THREAD

**Issue by jithu7432** [NeoVintageous/NeoVintageous#829]
```
set clipboard=unnamedplus
```
Can anyone implement this feature?

**Comment by gerardroche** [comment]
I don't yet understand the differences between unnamed and unnamedplus and the implications of them. 


I have the following mappings:

```
let mapleader=,

" Yank and paste using system clipboard.
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P
``` 

This allows me to yank to clipboard with `,y` and paste `,p`.

Does that help? There also one setting related to the clipboard:

```

    // Propagate copy actions to the system clipboard.
    "vintageous_use_sys_clipboard": false
```

**Comment by jithu7432** [comment]
setting  `"vintageous_use_sys_clipboard"` to true does it. Marking the issue as closed.

**Comment by jithu7432** [comment]
> Hmm, so `set clipboard=unnamedplus` should work the same as setting `vintageous_use_sys_clipboard` to true, `set clipboard=unnamed` should work like it does when `vintageous_use_sys_clipboard` is false, and the default should be `set clipboard=unnamed` and `vintageous_use_sys_clipboard` false (which is how it currently works by default)?

correct.

**Comment by gerardroche** [comment]
I'm going to reopen this because implementing this as option means there would be no need for preference.

**Comment by jithu7432** [comment]
Can you mention a similar PR, which implements a `set` feature. I would like to contribute this feature.

**Comment by gerardroche** [comment]
Cool. Here are some commits:

- https://github.com/NeoVintageous/NeoVintageous/commit/139455702245788d1ea6cb424e727841933f6e7d
- https://github.com/NeoVintageous/NeoVintageous/commit/2c73e43de12b9459393f258225db5d571bbf4676
- https://github.com/NeoVintageous/NeoVintageous/commit/d5ecb4724623e612f348445d5abe5f907d236079

Here is a list of PRs with the option label:

https://github.com/NeoVintageous/NeoVintageous/issues?q=label%3Aoptions+is%3Aclosed

**Comment by jithu7432** [comment]
Awesome!! I would like to know how you debug during development.
Already took a look at [CONTRIBUTING.md](CONTRIBUTING.md)

**Comment by gerardroche** [comment]
I just the debug log details in contributing and old school dump statements when I get stuck.

**Comment by jithu7432** [comment]
It is difficult to code without running debuggers and setting breakpoints. Saw an answer in stackoverflow that says you can connect the debugger with the plugin host PID, but that is not working for me.

**Comment by gerardroche** [comment]
Moved to the roadmap:

https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md
