### ISSUE TITLE
Optimize gj & gk motions

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#83]
<a href="https://github.com/albertxing"><img src="https://avatars2.githubusercontent.com/u/2881206?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [albertxing](https://github.com/albertxing)**
_Tuesday Oct 07, 2014 at 23:34 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/762_

----

Currently `gj` and `gk` are implemented in a very inefficient manner (i.e. it will often lag during normal use).

Sublime's Vintage mode maps j to gj and k to gk by default, and it doesn't exhibit slow performance.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Oct 13, 2014 at 17:59 GMT_

----

Can you please indicate repro steps and platform details?

**Comment by gerardroche** [comment]
<a href="https://github.com/albertxing"><img src="https://avatars2.githubusercontent.com/u/2881206?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albertxing](https://github.com/albertxing)**
_Monday Oct 13, 2014 at 18:03 GMT_

----

In `.vintageousrc` I use

```
:map j gj
:map k gk
```

On larger files and especially on my slower machine, Sublime will stutter and lag when <kbd>j</kbd> is pressed continuously.

I'm on Windows 8.1.

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Oct 13, 2014 at 18:05 GMT_

----

IIRC, Vintageous uses native ST commands for this. In fact, I had to reimplement `j` and `k` so they were faster than their native version. Can you confirm you don't see this lag in plain ST or Vintage under the same circumstances?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Oct 13, 2014 at 18:06 GMT_

----

Can you also please define 'large file' so that I can try and repro this?

**Comment by gerardroche** [comment]
<a href="https://github.com/guillermooo"><img src="https://avatars1.githubusercontent.com/u/684948?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [guillermooo](https://github.com/guillermooo)**
_Monday Oct 13, 2014 at 18:10 GMT_

----

Also, for my reference, the API doesn't allow such granular control as to replicate `gk` and `gj` without resorting to using native commands.

**Comment by gerardroche** [comment]
<a href="https://github.com/albertxing"><img src="https://avatars2.githubusercontent.com/u/2881206?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albertxing](https://github.com/albertxing)**
_Monday Oct 13, 2014 at 18:13 GMT_

----

I think the problem only exists on slower machines (e.g. without enough graphics power).
By large file I mean roughly >500 lines.

In general this is something that I have failed to constantly reproduce on my laptop (with integrated graphics), and have not yet thoroughly tested this on various older machines. If possible, try finding a machine with no discreet or integrated graphics (i.e. a Core 2 processor).

However the lag is significant enough when it does appear to be a cause of concern, hence the issue.

**Comment by gerardroche** [comment]
<a href="https://github.com/albertxing"><img src="https://avatars2.githubusercontent.com/u/2881206?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [albertxing](https://github.com/albertxing)**
_Monday Oct 13, 2014 at 18:15 GMT_

----

I do recall, however, testing out the built-in Vintage on a machine that was lagging considerably with Vintageous, and Vintage mode worked more or less okay.

**Comment by gerardroche** [comment]
Please open an issue specific to NeoVintageous with debugging information: read the [debugging](https://github.com/NeoVintageous/NeoVintageous#debugging) section in readme for detailed information of debugging.

**Comment by nimafazeli** [comment]
I have mapped my motion keys to move by visual line instead of logical lines i.e:
```
noremap j gj
noremap k gk
```
However it suddenly started to be very slow. Console log is filled with lines like following : 
```
2018-09-14 19:43:44,930 - INFO - key evt: g repeat_count=None do_eval=False check_user_mappings=False
2018-09-14 19:43:44,930 - DEBUG - sequence >>>g<<<
2018-09-14 19:43:44,945 - DEBUG - partial sequence >>>g<<<
2018-09-14 19:43:44,945 - DEBUG - resolved None -> g -> <ViOpenNameSpace (<unset>)>
2018-09-14 19:43:44,945 - INFO - opening namespace
2018-09-14 19:43:44,945 - DEBUG - key evt took 0.0156s
2018-09-14 19:43:44,945 - INFO - key evt: j repeat_count=None do_eval=False check_user_mappings=False
2018-09-14 19:43:44,945 - DEBUG - sequence >>>gj<<<
2018-09-14 19:43:44,945 - DEBUG - partial sequence >>>gj<<<
2018-09-14 19:43:44,945 - DEBUG - resolved None -> gj -> <ViMoveByScreenLineDown (<unset>)>
2018-09-14 19:43:44,945 - DEBUG - key evt took 0.0000s
2018-09-14 19:43:44,945 - INFO - view.run_command() {'is_jump': True, 'motion_args': {'count': 1, 'mode': 'mode_normal'}, 'motion': '_vi_gj'}
2018-09-14 19:43:44,945 - DEBUG - sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - partial sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - partial sequence >>><<<
2018-09-14 19:43:44,961 - DEBUG - key evt took 0.0312s
```
Please let me know whether you need me to send more information.
Thanks in advance for any hint.
