### ISSUE TITLE
Surround "Replacement" not working as intended

### ISSUE THREAD

**Issue by skopjanecot** [NeoVintageous/NeoVintageous#830]
Are "Replacements" from the "Surround" plugin implemented in NeoVintageous? If I enter the command as bellow I only get the word wraped around in "f"s.
  Old text                  Command           New text ~
  "hello"                   ysWfprint<cr>     print("hello")

**Comment by gerardroche** [comment]
It's hard to read the example you posted.

**Comment by skopjanecot** [comment]
Hey, sorry for not being more specific.
Basically "Replacements" are a feature in the "Surround" plugin. They are listed in the NeoVintageous help page, so I thought they might be implemented and I have missed something.

As you wrote, it should prompt for a function to be inserted.

Sorry for the bad formating in the original post, I didn't review the post because I was in hurry.
Let me know if I can update in any way.
