### ISSUE TITLE
vat/vit commands are broken

### ISSUE THREAD

**Issue by titouandk** [NeoVintageous/NeoVintageous#832]
**Describe the bug**  
The `vat` and `vit` vim commands are broken under certain circumstances.

On the same JSP files, those commands work on some tags, and fail on others.

**Example of broken `vat` behavior**

https://user-images.githubusercontent.com/5413308/177322428-23b3f56b-1123-4302-9c02-3ec76a105003.mp4

Sublime Console Output:
```
command: nv_feed_key {"key": "v"}
command: nv_enter_visual_mode {"mode": "mode_internal_normal"}
chr evt: a (0x61)
command: nv_feed_key {"key": "a"}
chr evt: t (0x74)
command: nv_feed_key {"key": "t"}
command: nv_vi_select_text_object {"count": 1, "inclusive": true, "mode": "mode_visual", "text_object": "t"}
```

`test.jsp` file content:

```JSP
<%-- Fil d'Ariane --%>
<div class="container mt-2 mt-lg-3">
	<nav aria-label="breadcrumb">
		<ol class="breadcrumb">
			<li class="breadcrumb-item"><a href="${RootPath}">Accueil</a></li>
			<li class="breadcrumb-item active" aria-current="page">Current page</li>
		</ol>
	</nav>
</div>

<%-- Titre de la page --%>
<div class="container">
	<h1 class="h1 mb-4">Current page</h1>
</div>
```

**Example of expected `vat` behavior**

https://user-images.githubusercontent.com/5413308/177322527-704179e4-b7f7-4976-bc96-089b586edae7.mp4

**Version**

Sublime Text 4121 on Windows (channel "stable").

**Comment by gerardroche** [comment]
I can't reproduce the issue. I'm on build 4131 and linux so it could be as OS specific bug or a fix in one of the recent bugs. I'll try test on a older build.

**Comment by titouandk** [comment]
Thank you for your answer,

I updated to Sublime Text **4126** on Windows and it works fine now.
