### ISSUE TITLE
Exits to normal mode when ST window loses focus

### ISSUE THREAD

**Issue by Amparose** [NeoVintageous/NeoVintageous#834]
**Describe the bug**  
I really hope that this might just be a setting I haven't tweaked because it is super frustrating that my vim mode is always exited whenever Sublime Text loses focus.

**To Reproduce**  
1. Enter insert mode.
2. Switch to another app and back to ST.

**Expected behavior**  
ST should still be in Insert mode.

**Actual behavior**  
ST is in Normal mode.

**Versions**  
Neovim 1.26.3
ST Build 4126
MacOS 11.6

**Comment by itsmewes** [comment]
Hey @Amparose,
Add `"vintageous_reset_mode_when_switching_tabs": false,` to your Sublime setting and it should change the functionality to match what you expect.

**Comment by gerardroche** [comment]
Yes, setting `vintageous_reset_mode_when_switching_tabs` to false should get you what you want. There is also a default mode option, currently only supports insert mode, so if you wanted to default to insert mode instead of normal mode set `vintageous_default_mode` to "insert":

```
'vintageous_default_mode'
                        string (default "")
        The default mode to use when activating or switching views.

        Valid values are: "insert" or "".

        mode   | description
        ------ | -----------
        insert | Enter insert mode when opening or switching views or when the
                 window receives focus and is not in visual mode i.e. visual
                 mode selections are retained when the window loses focus.
````

See https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L728

**Comment by gerardroche** [comment]
Reworking the mode handling is a long standing issue. It's a difficult one to do right. It's on the [roadmap](https://github.com/NeoVintageous/NeoVintageous/issues/711)

> In Vim, the cursor is generally not reset to normal mode. When you enter
insert mode and move to another view, you stay in insert mode. When you
enter visual mode & move to another view the visual mode is cleared and
changes to normal mode and then the cursor moves to the other view and
stays in normal mode. Making NeoVintageous work like this will require
significant resign of how the mode state is handled.
> https://github.com/NeoVintageous/NeoVintageous/commit/239b3bf69b52728cb2177b3ec6297ed3168fb346
