### ISSUE TITLE
NeoVintageous adds too many jumps to the jumplist

### ISSUE THREAD

**Issue by lucypero** [NeoVintageous/NeoVintageous#835]
**Describe the bug**  
It adds jumps that clearly should not be added. For example, simply clicking on another character adds a jump to the list.

**To Reproduce**  
1. Click on a line 2 lines away from the cursor
2. Repeat `1`
3. press `C-O`
4. Repeat `3`
5. Observe how it puts you back to where you were

**Expected behavior**  
Add jumps to the jumplist less often, or let us customize the behavior. At least don't add jumps just for clicking.

**Comment by gerardroche** [comment]
Dup of https://github.com/NeoVintageous/NeoVintageous/issues/778
