### ISSUE TITLE
Add show char's ascii info that is under cursor in statusbar

### ISSUE THREAD

**Issue by NEX-S** [NeoVintageous/NeoVintageous#840]
Will vintageous add show char's ascii info that is under cursor in statusbar?

**Comment by gerardroche** [comment]
The command `ga` should get you what you need. 

```
ga			Print the ascii value of the character under the
			cursor in decimal, hexadecimal and octal.
			Mnemonic: Get Ascii value.

			For example, when the cursor is on a 'R':
				<R>  82,  Hex 52,  Octal 122 ~

```

**Comment by gerardroche** [comment]
No, I think that would need a `:statusline` feature

**Comment by gerardroche** [comment]
I implemented this as a plugin because it's useful outside of the context of NeoVintageous. It has been submitted to Package Control. https://github.com/gerardroche/sublime-show-ascii-value
