### ISSUE TITLE
Caret speed is slow  in command mode

### ISSUE THREAD

**Issue by IshanChhangani** [NeoVintageous/NeoVintageous#843]
I have observed that the movement speed of the cursor is quite slow in the command mode(when using j,k,h,l) , I searched net to increase caret speed in sublime but did not find a solution. Can somebody help.

**Comment by gerardroche** [comment]
Are you using osx? try

```

Holding down a key like j does not repeat the command                   *nv-j*

This is a feature of OS X Lion and newer versions. To make a key repeat a
command when holding it down, run this once at the terminal: >

    defaults write com.sublimetext.3 ApplePressAndHoldEnabled -bool false
```

**Comment by IshanChhangani** [comment]
Thank you for your reply, But I am on arch linux with kde plasma desktop environment. Pressing j does repeat the command in my case but the caret is quite slow as compared to normal vim or vscode-vim.

```command: mark_undo_groups_for_gluing
command: nv_enter_insert_mode {"count": 1, "mode": "mode_internal_normal"}
chr evt: J (0x4a)
command: nv_enter_normal_mode {"mode": "mode_insert"}
command: hide_auto_complete
command: hide_overlay
command: glue_marked_undo_groups
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}```


Not sure if you asked for this or if this can be helpful but this is what I get by using the guide you sent.

**Comment by gerardroche** [comment]
Set `SUBLIME_NEOVINTAGEOUS_DEBUG` env for more nv debug logs which will contain some timing logging. https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md

**Comment by IshanChhangani** [comment]
Thank you for your reply I did that as well , but there doesn't seems to be any change in the output.
`command: drag_select {"event": {"button": 1, "x": 227.38168022, "y": 191.592743121}}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
command: inteli_sense {"action": "stop_sense"}
command: inteli_sense {"action": "run_sense"}
command: inteli_sense {"action": "stop_sense"}
command: inteli_sense {"action": "run_sense"}
command: inteli_sense {"action": "stop_sense"}`

If there is anything else please tell me, but I don't think it has something to do with my setup specifically , I am searching for some option inside sublime which can increase the caret speed.

**Comment by gerardroche** [comment]
Sorry, try:

```
export SUBLIME_NEOVINTAGEOUS_DEBUG=y; subl
```

The contributing guide was missing the `export` part.

**Comment by IshanChhangani** [comment]
Thanks for reply , Hope this is helpful,
`command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0025 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0015 secs
command: drag_select {"event": {"button": 1, "x": 1415.33396049, "y": 761.388884551}}
command: drag_select {"event": {"button": 1, "x": 1638.09976371, "y": 764.399244106}}
command: drag_select {"event": {"button": 1, "x": 1331.04423745, "y": 695.161261428}}
command: drag_select {"event": {"button": 1, "x": 1493.60307925, "y": 708.707793299}}
command: drag_select {"event": {"button": 1, "x": 1614.01700211, "y": 758.378582413}}
command: drag_select {"event": {"button": 1, "x": 83.2549388523, "y": 78.0398924174}}
command: view_tester {"action": "get_var_value", "pos": 26}
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0060 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0057 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0059 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0049 secs
chr evt: l (0x6c)
command: nv_feed_key {"key": "l"}
NeoVintageous: INFO    [    commands.py: 502] key evt: l count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveRightByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveRightByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_l', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_l {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0058 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0055 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0050 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0051 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0045 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0050 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0038 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0039 secs
chr evt: h (0x68)
command: nv_feed_key {"key": "h"}
NeoVintageous: INFO    [    commands.py: 502] key evt: h count=None eval=True mappings=True
NeoVintageous: DEBUG   [    commands.py: 527] mode: mode_normal
NeoVintageous: INFO    [    mappings.py: 192] resolved <ViMoveLeftByChars> mode=None sequence=None (<class 'NeoVintageous.nv.vi.cmd_defs.ViMoveLeftByChars'>, <class 'NeoVintageous.nv.vi.cmd_base.ViMotionDef'>, <class 'NeoVintageous.nv.vi.cmd_base.ViCommandDefBase'>, <class 'object'>)
NeoVintageous: DEBUG   [       state.py: 243] evaluating...
NeoVintageous: DEBUG   [       state.py: 301] motion: {'motion': 'nv_vi_h', 'motion_args': {'mode': 'mode_normal', 'count': 1}}
command: nv_vi_h {"count": 1, "mode": "mode_normal"}
NeoVintageous: INFO    [    commands.py: 511] key processed in 0.0044 secs`

**Comment by gerardroche** [comment]
On my system I get presses as low as 0.0007. It looks like your key presses are
being throttled, probably at the OS level.

See https://github.com/NeoVintageous/NeoVintageous/issues/381#issuecomment-481460821
for some details on how to configure Ubuntu key press interval and delay. Try
playing around with different values to find the best performance. Remember, if
you set the interval to low it will actuall degrade performance. You need to
play around with different values to find the sweet spot.

My current config on this laptop, which performs fairly well, is:

    org.gnome.desktop.peripherals.keyboard delay 150
    org.gnome.desktop.peripherals.keyboard repeat true
    org.gnome.desktop.peripherals.keyboard repeat-interval 3

**Comment by IshanChhangani** [comment]
Thank you for your input , I am on kde plasma and the problem was solved with the delay and repeat settings given in systemsettings5.

**Comment by gerardroche** [comment]
It would be great if you could an example fix for kde in docs here:

https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt#L880

**Comment by IshanChhangani** [comment]
Added a pull request https://github.com/NeoVintageous/NeoVintageous/pull/845
