### ISSUE TITLE
How to make Tab key work properly with snippets that use fields/placeholders/variables

### ISSUE THREAD

**Issue by blackace72** [NeoVintageous/NeoVintageous#853]
## Environment

Macbook Air (M1, 2020)
macOS 12.3.1
Sublime Build 4113
NeoVintageous 1.27.2

## Issue

After **visually** selecting text and activating a sublime-snippet on that text, I cannot use the <kbd>Tab</kbd> key to jump to different placeholders/fields (things like `$1`, `${1:SELECTION}`). However, <kbd>Tab</kbd> does work properly with the snippet if I select the text with **insert mode**.

### First: Create a snippet

- Create a snippet that uses fields/placeholders. You can do this by either creating a `.sublime-snippet` file, or setting a key bind to run the `insert_snippet` command in your `.sublime-keymap` file.
- I used the second way and will show what I have written

```json
[
	{ "keys": ["ctrl+6"], "command": "insert_snippet", "args": { "contents": "{{c${2:1}::${1:$SELECTION}}}"}}
]
```

### Second: Using the snippet (and Tab)

1. Open a blank document and make sure you're in Normal Mode (with block cursor)
2. Press <kbd>i</kbd> to enter Insert Mode, then type the word `foo`, then press <kbd>Esc</kbd> to return to Normal Mode
3. Type <kbd>v</kbd><kbd>i</kbd><kbd>w</kbd> to select the word in Visual Mode
4. Press <kbd>Ctrl</kbd>+<kbd>6</kbd> to activate the snippet on the select text
5. Press <kbd>Tab</kbd>

**Note**: After pressing <kbd>Tab</kbd>, at the bottom of the screen it says "Field 1 of 3; Already at newest postion"

### Option 1: Manual Selection With Mouse/Trackpad Using Insert Mode

1. Open a blank document and make sure you're in Normal Mode (with block cursor)
2. Press <kbd>i</kbd> to enter Insert Mode, then type the word `foo`
3. Use your mouse/trackpad to manually select the word
4. Press <kbd>Ctrl</kbd>+<kbd>6</kbd> to activate the snippet on the select text
5. Press <kbd>Tab</kbd>

**Note**: Notice that the new highlighted character is the number `1`; and also that we are in Insert Mode

### Option 2: Visual Mode Selection, Then <kbd>Esc</kbd>, Then <kbd>i</kbd>, Then <kbd>Tab</kbd>

1. Open a blank document and make sure you're in Normal Mode (with block cursor)
2. Press <kbd>i</kbd> to enter Insert Mode, then type the word `foo`, then press <kbd>Esc</kbd> to return to Normal Mode
3. Type <kbd>v</kbd><kbd>i</kbd><kbd>w</kbd> to select the word in Visual Mode
4. Press <kbd>Ctrl</kbd>+<kbd>6</kbd> to activate the snippet on the select text
5. Press <kbd>Esc</kbd> (returns to Normal Mode)
6. Press <kbd>i</kbd> (enters Insert Mode)
7. Press <kbd>Tab</kbd>

### Use NeoVintageosrc File To Make Macro (Simulating Option 2 Behavior)

Because Option 2 seems simple to do (activate the snippet then press <kbd>Esc</kbd>, then <kbd>i</kbd>, then <kbd>Tab</kbd>) and repetitive, I wanted to just make it like a "macro" by binding it to a key bind.

In the RC file, I put this:

```vimrc
vnoremap ' <Esc>i<Tab>
```
However, when I activate the snippet and then press <kbd>'</kbd>, a tab is created between two `fo` and `o`, like this:

```plain
{{c1::fo	o}}
```
Which is *not* the desired behavior.

---

I then tried to use `<C-i>` because I read that this is the same as Tab, so I used this instead:

```vimrc
vnoremap ' <Esc>i<C-i>
```

But then the result is 

```plain
{{c1::fo<C-i>o}}
```
If I instead try to do <kbd>v</kbd><kbd>i</kbd><kbd>w</kbd>, then activate the snippet, then press <kbd>Ctrl</kbd>+<kbd>i</kbd> I get (again):
"Already at newest position"

---

So then I tried to use this in my `Preferences.sublime-settings` file:

```json
"vintageous_handle_keys": {
		"v_<C-i>": false,
		"s_<C-i>": false,
		"v_<Tab>": false,
		"s_<Tab>": false,
	},
```

I then again tried: 
<kbd>v</kbd><kbd>i</kbd><kbd>w</kbd>, then activate the snippet, then press <kbd>Ctrl</kbd>+<kbd>i</kbd>
(but this time I don't get the "Already at newest position" text)

And using <kbd>'</kbd> after activating the snippet still produces this:
```plain
{{c1::fo<C-i>o}}
```

**Comment by gerardroche** [comment]
I added the ability to disable the `<Tab>` key via `vintageous_handle_keys` in
the develop branch:

https://github.com/NeoVintageous/NeoVintageous/commit/c984f2ebfdf43ad4b04e7c8698375f724000a017

You can now disable the `<Tab>` key making it fallback to ST:

```
"vintageous_handle_keys":
{
    "<Tab>": false,
}
```

I think it kind of solves the problem, but I think there are still some issues.
Let me know how this works for you.

**Comment by blackace72** [comment]
So far it is working great, at least for my intended purposes! I will let you know if I spot anything weird, but so far so good. Thanks again!
