### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by jyc** [NeoVintageous/NeoVintageous#856]
Hi—thank you for the excellent package! If you were interested & wanted to use GitHub Sponsors, I'd definitely donate without any expectations. Others might be interested too. I would definitely donate $5/mo.

**Comment by gerardroche** [comment]
I appreciate it but there's no current plan to accept donations. I prefer not to deal with the administrative workload. There's no direct costs involved with the project. No hosting or server costs. CI and [my blog](https://blog.gerardroche.com/) are hosted by GitHub for free. Thanks all the same.
