### ISSUE TITLE
ZZ doesn't save and close a new file

### ISSUE THREAD

**Issue by eproxus** [NeoVintageous/NeoVintageous#859]
**Describe the bug**  
I have `$EDITOR` set to `subl -w` and want to use the `ZZ` command after being done with the file (e.g. when making a Git commit). However, this brings up a save dialog that I have to manually confirm. This behaviour doesn't exist in Vim/Nvim which just saves the file (because I just told it to 😄) 

**To Reproduce**  
1. Call `subl -w foo` from the shell (`foo` must not already exist)
2. Go to normal mode and press `ZZ`

**Expected behavior**  
The file is silently saved and closed.

**Actual behavior**  
A dialog shows _Do you want to save the changes made to foo?_ in which I have to press enter again.

**Versions**  
`startup, version: 4148 osx arm64 channel: dev`

NeoVintageous v1.27.4.

**Comment by gerardroche** [comment]
This is caused by a race condition due to views being saved asynchronously The
commands that quit or close immediately after saving should be saved
synchronously to avoid this.

Perhaps this is what was causing https://github.com/NeoVintageous/NeoVintageous/pull/819.
