### ISSUE TITLE
Allow rebinding commands within the Multiple Cursors "mode"

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#865]
As far as I understand, the multiple cursors mode commands can't be rebound within .neovintageousrc or config, only the first `gh` command can be changed

**Comment by gerardroche** [comment]
Try `snoremap`:

```
snoremap <space> :ls<CR>
```

**Comment by eugenesvk** [comment]
Oh, so it's just a regular select mode, I thought it was a special "multiple cursor" submode that had special keybinds

So then 
> start:      <C-n> or gh     Start multiple cursor.

mean something like?

> Enter the select mode with the multiple cursor functionality

**Comment by gerardroche** [comment]
Yes. Multiple cursor mode uses select mode. I don't know if this is the case in Vim, but in nv it was easier to implement this way.
