### ISSUE TITLE
Multiple cursors: yanked value should paste straight after multi-cursor select

### ISSUE THREAD

**Issue by asfaltboy** [NeoVintageous/NeoVintageous#871]
**Describe the bug**  

The behavior of copy paste is somewhat unintuitive. If I yank 1 item, and then select multiple cursors, I should be able to simply press 'p' to replace all the selected values. However, pasting does work if re-selecting (e.g `vvw`) and then hitting 'p'.

I believe that the original extension does support it, if I understand [this spec](https://github.com/terryma/vim-multiple-cursors/blob/6456718e1d30b42c04b920c5413ca44f68f08759/spec/multiple_cursors_spec.rb#L389-L403) correctly.

Note: I came across issue https://github.com/NeoVintageous/NeoVintageous/issues/786 which I think was the last reported issue with multiple cursors and copy-paste behavior.

**To Reproduce**  
1. Yank a word
2. Select multiple items (`<C-n>`)
3. Hit `p`
4. Nothing happens

**Expected behavior**  

The multiple items that are already selected should be replaced with the yanked item.

**Actual behavior**  

Nothing happens when 'p' is pressed.

**Versions**  
startup, version: 4143 osx x64 channel: stable

**Additional Information**  
I'm running NeoVintageous from a local directory using the latest master.

Logs:
```
command: nv_enter_normal_mode {"mode": "mode_visual"}
command: hide_auto_complete
command: hide_overlay
command: git_gutter {"events": 128}
command: nv_feed_key {"key": "y"}
command: nv_feed_key {"key": "i"}
command: nv_feed_key {"key": "w"}
command: nv_vi_y {"count": 1, "mode": "mode_internal_normal", "motion": {"motion": "nv_vi_select_text_object", "motion_args": {"count": 1, "inclusive": false, "mode": "mode_internal_normal", "text_object": "w"}}, "register": "\""}
command: nv_vi_select_text_object {"count": 1, "inclusive": false, "mode": "mode_internal_normal", "text_object": "w"}
command: nv_enter_normal_mode {"mode": "mode_internal_normal"}
command: hide_auto_complete
command: hide_overlay
command: nv_feed_key {"key": "W"}
command: nv_vi_big_w {"count": 1, "mode": "mode_normal"}
command: nv_feed_key {"key": "<C-n>"}
command: nv_enter_select_mode {"mode": "mode_internal_normal"}
command: find_under_expand
command: nv_feed_key {"key": "<C-n>"}
command: nv_vi_select_j {"count": 1, "mode": "mode_select"}
command: find_under_expand
command: nv_feed_key {"key": "p"}
```

> ... will provide the following if needed
> Running `$ SUBLIME_NEOVINTAGEOUS_DEBUG=y; subl` (unix), `> set SUBLIME_NEOVINTAGEOUS_DEBUG=y& "C:\Program Files\Sublime Text 3\subl.exe"` (windows), will run NeoVintageous in debug mode. Debug messages are printed to the console log. See the [contributing guide](https://github.com/NeoVintageous/NeoVintageous/blob/master/CONTRIBUTING.md) for additional debugging instructions.
> 
> You may also want to review the help file: `:help neovintageous`, or visit the [online help file](https://github.com/NeoVintageous/NeoVintageous/blob/master/res/doc/neovintageous.txt).

**Comment by gerardroche** [comment]
I haven't deep dived into this yet, but I see that you need to escape to normal
mode, make the visual selection, and then paste. Which is fine if you want to
paste to an alternate visual selection and not the initial multiple cursor, but
yes it should allow an immediate paste to the multiple cursor.

I have a fix.
