### ISSUE TITLE
More ergonomic command mappings: how much work would that be?

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#872]
I briefly mentioned this in https://github.com/NeoVintageous/NeoVintageous/issues/864, but this is a more important and more general issue.

Would you please explain roughly what type of work would be needed to replace the unergonomic config 
`map  k j` with something like
`map k move-line-down`

Is it "only" replacing the parser that would map `move-line-down` to `j` (and could potentially be done incrementally, where you could have a special `['cmd1', 'cmd2']` syntax that would flow through the new parser) or would it be much more involved and require changing all `j` references in the plugin?

**Comment by gerardroche** [comment]
It's a whole a new layer and I don't see the point. I wouldn't even know to start because it's not clear to me what it is that you're trying to achieve. Why can't you map `noremap k j`?

**Comment by gerardroche** [comment]
Is is simply that you feel `map k move-line-down` is a nicer way to write mappings instead of `map k j`? If that's the case you could write a plugin with a simple translation map that takes your config file and outputs a neovintageousrc file.

**Comment by eugenesvk** [comment]
> It's a whole a new layer and I don't see the point. I wouldn't even know to start because it's not clear to me what it is that you're trying to achieve.

a readable large config file

>   Why can't you map `noremap k j`?

Because this is a very unergonomic way to configure: why does it requires me to remember all the many bad default keybinds of vim even though I use almost none of them?
It's also not nestable, has no comments, breaks the convenience of copy&pastes of sublime commands (`MoveTo` instead of `move_to` and manual remap of arguments), has no syntax highlighting, no imports etc.

> case you could write a plugin with a simple translation map that takes your config file and outputs a neovintageousrc file

I've thought about that, but then I already have one level of indirection where I use chezmoi config manager to allow comments, some variables, splitting config file by mode (so instead of one huge file I have normal mode mappings, visual mode etc.), and some x-platform modifier substitution
So it'd be better to do feed the alternative config format directly to whatever plugin command importer rather than trying to match this poor intermediate layer

**Comment by gerardroche** [comment]
What you're asking for is a completely new format for the neovintageousrc. A new format like this is a no go. I think it's overkill. The neovintageousrc tries to emulate the vimrc as best and reasonable as possible. It's not possible or reasonable to implement some things in Vim, it's always a work in progress. And some things need to adapt to Sublime Text so there are some trade-offs and compromises.

**Comment by eugenesvk** [comment]
> The neovintageousrc tries to emulate the vimrc as best and reasonable as possible

and it can continue to do so, why does that mean that no progress is possible?

For example, you can have a proper config format that is loaded after `.neovintageousrc`, so for compatibility with vimrc you'd use it, but since this is Sublime Text, for compatibility with ST you'd use this format that would allow you to copy&paste ST commands without having to convert them to vimrc

**Comment by gerardroche** [comment]
There has been massive progress on implementing features, see https://blog.gerardroche.com.

I know it can be done in addition to neovintageousrc. I don't see enough value in adding a new config format.

**Comment by eugenesvk** [comment]
> There has been massive progress on implementing features

I obviously meant progress in configuring the plugin

> I know it can be done in addition to neovintageousrc. 

Then why did you bring backward compatibility as a blocker if it doesn't block?

> I don't see enough value in adding a new config format.

Out of curiosity, is it because you don't use many rebindings?

**Comment by gerardroche** [comment]
I don't remember saying backwards compatibility was an issue.

I mostly use leader key bindings. A few mappings are there to test NeoVintageous. 

```
set ignorecase
set nominimap
set smartcase

let mapleader=,

nnoremap <leader><leader> :RevealInSideBar<CR>
nnoremap <leader>G :GsShowStatus<CRl
nnoremap <leader>c :CopyRelativeFilePath<CR>
nnoremap <leader>d :Neovintageous action=toggle_side_bar<CR>
nnoremap <leader>ek :OpenKeyBindings<CR>
nnoremap <leader>en :Neovintageous action=open_rc_file<CR>
nnoremap <leader>ep :OpenPreferences<CR>
nnoremap <leader>g/ :ToggleInlineDiff<CR>
nnoremap <leader>g; :ToggleInlineDiff prefer_hide=true<CR>
nnoremap <leader>ga :silent !git add %<CR>
nnoremap <leader>gb :GitGutter action=blame<CR>
nnoremap <leader>gf :ShowOverlay overlay=goto text=@<CR>
nnoremap <leader>gs :!git status<CR>
nnoremap <leader>gu :GenerateUnitTest<CR>
nnoremap <leader>gv :FindFileUnderCursor<CR>
nnoremap <leader>hm :RevertModification<CR>
nnoremap <leader>hp :PasteFromHistory<CR>
nnoremap <leader>hu :RevertHunk<CR>
nnoremap <leader>o :ls<CR>
nnoremap <leader>q gqip:w<CR>
nnoremap <leader>r :reg<CR>
nnoremap <leader>sr :SublimeLinterLineReport<CR>
nnoremap <leader>st :SublimeLinterPanelToggle<CR>
nnoremap <leader>sv <C-w><C-v><C-w>h<C-w>q<C-w>l
nnoremap <leader>x :GitOpen<CR>
noremap <C-l> :nohlsearch<CR>
noremap <C-s> :w<CR>
noremap <D-I> :ShowOverlay overlay=goto text=@<CR>
noremap <D-i> :GotoSymbolInProject<CR>
noremap <leader>/ :ToggleInlineDiff<CR>
noremap <space> :

" Yank and paste using system clipboard.
noremap <leader>y "+y
noremap <leader>Y "+Y
noremap <leader>p "+p
noremap <leader>P "+P

" Sorting.
nnoremap <leader>s) vi):sort u<CR>
nnoremap <leader>s] vi]:sort u<CR>
nnoremap <leader>si vii:sort u<CR>
nnoremap <leader>sp vip:sort u<CR>
nnoremap <leader>ss vip:sort u<CR>
vnoremap <leader>s :sort u<CR>

" Plugin: User - Finders
nnoremap <leader>f  :FindInOpenFolders interactive=true filter=true include_vendor=true<CR>
noremap <C-S-f3>    :FindInOpenFolders interactive=true filter=true<CR>
noremap <C-S-f4>    :FindInOpenFolders interactive=true filter=true include_vendor=true<CR>
noremap <C-f3>      :FindInOpenFolders interactive=true<CR>
noremap <S-f3>      :FindInOpenFolders interactive=false<CR>

" Plugin: User - Debug
nnoremap <leader>vd :DumpVariable phpfunc=dump<CR>
nnoremap <leader>vm :DumpVariable phpfunc=dump content=__METHOD__<CR>
nnoremap <leader>vp :DumpVariable phpfunc=print_r<CR>
nnoremap <leader>vr :DumpVariable sublime_region_view_string=true<CR>
nnoremap <leader>vv :DumpVariable phpfunc=dd<CR>

" Plugin: Test https://github.com/gerardroche/sublime-test
nnoremap <D-n> :TestNearest<CR>
nnoremap <leader>T :TestFile<CR>
nnoremap <leader>a :TestSuite<CR>
nnoremap <leader>gg :TestVisit<CR>
nnoremap <leader>l :TestLast<CR>
nnoremap <leader>t :TestNearest<CR>

" Plugin: Origami https://packagecontrol.io/packages/Origami
nnoremap <C-w>z :ToggleZoomPane fraction=0.98<CR>
nnoremap <leader>. :ToggleZoomPane fraction=0.98<CR>
nnoremap <leader>wd :DestroyPane direction=self<CR>
nnoremap <leader>ws :CarryFileToPane direction=down<CR>
nnoremap <leader>wv :CarryFileToPane direction=right<CR>
nnoremap <leader>ww :UserDefaultSetLayout<CR>

" LSP
nnoremap FileType php gd :LspSymbolDefinition<CR>
nnoremap FileType go,html gd :LspSymbolDefinition<CR>
```

**Comment by eugenesvk** [comment]
Ok, so now imagine that all of your config is just one leader submode. Moreover, that submode is repeated with an extra modifier, so you have to remember to edit in two places should you want to change anything
Basically, it's like having no modules in your plugin

And then your config is mostly readable commands (which is exactly what I mean a config should be), but then imagine you can't read it because it's all `bhkgde` which you don't remember because you don't use `b` to perform the b function etc 

It shouldn't be that hard to see how the current config is unsuitable for anything more than a couple of dozen of lines

**Comment by gerardroche** [comment]
I think it's fine. Post your current configuration so I can understand what is your dealing with.

**Comment by eugenesvk** [comment]
Wow, how is it fine having to edit same code in different places instead of only one place and learn a foreign language to read it?

I haven't ported my config fully to nv yet, but FYI these are the source module configs with variables that allow inserting same group of commands under slightly different leader submode

https://github.com/eugenesvk/kbdHelix/tree/modifew/src

And this is the resulting config a couple of orders of magnitude longer than a dozen lines  https://github.com/eugenesvk/kbdHelix/blob/modifew/config/modifew.toml

**Comment by gerardroche** [comment]
Why are you using Sublime Text and NeoVintageous instead of Helix?

**Comment by eugenesvk** [comment]
Because Helix is too far away from matching ST's functionality, has no GUI and no extensions, but unfortunately "inherits" some of the flaws of other editors like failing to work with alternative layouts
