### ISSUE TITLE
Document all implemented functionality

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#884]
There are no canonical resources that documents all the functionality that NeoVintageous has implemented. The Vim documentation is bundled with NeoVintageous without modification. I think it's maybe time to try and document all the functionality that is implemented. This will help with confusions about feature status and also discoverability. 

I'm not quiet sure yet how to go about this. It seems a lot of work to copy and rewrite chunks of the Vim docs, but I don't see any other way, and it would be nice to have NeoVintageous docs like Vim's but documenting all NeoVintageous's functionality properly, even if it means simply copying portions of the Vim's docs. Keeping those copied sections up to date could be challenging and tedious.

It would also be nice to have a simple long list of what has been implemented.

It might also be time to do a github pages doc site.

**Comment by sourcevault** [comment]
If you need help with this, please let me know 🙏.

**Comment by gerardroche** [comment]
I think there are two parts to this.

- Documentation via something like github-pages
- Vim help documentation 

Both of these documentation are the same, except in different output formats. the github-pages docs will be available online. The vim help pages are help pages available via `:help {subject}` inside nv and unlike the current help pages are specific to nv.

I'm think that we can still provide the unmodified version of the vim docs via something like `help vim:{subject}`. So you would still be able to lookup the original vim docs. But :help {subject}` should show only specific help pages on nv. 

I think the original vim docs can be intimidating to new users and confusing to all users when nv doesn't work as documented. nv is a emulation and will never fully implement everything in vim. Even if it did, it would still differ in some ways.

### Index of implemented functionality 

Irregardless of the above. I think a full comprehensive list of everything implemented would be great. Not just for end users. It will be helpful to see what features we're missing and make it easier for users to make feature requests.

The index can be done separately from the documentation updates and is priority.

I'll start a list tonight and you can help me get it up to date.

**Comment by gerardroche** [comment]
I added an initial document here: https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md 

I browsed the VsCode roadmap: https://github.com/VSCodeVim/Vim/blob/HEAD/ROADMAP.md

I'm not sure about documenting the commands in this list. It seems redundant as there will be additional documentations. This list is really just a quick overview index of what is available. It's a lot. I only done a few things. 

When it's up to date it will be easy to keep it up to date.

**Comment by sourcevault** [comment]
> Both of these documentation are the same, except in different output formats. the github-pages docs will be available online. The vim help pages are help pages available via :help {subject} inside nv and unlike the current help pages are specific to nv.

IMHO the online doc should be the priority. 

vim style help is not really that helpful for learning how to use it, it lacks many important things. 

> https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md

This one is great ! 😄 exactly what I had in mind, but it has to be made visible for the ones looking for it. 

A lot of your documentation is in various places and hard to get access to for a newbie, would you mind if I create a page to make it easily discoverable ? 

I will be able to talk about it, if you ping me [here](mailto:sourcevault.pub@gmail.com).

**Comment by gerardroche** [comment]
I agree. The vim docs require a user to know some vim. It's a big ask.

I intentionally didn't expose the roadmap yet until it's more up to date. There's still a lot of things that haven't been added yet. I don't really want to expose it until a good chunk of it is done. Documenting it really drives home how much is actually done.

Maybe by the end of the week it'll be enough done. Then we can really highlight in the readme.

Yeah, go ahead and make a page. You're thinking of a kind of introduction for new users to get started?

I will maybe get time tomorrow evening.

**Comment by sourcevault** [comment]
> I agree. The vim docs require a user to know some vim. It's a big ask.

Are you being sarcastic, I cannot tell.

My main way of learning Sublime Text was through short videos that are easy to digest, like the excellent timeless series called ['Perfect WorkFlow in Sublime Text 2' by NetTuts](https://www.youtube.com/watch?v=U5ZYOmo0KuI).

Vim is really difficult unless it is made a lot more accessible.

> Yeah, go ahead and make a page. You're thinking of a kind of introduction for new users to get started?

For now some documentation for people who were clueless like me 2 months ago, nothing too fancy.

**Comment by gerardroche** [comment]
No not at all. What I mean is that: in order to use the vim help pages, you to know various navigation commands, jumps, command line. A new user can be easily overwhelmed by it. It's a little easier in sublime.

I got frustrated a lot when I started.

I remember I liked the vimcast series: http://vimcasts.org/episodes/page/8/

**Comment by gerardroche** [comment]
Have you tried `vimtutor`? Run `vimtuor` from the command line.

**Comment by sourcevault** [comment]
> I remember I liked the vimcast series: http://vimcasts.org/episodes/page/8/

something similar is needed for NeoVintageous, but it requires a lot of work, I will have to co-ordinate with you somehow.

**Comment by gerardroche** [comment]
I made a big update to the roadmap: https://github.com/NeoVintageous/NeoVintageous/blob/master/ROADMAP.md

I think have at least 80% of the implemented features listed.

I think we still need documentation site where each section can be a different page and include some context  like the vim docs. But this big list is useful. Later when there's a documentation site, the description columns can maybe be replaced with links to the documentation instead of long descriptions.

**Comment by gerardroche** [comment]
I'm gonna close this. I've updated both ROADMAP.md and README.md with an index of what of what is implemented and fleshed out a good bit of documentation in the readme. It's currently in the develop branch, but I'll be cutting a beta release soon: https://github.com/NeoVintageous/NeoVintageous/tree/develop 

The readme docs can be moved to a dedicated docs site later.
