### ISSUE TITLE
No animated/smooth scrolling with NeoVintageous `<C-d>` or `<C-u>`

### ISSUE THREAD

**Issue by Manuzor** [NeoVintageous/NeoVintageous#913]
Is there a way to turn on animated scrolling with some settings?

I'm pretty new to NeoVintageous but one thing immediately stuck out. Scrolling half pages with `<C-d>` or `<C-u>` behaves differently than scrolling with, say, the mouse or `PageDown` or `PageUp`, even while NeoVintageous is enabled. The "native" sublime scrolling smoothly animates to the destination view location while NeoVintageous scrolling is immediate and jumps to the destination.

I'm on Windows 11 if that is relevant at all.

I tried looking around and hope I didn't miss an existing issue about this. Also didn't find anything in the NeoVintageous specific docs.

**Comment by gerardroche** [comment]
Good catch. It will be resolved in the next release.  I didn't notice this
because as weird as it may seem I actually disable animations.

Menu → Preferences → Settings

```js
"animation_enabled": true,
```

I've re-enabled them. Gonna leave it on for a while and see if I still prefer
them off.
