### ISSUE TITLE
Multiline paste works badly

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#93]
<a href="https://github.com/firetech"><img src="https://avatars0.githubusercontent.com/u/104522?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [firetech](https://github.com/firetech)**
_Monday Feb 16, 2015 at 16:03 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/826_

----

After selecting a block of text using either visual block (ctrl-v), select mode (gh) or the built-in mouse based method (https://www.sublimetext.com/docs/2/column_selection.html) and then using p or P to paste, I get really weird results.

For example, I have this text:

> THIS IS A TEXT
> THIS IS A TEXT
> THIS IS A TEXT

Selecting "THIS " (word and following space) on every line, yanking with y and then pasting with p (still in multiline mode, but no text selected, cursor at the start of each line), I get:

> THIS IS A TTHIS EXT
> THIS ITHIS S A TEXT
> TTHIS HIS IS A TEXT

If I use P to paste instead, I get:

> THIS THIS THIS THIS IS A TEXT
> THIS IS A TEXT
> THIS IS A TEXT

All the selected text is yanked and pasted in both cases, just not in the right places.

Using the built in copy/paste methods, I get the expected result:

> THIS THIS IS A TEXT
> THIS THIS IS A TEXT
> THIS THIS IS A TEXT

If I instead copy a single word of text and try to paste it in a block selection, it works differently, for example with "THAT" yanked and selecting "THIS" on every line selected using ctrl-v, pasting with p, I get:

> THIS IS A TEXTHATT
> THIS IS ATHAT TEXT
> THIS THATIS A TEXT

(With P, nothing happens)

If I use select mode or the mouse in this case, p actually works as expected (but if the new text is not the same length as the replaced text, the multiline cursors end up scattered all over the text):

> THAT IS A TEXT
> THAT IS A TEXT
> THAT IS A TEXT

(P in this case also works, but only affects the first line.)

**Comment by ghking1** [comment]
I have the same problem，it‘s real bad without multiline mode paste

**Comment by gerardroche** [comment]
@firetech This has been fixed in 1.16.0 (NeoVintageous is a fork of the discontinued Vintageous plugin).
