### ISSUE TITLE
Maintain cursor positon on Enter+Leave Insert mode

### ISSUE THREAD

**Issue by eugenesvk** [NeoVintageous/NeoVintageous#934]
Currently when you enter and exit insert mode the cursor moves by 1 to the left, that's very unexpected
Is there a way to switch this to maintain cursor position?

**Comment by gerardroche** [comment]
This is the same in Vim. I don't know what the reasoning is, but no doubt there is one.

**Comment by eugenesvk** [comment]
> This is the same in Vim. I don't know what the reasoning is, but no doubt there is one.

Sure there is one, it's just not a good one

https://vimhelp.org/vim_faq.txt.html#faq-10.2

> No. It is not possible to change this behavior. The cursor is always positioned on a valid character (unless you have virtual-edit mode enabled). So, if you are appending text to the end of a line, when you return to command mode the cursor must drop back onto the last character you typed. For consistency sake, the cursor drops back everywhere, even if you are in the middle of a line.

First, it's perfectly possible to rest on the valid newline character like some other text editors do
Second, consistency with the more rare case of a line end is less desirable vs. the most basic intuition that enter/exit should not change anything, it's better for the line end to be special

But I'm not arguing for a change in the bad defaults, I'd just like to be able to configure them to be better

**Comment by gerardroche** [comment]
It has never bothered me. It's not something I want to add, because I think it's fine as it is. I bow to the Vim devs.
