### ISSUE TITLE
Normal mode broken in 1.32 (.1?)

### ISSUE THREAD

**Issue by nikhilm** [NeoVintageous/NeoVintageous#958]
**Describe the bug**

(Related: PackageControl has 1.32.1 listed as the latest version, while on Github it is 1.31.0.)

In normal mode, I'm unable to use any keys for navigation. I see the following error in the console.

```
Traceback (most recent call last):
  File "/opt/sublime_text/Lib/python38/sublime_plugin.py", line 1657, in run_
    return self.run(**args)
TypeError: run() got an unexpected keyword argument 'character'
```

This is a regression between 1.31 and 1.32.1, since on another machine that is still on 1.31.0, I am able to use normal mode just fine.

**To Reproduce**

Enable NeoVintageous via Package Control.

**Expected behaviour**

I am able to use regular keybindings for movement in normal mode.

**Actual behaviour**

Key bindings do not actually cause movement. Instead there are errors in the console.

**Versions**
ST4 Linux Build 4152
NeoVintageous 1.32.1

**Comment by nikhilm** [comment]
I forgot to mention I see this error _every time I press a key_. Unfortunately that is all the stacktrace :/

**Comment by nikhilm** [comment]
If it helps with the investigation - Ctrl + F and Ctrl + B for moving a page at a time _are working_.

**Comment by nikhilm** [comment]
I believe https://github.com/NeoVintageous/NeoVintageous/commit/cc774993d41de5e2a07110eba5e0ff994b9406c5 is the regression.

Please don't take this as me telling you how to write ST plugins :) Inheriting from `WindowCommand` and then overriding a method `run()` that is explicitly marked private, sounds like a bad idea.

**Comment by gerardroche** [comment]
I'm pretty sure the run method being marked as private is a documentation error. Commands need to define a run method.

It looks like you have the new keymap command calling the old window command. Did you try restarting Sublime? Perhaps during the upgrade the plugin wasn't reloaded properly so it still has the old command but the new keymap passing the character argument.

**Comment by nikhilm** [comment]
> It looks like you have the new keymap command calling the old window command. Did you try restarting Sublime? Perhaps during the upgrade the plugin wasn't reloaded properly so it still has the old command but the new keymap passing the character argument.

🤦🏽 Thanks! I should have tried this first. Sorry to waste your time.

**Comment by gerardroche** [comment]
No worries. Sorry about that. It was a fairly big update. 

Most minor releases need a restart. Usually you get prompted to restart Sublime, but sometimes the reloading doesn't throw any error and reloads silently so the plugin thinks it has reloaded without issue.

I try to keep patch releases very small, so that even if a restart is needed for the fixes to take effect, it should still work fine without a restart. Minor releases tend to have much bigger changes and that's when reloading can be an issue.
