### ISSUE TITLE
Mapping double quotes

### ISSUE THREAD

**Issue by gerardroche** [NeoVintageous/NeoVintageous#98]
<a href="https://github.com/adamk33n3r"><img src="https://avatars1.githubusercontent.com/u/1350444?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [adamk33n3r](https://github.com/adamk33n3r)**
_Wednesday Jan 14, 2015 at 22:48 GMT_
_Originally opened as https://github.com/guillermooo/Vintageous/issues/811_

----

I try to map double quotes and it doesn't work. Single quotes work.

e.g. nmap "" dd

It registers the map because in the bottom left I can see the first quote and then when I push the second it goes away. I just doesn't execute "dd" like it should.

**Comment by gerardroche** [comment]
@adamk33n3r I'm unable to reproduce this. Perhaps it has been fixed. The last few versions made some improvements to the `.vintageousrc` file. The latest version is `1.2.0`. What I have tried:

Open config file: `Command Palette > Open My .vintageousrc File`

```
nmap " dd
```
Reload config file: `Command Palette > Reload My .vintageousrc File`

`"` is now mapped to `dd` correctly.

**Comment by adamk33n3r** [comment]
I stopped using sublime ages ago so I don't really have much input in this. I do notice that you're using single quotes `'`, though. I mention in the issue that single quotes work. It's double quotes `"` that don't. So for me, at the time, `nmap '' dd` (two single quotes) worked but `nmap "" dd` (two double quotes) didn't.

**Comment by gerardroche** [comment]
Thanks! Indeed, the two double quotes doesn't work.
