### ISSUE TITLE
Sneak won't jump to "g{char}"

### ISSUE THREAD

**Issue by unifreak** [NeoVintageous/NeoVintageous#984]
**Describe the bug**

When trying to use `s` or `S` for jumping to a {char}{char} combination starting with char `g`, sneak does nothing.

**To Reproduce**

Steps to reproduce the behaviour:

1. write a line like `it's good practice`
2. place cursor before `good`
3. type `sgo` trying to place cursor on `good`
4. nothing happens

Same if we use `S` for backward jump.

**Expected behaviour**

Sneak jumps to `good`

**Actual behaviour**

Sneak does nothing.

**Versions**

`startup, version: 4152 linux x64 channel: stable`

**Comment by gerardroche** [comment]
I can't reproduce the issue.

Is specifically only for "sg{char}"? Does it work for other characters?

Sneak is disabled by default and needs to be enable by setting `vintageous_enable_sneak` to true.

There may be some keybinding conflict. Try debugging to see if there are
any conficts:

Console Logging: View console logging by navigating to Menu → View → Show Console.

Command and Input Logging: Enable command and input logging by running the following commands in the console:

    sublime.log_commands(True)
    sublime.log_input(True)

**Comment by unifreak** [comment]
You're right, using the debug tip, it shows that `sgo` somehow triggered `go` which is a keybinding for "Open Search Result" command. (forget when I have installed that plugin), uninstall/disable the "Open Search Result" plugin fixed this.

Thanks!

**Comment by gerardroche** [comment]
Thank for the follow up.

Fyi, in cases like this it's better to use a mapping. For example in the
case of mapping the open search result:


```vim
nnoremap go :OpenSearchResult<CR>
```

Or better still, use a leader key:


```vim
let mapleader=,
nnoremap <leader>go :OpenSearchResult<CR>
```

One of the issues with the Open Search Results plugin is that there is
no way to disable the existing key binding, but I don't think they
should define that key binding at all.

I think they should just provide instructions on how to create it,
either as an rc file mapping or key binding.


To edit the neovintageousrc file, follow these steps:

1. Open the Command Palette: `Command Palette → NeoVintageous: Open neovintageousrc file`.

2. Make the necessary changes to the file.

3. To apply the changes, reload the neovintageousrc from the Command Palette: `Command Palette → NeoVintageous: Reload neovintageousrc file`.


See the [README](https://github.com/NeoVintageous/NeoVintageous) for
documentation on using mappings.
