### ISSUE TITLE
How to get back block caret only in normal mode

### ISSUE THREAD

**Issue by maxim** [NeoVintageous/NeoVintageous#990]
For those of you who update NeoVintageous and stumble on this:

It used to be that with `"block_caret": true` in Sublime settings, the caret would be `|` in insert mode, and block in normal mode.

Since [this commit](https://github.com/NeoVintageous/NeoVintageous/commit/dd47b2dafb71623df4e3e17c96172f4b1e1cf9df), looks like you'll have block in both insert and normal modes. If you want the previous behavior back, remove the `"block_caret": true` setting (it's false by default).

I had to get there by trial and error, so sharing this here. I do recommend to mention this in the changelog.

**Comment by gerardroche** [comment]
Yea, this was added to support block caret in insert mode.

You have block caret enabled, but you don't want block caret enabled in
NeoVintageous?

I thought about adding a specific NeoVintageous setting for enabling
block caret in insert mode, but I figured anyone enabling block caret
would want it enabled everywhere.

Would a specific NeoVintageous setting for a block caret in
insert mode be better?

**Comment by maxim** [comment]
Makes sense now! 👍🏻

Since I unknowingly kept `block_caret` on for the wrong reason (why would I keep it on if it didn't do anything, right?), at first this update seemed to have broken something, and I took some time troubleshooting what happened. Which is why I'd still mention it somewhere, or hopefully someone will find this issue. We can close it either way. Thank you for building this awesome package! ❤️
