### ISSUE TITLE
Go back to previous buffer

### ISSUE THREAD

**Issue by korgoth** [NeoVintageous/NeoVintageous#993]
in vim using :b# sends you back to the previously edited buffer (no matter the order of buffers). 

I see that Neovintageous has a :bp command, but it doesnt quite do that - it just scrolls back in the buffer list. 

is :b# something that can be implemented? 

Thanks!

**Comment by gerardroche** [comment]
I don't see why not. We already have  the `#` register, see `:registers`. 

I think the `#` register is already used for commands like `CTRL-^` (`CTRL-6` on some keyboards), which switches to and from the current/previous buffer i.e. switch to the file in the `#` register.

The `:buffer` command should take a parameter `:buffer [N]`: Edit buffer `[N]` from the buffer list.  If `[N]` is not given, the current buffer remains being edited. If `[N]` is `#` it should substitute the `#` register value.

**Comment by gerardroche** [comment]
I've implemented this for the next version 1.35.0. It works the same as
`CTRL-^` or `CTRL-6`, which is already available in the current release.
