### ISSUE TITLE
Goto definition gd and gD not working

### ISSUE THREAD

**Issue by JonathanHolvey** [NeoVintageous/NeoVintageous#995]
**Describe the bug**

The `gd` and `gD` shortcuts for goto definition no longer work.

**To Reproduce**

Steps to reproduce the behaviour:

1. Create a file with a symbol and a reference to that symbol, for example:
    ```javascript
    // example.js
    const foo = () => 'bar' // Symbol
    foo() // Reference
    ```
3. In normal mode, place the cursor in the reference name and type `gd`

Documentation for this feature: https://github.com/NeoVintageous/NeoVintageous/blob/e330372152d48c2d985580cd932786d14d73d1cf/res/doc/tips.txt#L62-L63

**Expected behaviour**

The cursor should jump to the symbol.

**Actual behaviour**

Nothing happens - the cursor remains in its original position.

The `gD` command also does nothing when accessing a definition in another file.

**Versions**

Sublime Text: `startup, version: 4169 windows x64 channel: stable`
NeoVintageous: v1.34.1

**Additional Information**

The built in 'Goto Definition' works fine via the context menu or <kbd>F12</kbd>.

**Comment by gerardroche** [comment]
I can't reproduce this.

Enable sublime command logging and inspect the console, you should see something like:

```
command: nv_feed_key
command: nv_vi_go_to_symbol {"count": 1, "globally": false, "mode": "mode_normal"}
command: add_jump_record {"selection": [[727, 727]]}
```

The important part `nv_vi_go_to_symbol`, is it being called?

Perhaps `gd` and `gD` are being shadowed by something else. 

See https://github.com/NeoVintageous/NeoVintageous/blob/master/.github/CONTRIBUTING.md#debugging

You can also install https://packagecontrol.io/packages/ToggleDebugMode, which will give you a developer tools menu to toggle various sublime text logging capabilities.

Also, you can try inspecting the symbol index directly to rule that out as a problem, run this in console (`Menu -> View -> Show Console`):

```
sublime.active_window().lookup_symbol_in_index('foo')
``` 

You should see something like:

```
>>> sublime.active_window().lookup_symbol_in_index('foo')
[('/path/to/project/js/example.js', 'app/js/example.js', (24, 7))]
```

If you don't, the file is not being indexed for some reason e.g. perhaps it's in sublime's index exclusion list.

P.S. There is also the `CTRL-]` command which maps to goto definition.

**Comment by JonathanHolvey** [comment]
Thanks for the detailed pointers. NV is in fact working fine, and it's the index that was faulty. Re-indexing everything solved the problem.
